// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clinics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClinic = `-- name: CreateClinic :one

INSERT INTO clinics (
    clinic_name, clinic_type, registration_number, primary_phone, 
    email, physical_address, city, province, postal_code, country,
    latitude, longitude, description, ownership_type, 
    accepts_medical_aid, verification_status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, clinic_name, clinic_type, city, province, 
    verification_status, created_at, updated_at
`

type CreateClinicParams struct {
	ClinicName         string         `json:"clinic_name"`
	ClinicType         string         `json:"clinic_type"`
	RegistrationNumber pgtype.Text    `json:"registration_number"`
	PrimaryPhone       pgtype.Text    `json:"primary_phone"`
	Email              pgtype.Text    `json:"email"`
	PhysicalAddress    string         `json:"physical_address"`
	City               pgtype.Text    `json:"city"`
	Province           pgtype.Text    `json:"province"`
	PostalCode         pgtype.Text    `json:"postal_code"`
	Country            pgtype.Text    `json:"country"`
	Latitude           pgtype.Numeric `json:"latitude"`
	Longitude          pgtype.Numeric `json:"longitude"`
	Description        pgtype.Text    `json:"description"`
	OwnershipType      pgtype.Text    `json:"ownership_type"`
	AcceptsMedicalAid  pgtype.Bool    `json:"accepts_medical_aid"`
	VerificationStatus pgtype.Text    `json:"verification_status"`
}

type CreateClinicRow struct {
	ID                 pgtype.UUID      `json:"id"`
	ClinicName         string           `json:"clinic_name"`
	ClinicType         string           `json:"clinic_type"`
	City               pgtype.Text      `json:"city"`
	Province           pgtype.Text      `json:"province"`
	VerificationStatus pgtype.Text      `json:"verification_status"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

// ============================================
// Clinic Queries
// ============================================
func (q *Queries) CreateClinic(ctx context.Context, arg CreateClinicParams) (CreateClinicRow, error) {
	row := q.db.QueryRow(ctx, createClinic,
		arg.ClinicName,
		arg.ClinicType,
		arg.RegistrationNumber,
		arg.PrimaryPhone,
		arg.Email,
		arg.PhysicalAddress,
		arg.City,
		arg.Province,
		arg.PostalCode,
		arg.Country,
		arg.Latitude,
		arg.Longitude,
		arg.Description,
		arg.OwnershipType,
		arg.AcceptsMedicalAid,
		arg.VerificationStatus,
	)
	var i CreateClinicRow
	err := row.Scan(
		&i.ID,
		&i.ClinicName,
		&i.ClinicType,
		&i.City,
		&i.Province,
		&i.VerificationStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClinicByID = `-- name: GetClinicByID :one
SELECT id, clinic_name, clinic_type, registration_number, accreditation_number, primary_phone, secondary_phone, emergency_phone, email, website, physical_address, city, province, postal_code, country, latitude, longitude, google_place_id, description, year_established, ownership_type, bed_count, operating_hours, services, specialties, languages_spoken, facilities, accepts_medical_aid, medical_aid_providers, payment_methods, fee_structure, accreditation_body, accreditation_expiry, certifications, is_verified, verification_status, verification_notes, verified_by, verification_date, patient_capacity, average_wait_time_minutes, rating, review_count, contact_person_name, contact_person_role, contact_person_phone, contact_person_email, created_at, updated_at FROM clinics WHERE id = $1
`

func (q *Queries) GetClinicByID(ctx context.Context, id pgtype.UUID) (Clinic, error) {
	row := q.db.QueryRow(ctx, getClinicByID, id)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.ClinicName,
		&i.ClinicType,
		&i.RegistrationNumber,
		&i.AccreditationNumber,
		&i.PrimaryPhone,
		&i.SecondaryPhone,
		&i.EmergencyPhone,
		&i.Email,
		&i.Website,
		&i.PhysicalAddress,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.GooglePlaceID,
		&i.Description,
		&i.YearEstablished,
		&i.OwnershipType,
		&i.BedCount,
		&i.OperatingHours,
		&i.Services,
		&i.Specialties,
		&i.LanguagesSpoken,
		&i.Facilities,
		&i.AcceptsMedicalAid,
		&i.MedicalAidProviders,
		&i.PaymentMethods,
		&i.FeeStructure,
		&i.AccreditationBody,
		&i.AccreditationExpiry,
		&i.Certifications,
		&i.IsVerified,
		&i.VerificationStatus,
		&i.VerificationNotes,
		&i.VerifiedBy,
		&i.VerificationDate,
		&i.PatientCapacity,
		&i.AverageWaitTimeMinutes,
		&i.Rating,
		&i.ReviewCount,
		&i.ContactPersonName,
		&i.ContactPersonRole,
		&i.ContactPersonPhone,
		&i.ContactPersonEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClinics = `-- name: ListClinics :many
SELECT id, clinic_name, clinic_type, city, province, 
    physical_address, primary_phone, email, is_verified,
    verification_status, rating, review_count, created_at
FROM clinics
WHERE 
    ($1::VARCHAR IS NULL OR clinic_type = $1)
    AND ($2::VARCHAR IS NULL OR province = $2)
    AND ($3::VARCHAR IS NULL OR city = $3)
    AND ($4::VARCHAR IS NULL OR verification_status = $4)
ORDER BY rating DESC NULLS LAST, created_at DESC
LIMIT $5 OFFSET $6
`

type ListClinicsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListClinicsRow struct {
	ID                 pgtype.UUID      `json:"id"`
	ClinicName         string           `json:"clinic_name"`
	ClinicType         string           `json:"clinic_type"`
	City               pgtype.Text      `json:"city"`
	Province           pgtype.Text      `json:"province"`
	PhysicalAddress    string           `json:"physical_address"`
	PrimaryPhone       pgtype.Text      `json:"primary_phone"`
	Email              pgtype.Text      `json:"email"`
	IsVerified         pgtype.Bool      `json:"is_verified"`
	VerificationStatus pgtype.Text      `json:"verification_status"`
	Rating             pgtype.Numeric   `json:"rating"`
	ReviewCount        pgtype.Int4      `json:"review_count"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ListClinics(ctx context.Context, arg ListClinicsParams) ([]ListClinicsRow, error) {
	rows, err := q.db.Query(ctx, listClinics,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClinicsRow{}
	for rows.Next() {
		var i ListClinicsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClinicName,
			&i.ClinicType,
			&i.City,
			&i.Province,
			&i.PhysicalAddress,
			&i.PrimaryPhone,
			&i.Email,
			&i.IsVerified,
			&i.VerificationStatus,
			&i.Rating,
			&i.ReviewCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchClinics = `-- name: SearchClinics :many
SELECT id, clinic_name, clinic_type, city, province, 
    physical_address, primary_phone, rating, review_count
FROM clinics
WHERE 
    clinic_name ILIKE '%' || $1 || '%'
    AND ($2::VARCHAR IS NULL OR province = $2)
    AND ($3::VARCHAR IS NULL OR city = $3)
    AND verification_status = 'verified'
ORDER BY rating DESC NULLS LAST
LIMIT $4 OFFSET $5
`

type SearchClinicsParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Column2 string      `json:"column_2"`
	Column3 string      `json:"column_3"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type SearchClinicsRow struct {
	ID              pgtype.UUID    `json:"id"`
	ClinicName      string         `json:"clinic_name"`
	ClinicType      string         `json:"clinic_type"`
	City            pgtype.Text    `json:"city"`
	Province        pgtype.Text    `json:"province"`
	PhysicalAddress string         `json:"physical_address"`
	PrimaryPhone    pgtype.Text    `json:"primary_phone"`
	Rating          pgtype.Numeric `json:"rating"`
	ReviewCount     pgtype.Int4    `json:"review_count"`
}

func (q *Queries) SearchClinics(ctx context.Context, arg SearchClinicsParams) ([]SearchClinicsRow, error) {
	rows, err := q.db.Query(ctx, searchClinics,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchClinicsRow{}
	for rows.Next() {
		var i SearchClinicsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClinicName,
			&i.ClinicType,
			&i.City,
			&i.Province,
			&i.PhysicalAddress,
			&i.PrimaryPhone,
			&i.Rating,
			&i.ReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchClinicsByLocation = `-- name: SearchClinicsByLocation :many
SELECT id, clinic_name, clinic_type, physical_address, city, 
    province, primary_phone, latitude, longitude, rating,
    -- Calculate distance using Haversine formula (approximate)
    (6371 * acos(
        cos(radians($1)) * cos(radians(latitude)) * 
        cos(radians(longitude) - radians($2)) + 
        sin(radians($1)) * sin(radians(latitude))
    )) AS distance_km
FROM clinics
WHERE 
    latitude IS NOT NULL 
    AND longitude IS NOT NULL
    AND verification_status = 'verified'
    AND (6371 * acos(
        cos(radians($1)) * cos(radians(latitude)) * 
        cos(radians(longitude) - radians($2)) + 
        sin(radians($1)) * sin(radians(latitude))
    )) <= $3
ORDER BY distance_km ASC
`

type SearchClinicsByLocationParams struct {
	Radians   float64        `json:"radians"`
	Radians_2 float64        `json:"radians_2"`
	Latitude  pgtype.Numeric `json:"latitude"`
}

type SearchClinicsByLocationRow struct {
	ID              pgtype.UUID    `json:"id"`
	ClinicName      string         `json:"clinic_name"`
	ClinicType      string         `json:"clinic_type"`
	PhysicalAddress string         `json:"physical_address"`
	City            pgtype.Text    `json:"city"`
	Province        pgtype.Text    `json:"province"`
	PrimaryPhone    pgtype.Text    `json:"primary_phone"`
	Latitude        pgtype.Numeric `json:"latitude"`
	Longitude       pgtype.Numeric `json:"longitude"`
	Rating          pgtype.Numeric `json:"rating"`
	DistanceKm      int32          `json:"distance_km"`
}

func (q *Queries) SearchClinicsByLocation(ctx context.Context, arg SearchClinicsByLocationParams) ([]SearchClinicsByLocationRow, error) {
	rows, err := q.db.Query(ctx, searchClinicsByLocation, arg.Radians, arg.Radians_2, arg.Latitude)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchClinicsByLocationRow{}
	for rows.Next() {
		var i SearchClinicsByLocationRow
		if err := rows.Scan(
			&i.ID,
			&i.ClinicName,
			&i.ClinicType,
			&i.PhysicalAddress,
			&i.City,
			&i.Province,
			&i.PrimaryPhone,
			&i.Latitude,
			&i.Longitude,
			&i.Rating,
			&i.DistanceKm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClinic = `-- name: UpdateClinic :exec
UPDATE clinics
SET clinic_name = $2, primary_phone = $3, email = $4, 
    description = $5, operating_hours = $6, services = $7,
    specialties = $8, accepts_medical_aid = $9
WHERE id = $1
`

type UpdateClinicParams struct {
	ID                pgtype.UUID `json:"id"`
	ClinicName        string      `json:"clinic_name"`
	PrimaryPhone      pgtype.Text `json:"primary_phone"`
	Email             pgtype.Text `json:"email"`
	Description       pgtype.Text `json:"description"`
	OperatingHours    []byte      `json:"operating_hours"`
	Services          []byte      `json:"services"`
	Specialties       []byte      `json:"specialties"`
	AcceptsMedicalAid pgtype.Bool `json:"accepts_medical_aid"`
}

func (q *Queries) UpdateClinic(ctx context.Context, arg UpdateClinicParams) error {
	_, err := q.db.Exec(ctx, updateClinic,
		arg.ID,
		arg.ClinicName,
		arg.PrimaryPhone,
		arg.Email,
		arg.Description,
		arg.OperatingHours,
		arg.Services,
		arg.Specialties,
		arg.AcceptsMedicalAid,
	)
	return err
}

const verifyClinic = `-- name: VerifyClinic :exec
UPDATE clinics
SET is_verified = TRUE, verification_status = 'verified',
    verified_by = $2, verification_date = NOW(),
    verification_notes = $3
WHERE id = $1
`

type VerifyClinicParams struct {
	ID                pgtype.UUID `json:"id"`
	VerifiedBy        pgtype.UUID `json:"verified_by"`
	VerificationNotes pgtype.Text `json:"verification_notes"`
}

func (q *Queries) VerifyClinic(ctx context.Context, arg VerifyClinicParams) error {
	_, err := q.db.Exec(ctx, verifyClinic, arg.ID, arg.VerifiedBy, arg.VerificationNotes)
	return err
}
