// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: clinic_services.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkServiceNameExists = `-- name: CheckServiceNameExists :one
SELECT EXISTS(
    SELECT 1 FROM clinic_services
    WHERE 
        clinic_id = $1
        AND service_name = $2
        AND ($3::uuid IS NULL OR id != $3)
) as exists
`

type CheckServiceNameExistsParams struct {
	ClinicID    pgtype.UUID `json:"clinic_id"`
	ServiceName string      `json:"service_name"`
	Column3     pgtype.UUID `json:"column_3"`
}

func (q *Queries) CheckServiceNameExists(ctx context.Context, arg CheckServiceNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkServiceNameExists, arg.ClinicID, arg.ServiceName, arg.Column3)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createClinicService = `-- name: CreateClinicService :one


INSERT INTO clinic_services (
    clinic_id, service_name, service_category, description,
    duration_minutes, preparation_instructions, follow_up_required, follow_up_days,
    minimum_age, maximum_age, gender_restriction, prerequisites,
    cost, cost_currency, is_covered_by_medical_aid, medical_aid_codes,
    is_active, available_days, requires_appointment, walk_in_allowed,
    provided_by_staff_ids
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18, $19, $20, $21
)
RETURNING id, clinic_id, service_name, service_category, description, duration_minutes, preparation_instructions, follow_up_required, follow_up_days, minimum_age, maximum_age, gender_restriction, prerequisites, cost, cost_currency, is_covered_by_medical_aid, medical_aid_codes, is_active, available_days, requires_appointment, walk_in_allowed, provided_by_staff_ids, popularity_score, average_rating, review_count, created_at, updated_at
`

type CreateClinicServiceParams struct {
	ClinicID                pgtype.UUID    `json:"clinic_id"`
	ServiceName             string         `json:"service_name"`
	ServiceCategory         pgtype.Text    `json:"service_category"`
	Description             pgtype.Text    `json:"description"`
	DurationMinutes         pgtype.Int4    `json:"duration_minutes"`
	PreparationInstructions pgtype.Text    `json:"preparation_instructions"`
	FollowUpRequired        pgtype.Bool    `json:"follow_up_required"`
	FollowUpDays            pgtype.Int4    `json:"follow_up_days"`
	MinimumAge              pgtype.Int4    `json:"minimum_age"`
	MaximumAge              pgtype.Int4    `json:"maximum_age"`
	GenderRestriction       pgtype.Text    `json:"gender_restriction"`
	Prerequisites           []string       `json:"prerequisites"`
	Cost                    pgtype.Numeric `json:"cost"`
	CostCurrency            pgtype.Text    `json:"cost_currency"`
	IsCoveredByMedicalAid   pgtype.Bool    `json:"is_covered_by_medical_aid"`
	MedicalAidCodes         []byte         `json:"medical_aid_codes"`
	IsActive                pgtype.Bool    `json:"is_active"`
	AvailableDays           []string       `json:"available_days"`
	RequiresAppointment     pgtype.Bool    `json:"requires_appointment"`
	WalkInAllowed           pgtype.Bool    `json:"walk_in_allowed"`
	ProvidedByStaffIds      []pgtype.UUID  `json:"provided_by_staff_ids"`
}

// ============================================
// CLINIC SERVICES REPOSITORY QUERIES
// Maps to: Part of ClinicRepository interface (service-related methods)
// Domain: Healthcare Service Management
// ============================================
// ============================================
// CORE CRUD OPERATIONS
// ============================================
func (q *Queries) CreateClinicService(ctx context.Context, arg CreateClinicServiceParams) (ClinicService, error) {
	row := q.db.QueryRow(ctx, createClinicService,
		arg.ClinicID,
		arg.ServiceName,
		arg.ServiceCategory,
		arg.Description,
		arg.DurationMinutes,
		arg.PreparationInstructions,
		arg.FollowUpRequired,
		arg.FollowUpDays,
		arg.MinimumAge,
		arg.MaximumAge,
		arg.GenderRestriction,
		arg.Prerequisites,
		arg.Cost,
		arg.CostCurrency,
		arg.IsCoveredByMedicalAid,
		arg.MedicalAidCodes,
		arg.IsActive,
		arg.AvailableDays,
		arg.RequiresAppointment,
		arg.WalkInAllowed,
		arg.ProvidedByStaffIds,
	)
	var i ClinicService
	err := row.Scan(
		&i.ID,
		&i.ClinicID,
		&i.ServiceName,
		&i.ServiceCategory,
		&i.Description,
		&i.DurationMinutes,
		&i.PreparationInstructions,
		&i.FollowUpRequired,
		&i.FollowUpDays,
		&i.MinimumAge,
		&i.MaximumAge,
		&i.GenderRestriction,
		&i.Prerequisites,
		&i.Cost,
		&i.CostCurrency,
		&i.IsCoveredByMedicalAid,
		&i.MedicalAidCodes,
		&i.IsActive,
		&i.AvailableDays,
		&i.RequiresAppointment,
		&i.WalkInAllowed,
		&i.ProvidedByStaffIds,
		&i.PopularityScore,
		&i.AverageRating,
		&i.ReviewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClinicService = `-- name: DeleteClinicService :exec
DELETE FROM clinic_services 
WHERE id = $1
`

func (q *Queries) DeleteClinicService(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteClinicService, id)
	return err
}

const getActiveClinicServices = `-- name: GetActiveClinicServices :many
SELECT 
    id, clinic_id, service_name, service_category, description,
    duration_minutes, cost, cost_currency, is_covered_by_medical_aid,
    requires_appointment, walk_in_allowed,
    average_rating, review_count, popularity_score
FROM clinic_services
WHERE 
    clinic_id = $1 
    AND is_active = TRUE
ORDER BY popularity_score DESC, service_name ASC
`

type GetActiveClinicServicesRow struct {
	ID                    pgtype.UUID    `json:"id"`
	ClinicID              pgtype.UUID    `json:"clinic_id"`
	ServiceName           string         `json:"service_name"`
	ServiceCategory       pgtype.Text    `json:"service_category"`
	Description           pgtype.Text    `json:"description"`
	DurationMinutes       pgtype.Int4    `json:"duration_minutes"`
	Cost                  pgtype.Numeric `json:"cost"`
	CostCurrency          pgtype.Text    `json:"cost_currency"`
	IsCoveredByMedicalAid pgtype.Bool    `json:"is_covered_by_medical_aid"`
	RequiresAppointment   pgtype.Bool    `json:"requires_appointment"`
	WalkInAllowed         pgtype.Bool    `json:"walk_in_allowed"`
	AverageRating         pgtype.Numeric `json:"average_rating"`
	ReviewCount           pgtype.Int4    `json:"review_count"`
	PopularityScore       pgtype.Int4    `json:"popularity_score"`
}

func (q *Queries) GetActiveClinicServices(ctx context.Context, clinicID pgtype.UUID) ([]GetActiveClinicServicesRow, error) {
	rows, err := q.db.Query(ctx, getActiveClinicServices, clinicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveClinicServicesRow{}
	for rows.Next() {
		var i GetActiveClinicServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.ClinicID,
			&i.ServiceName,
			&i.ServiceCategory,
			&i.Description,
			&i.DurationMinutes,
			&i.Cost,
			&i.CostCurrency,
			&i.IsCoveredByMedicalAid,
			&i.RequiresAppointment,
			&i.WalkInAllowed,
			&i.AverageRating,
			&i.ReviewCount,
			&i.PopularityScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClinicServices = `-- name: GetClinicServices :many

SELECT 
    id, clinic_id, service_name, service_category, description,
    duration_minutes, cost, cost_currency, is_covered_by_medical_aid,
    is_active, requires_appointment, walk_in_allowed,
    average_rating, review_count, popularity_score
FROM clinic_services
WHERE clinic_id = $1 
ORDER BY popularity_score DESC, service_name ASC
`

type GetClinicServicesRow struct {
	ID                    pgtype.UUID    `json:"id"`
	ClinicID              pgtype.UUID    `json:"clinic_id"`
	ServiceName           string         `json:"service_name"`
	ServiceCategory       pgtype.Text    `json:"service_category"`
	Description           pgtype.Text    `json:"description"`
	DurationMinutes       pgtype.Int4    `json:"duration_minutes"`
	Cost                  pgtype.Numeric `json:"cost"`
	CostCurrency          pgtype.Text    `json:"cost_currency"`
	IsCoveredByMedicalAid pgtype.Bool    `json:"is_covered_by_medical_aid"`
	IsActive              pgtype.Bool    `json:"is_active"`
	RequiresAppointment   pgtype.Bool    `json:"requires_appointment"`
	WalkInAllowed         pgtype.Bool    `json:"walk_in_allowed"`
	AverageRating         pgtype.Numeric `json:"average_rating"`
	ReviewCount           pgtype.Int4    `json:"review_count"`
	PopularityScore       pgtype.Int4    `json:"popularity_score"`
}

// ============================================
// QUERYING BY CLINIC
// ============================================
func (q *Queries) GetClinicServices(ctx context.Context, clinicID pgtype.UUID) ([]GetClinicServicesRow, error) {
	rows, err := q.db.Query(ctx, getClinicServices, clinicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClinicServicesRow{}
	for rows.Next() {
		var i GetClinicServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.ClinicID,
			&i.ServiceName,
			&i.ServiceCategory,
			&i.Description,
			&i.DurationMinutes,
			&i.Cost,
			&i.CostCurrency,
			&i.IsCoveredByMedicalAid,
			&i.IsActive,
			&i.RequiresAppointment,
			&i.WalkInAllowed,
			&i.AverageRating,
			&i.ReviewCount,
			&i.PopularityScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, clinic_id, service_name, service_category, description, duration_minutes, preparation_instructions, follow_up_required, follow_up_days, minimum_age, maximum_age, gender_restriction, prerequisites, cost, cost_currency, is_covered_by_medical_aid, medical_aid_codes, is_active, available_days, requires_appointment, walk_in_allowed, provided_by_staff_ids, popularity_score, average_rating, review_count, created_at, updated_at FROM clinic_services
WHERE id = $1
`

func (q *Queries) GetServiceByID(ctx context.Context, id pgtype.UUID) (ClinicService, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i ClinicService
	err := row.Scan(
		&i.ID,
		&i.ClinicID,
		&i.ServiceName,
		&i.ServiceCategory,
		&i.Description,
		&i.DurationMinutes,
		&i.PreparationInstructions,
		&i.FollowUpRequired,
		&i.FollowUpDays,
		&i.MinimumAge,
		&i.MaximumAge,
		&i.GenderRestriction,
		&i.Prerequisites,
		&i.Cost,
		&i.CostCurrency,
		&i.IsCoveredByMedicalAid,
		&i.MedicalAidCodes,
		&i.IsActive,
		&i.AvailableDays,
		&i.RequiresAppointment,
		&i.WalkInAllowed,
		&i.ProvidedByStaffIds,
		&i.PopularityScore,
		&i.AverageRating,
		&i.ReviewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const serviceExists = `-- name: ServiceExists :one
SELECT EXISTS(
    SELECT 1 FROM clinic_services 
    WHERE id = $1
) as exists
`

func (q *Queries) ServiceExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, serviceExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateClinicService = `-- name: UpdateClinicService :exec
UPDATE clinic_services
SET 
    service_name = COALESCE($2, service_name),
    service_category = COALESCE($3, service_category),
    description = COALESCE($4, description),
    duration_minutes = COALESCE($5, duration_minutes),
    cost = COALESCE($6, cost),
    is_covered_by_medical_aid = COALESCE($7, is_covered_by_medical_aid),
    requires_appointment = COALESCE($8, requires_appointment),
    walk_in_allowed = COALESCE($9, walk_in_allowed),
    updated_at = NOW()
WHERE id = $1
`

type UpdateClinicServiceParams struct {
	ID                    pgtype.UUID    `json:"id"`
	ServiceName           string         `json:"service_name"`
	ServiceCategory       pgtype.Text    `json:"service_category"`
	Description           pgtype.Text    `json:"description"`
	DurationMinutes       pgtype.Int4    `json:"duration_minutes"`
	Cost                  pgtype.Numeric `json:"cost"`
	IsCoveredByMedicalAid pgtype.Bool    `json:"is_covered_by_medical_aid"`
	RequiresAppointment   pgtype.Bool    `json:"requires_appointment"`
	WalkInAllowed         pgtype.Bool    `json:"walk_in_allowed"`
}

func (q *Queries) UpdateClinicService(ctx context.Context, arg UpdateClinicServiceParams) error {
	_, err := q.db.Exec(ctx, updateClinicService,
		arg.ID,
		arg.ServiceName,
		arg.ServiceCategory,
		arg.Description,
		arg.DurationMinutes,
		arg.Cost,
		arg.IsCoveredByMedicalAid,
		arg.RequiresAppointment,
		arg.WalkInAllowed,
	)
	return err
}
