// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: clinics.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClinic = `-- name: CreateClinic :one


INSERT INTO clinics (
    created_by, owner_user_id,
    clinic_name, clinic_type, registration_number, accreditation_number,
    primary_phone, secondary_phone, emergency_phone, email, website,
    physical_address, city, province, postal_code, country,
    latitude, longitude, google_place_id,
    description, year_established, ownership_type, bed_count, operating_hours,
    services, specialties, languages_spoken, facilities,
    accepts_medical_aid, medical_aid_providers, payment_methods, fee_structure,
    accreditation_body, accreditation_expiry, certifications,
    patient_capacity, average_wait_time_minutes,
    contact_person_name, contact_person_role, contact_person_phone, contact_person_email
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16,
    $17, $18, $19, $20, $21, $22, $23, $24::jsonb, $25::jsonb, $26::jsonb, $27,
    $28::jsonb, $29, $30::jsonb, $31::jsonb, $32, $33, $34,
    $35::jsonb, $36, $37, $38, $39, $40, $41
)
RETURNING id, created_by, owner_user_id, clinic_name, clinic_type, registration_number, accreditation_number, primary_phone, secondary_phone, emergency_phone, email, website, physical_address, city, province, postal_code, country, latitude, longitude, google_place_id, description, year_established, ownership_type, bed_count, operating_hours, services, specialties, languages_spoken, facilities, accepts_medical_aid, medical_aid_providers, payment_methods, fee_structure, accreditation_body, accreditation_expiry, certifications, is_verified, verification_status, verification_notes, verified_by, verification_date, patient_capacity, average_wait_time_minutes, rating, review_count, contact_person_name, contact_person_role, contact_person_phone, contact_person_email, created_at, updated_at
`

type CreateClinicParams struct {
	CreatedBy              pgtype.UUID     `json:"created_by"`
	OwnerUserID            pgtype.UUID     `json:"owner_user_id"`
	ClinicName             string          `json:"clinic_name"`
	ClinicType             string          `json:"clinic_type"`
	RegistrationNumber     pgtype.Text     `json:"registration_number"`
	AccreditationNumber    pgtype.Text     `json:"accreditation_number"`
	PrimaryPhone           pgtype.Text     `json:"primary_phone"`
	SecondaryPhone         pgtype.Text     `json:"secondary_phone"`
	EmergencyPhone         pgtype.Text     `json:"emergency_phone"`
	Email                  pgtype.Text     `json:"email"`
	Website                pgtype.Text     `json:"website"`
	PhysicalAddress        string          `json:"physical_address"`
	City                   pgtype.Text     `json:"city"`
	Province               pgtype.Text     `json:"province"`
	PostalCode             pgtype.Text     `json:"postal_code"`
	Country                pgtype.Text     `json:"country"`
	Latitude               pgtype.Numeric  `json:"latitude"`
	Longitude              pgtype.Numeric  `json:"longitude"`
	GooglePlaceID          pgtype.Text     `json:"google_place_id"`
	Description            pgtype.Text     `json:"description"`
	YearEstablished        pgtype.Int4     `json:"year_established"`
	OwnershipType          pgtype.Text     `json:"ownership_type"`
	BedCount               pgtype.Int4     `json:"bed_count"`
	Column24               json.RawMessage `json:"column_24"`
	Column25               json.RawMessage `json:"column_25"`
	Column26               json.RawMessage `json:"column_26"`
	LanguagesSpoken        []string        `json:"languages_spoken"`
	Column28               json.RawMessage `json:"column_28"`
	AcceptsMedicalAid      pgtype.Bool     `json:"accepts_medical_aid"`
	Column30               json.RawMessage `json:"column_30"`
	Column31               json.RawMessage `json:"column_31"`
	FeeStructure           pgtype.Text     `json:"fee_structure"`
	AccreditationBody      pgtype.Text     `json:"accreditation_body"`
	AccreditationExpiry    pgtype.Date     `json:"accreditation_expiry"`
	Column35               json.RawMessage `json:"column_35"`
	PatientCapacity        pgtype.Int4     `json:"patient_capacity"`
	AverageWaitTimeMinutes pgtype.Int4     `json:"average_wait_time_minutes"`
	ContactPersonName      pgtype.Text     `json:"contact_person_name"`
	ContactPersonRole      pgtype.Text     `json:"contact_person_role"`
	ContactPersonPhone     pgtype.Text     `json:"contact_person_phone"`
	ContactPersonEmail     pgtype.Text     `json:"contact_person_email"`
}

// ============================================
// CLINIC REPOSITORY QUERIES
// Maps to: ClinicRepository interface
// Domain: Healthcare Provider Management
// ============================================
// ============================================
// CORE CRUD OPERATIONS
// ============================================
func (q *Queries) CreateClinic(ctx context.Context, arg CreateClinicParams) (Clinic, error) {
	row := q.db.QueryRow(ctx, createClinic,
		arg.CreatedBy,
		arg.OwnerUserID,
		arg.ClinicName,
		arg.ClinicType,
		arg.RegistrationNumber,
		arg.AccreditationNumber,
		arg.PrimaryPhone,
		arg.SecondaryPhone,
		arg.EmergencyPhone,
		arg.Email,
		arg.Website,
		arg.PhysicalAddress,
		arg.City,
		arg.Province,
		arg.PostalCode,
		arg.Country,
		arg.Latitude,
		arg.Longitude,
		arg.GooglePlaceID,
		arg.Description,
		arg.YearEstablished,
		arg.OwnershipType,
		arg.BedCount,
		arg.Column24,
		arg.Column25,
		arg.Column26,
		arg.LanguagesSpoken,
		arg.Column28,
		arg.AcceptsMedicalAid,
		arg.Column30,
		arg.Column31,
		arg.FeeStructure,
		arg.AccreditationBody,
		arg.AccreditationExpiry,
		arg.Column35,
		arg.PatientCapacity,
		arg.AverageWaitTimeMinutes,
		arg.ContactPersonName,
		arg.ContactPersonRole,
		arg.ContactPersonPhone,
		arg.ContactPersonEmail,
	)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.OwnerUserID,
		&i.ClinicName,
		&i.ClinicType,
		&i.RegistrationNumber,
		&i.AccreditationNumber,
		&i.PrimaryPhone,
		&i.SecondaryPhone,
		&i.EmergencyPhone,
		&i.Email,
		&i.Website,
		&i.PhysicalAddress,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.GooglePlaceID,
		&i.Description,
		&i.YearEstablished,
		&i.OwnershipType,
		&i.BedCount,
		&i.OperatingHours,
		&i.Services,
		&i.Specialties,
		&i.LanguagesSpoken,
		&i.Facilities,
		&i.AcceptsMedicalAid,
		&i.MedicalAidProviders,
		&i.PaymentMethods,
		&i.FeeStructure,
		&i.AccreditationBody,
		&i.AccreditationExpiry,
		&i.Certifications,
		&i.IsVerified,
		&i.VerificationStatus,
		&i.VerificationNotes,
		&i.VerifiedBy,
		&i.VerificationDate,
		&i.PatientCapacity,
		&i.AverageWaitTimeMinutes,
		&i.Rating,
		&i.ReviewCount,
		&i.ContactPersonName,
		&i.ContactPersonRole,
		&i.ContactPersonPhone,
		&i.ContactPersonEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateClinic = `-- name: DeactivateClinic :exec
UPDATE clinics
SET 
    verification_status = 'rejected',
    is_verified = FALSE,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateClinic(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateClinic, id)
	return err
}

const deleteClinic = `-- name: DeleteClinic :exec
DELETE FROM clinics WHERE id = $1
`

func (q *Queries) DeleteClinic(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteClinic, id)
	return err
}

const getAllClinics = `-- name: GetAllClinics :many
SELECT id, created_by, owner_user_id, clinic_name, clinic_type, registration_number, accreditation_number, primary_phone, secondary_phone, emergency_phone, email, website, physical_address, city, province, postal_code, country, latitude, longitude, google_place_id, description, year_established, ownership_type, bed_count, operating_hours, services, specialties, languages_spoken, facilities, accepts_medical_aid, medical_aid_providers, payment_methods, fee_structure, accreditation_body, accreditation_expiry, certifications, is_verified, verification_status, verification_notes, verified_by, verification_date, patient_capacity, average_wait_time_minutes, rating, review_count, contact_person_name, contact_person_role, contact_person_phone, contact_person_email, created_at, updated_at FROM clinics
`

func (q *Queries) GetAllClinics(ctx context.Context) ([]Clinic, error) {
	rows, err := q.db.Query(ctx, getAllClinics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Clinic{}
	for rows.Next() {
		var i Clinic
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.OwnerUserID,
			&i.ClinicName,
			&i.ClinicType,
			&i.RegistrationNumber,
			&i.AccreditationNumber,
			&i.PrimaryPhone,
			&i.SecondaryPhone,
			&i.EmergencyPhone,
			&i.Email,
			&i.Website,
			&i.PhysicalAddress,
			&i.City,
			&i.Province,
			&i.PostalCode,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.GooglePlaceID,
			&i.Description,
			&i.YearEstablished,
			&i.OwnershipType,
			&i.BedCount,
			&i.OperatingHours,
			&i.Services,
			&i.Specialties,
			&i.LanguagesSpoken,
			&i.Facilities,
			&i.AcceptsMedicalAid,
			&i.MedicalAidProviders,
			&i.PaymentMethods,
			&i.FeeStructure,
			&i.AccreditationBody,
			&i.AccreditationExpiry,
			&i.Certifications,
			&i.IsVerified,
			&i.VerificationStatus,
			&i.VerificationNotes,
			&i.VerifiedBy,
			&i.VerificationDate,
			&i.PatientCapacity,
			&i.AverageWaitTimeMinutes,
			&i.Rating,
			&i.ReviewCount,
			&i.ContactPersonName,
			&i.ContactPersonRole,
			&i.ContactPersonPhone,
			&i.ContactPersonEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClinicByID = `-- name: GetClinicByID :one
SELECT id, created_by, owner_user_id, clinic_name, clinic_type, registration_number, accreditation_number, primary_phone, secondary_phone, emergency_phone, email, website, physical_address, city, province, postal_code, country, latitude, longitude, google_place_id, description, year_established, ownership_type, bed_count, operating_hours, services, specialties, languages_spoken, facilities, accepts_medical_aid, medical_aid_providers, payment_methods, fee_structure, accreditation_body, accreditation_expiry, certifications, is_verified, verification_status, verification_notes, verified_by, verification_date, patient_capacity, average_wait_time_minutes, rating, review_count, contact_person_name, contact_person_role, contact_person_phone, contact_person_email, created_at, updated_at FROM clinics 
WHERE id = $1
`

func (q *Queries) GetClinicByID(ctx context.Context, id pgtype.UUID) (Clinic, error) {
	row := q.db.QueryRow(ctx, getClinicByID, id)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.OwnerUserID,
		&i.ClinicName,
		&i.ClinicType,
		&i.RegistrationNumber,
		&i.AccreditationNumber,
		&i.PrimaryPhone,
		&i.SecondaryPhone,
		&i.EmergencyPhone,
		&i.Email,
		&i.Website,
		&i.PhysicalAddress,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.GooglePlaceID,
		&i.Description,
		&i.YearEstablished,
		&i.OwnershipType,
		&i.BedCount,
		&i.OperatingHours,
		&i.Services,
		&i.Specialties,
		&i.LanguagesSpoken,
		&i.Facilities,
		&i.AcceptsMedicalAid,
		&i.MedicalAidProviders,
		&i.PaymentMethods,
		&i.FeeStructure,
		&i.AccreditationBody,
		&i.AccreditationExpiry,
		&i.Certifications,
		&i.IsVerified,
		&i.VerificationStatus,
		&i.VerificationNotes,
		&i.VerifiedBy,
		&i.VerificationDate,
		&i.PatientCapacity,
		&i.AverageWaitTimeMinutes,
		&i.Rating,
		&i.ReviewCount,
		&i.ContactPersonName,
		&i.ContactPersonRole,
		&i.ContactPersonPhone,
		&i.ContactPersonEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClinicByOwner = `-- name: GetClinicByOwner :one

SELECT id, created_by, owner_user_id, clinic_name, clinic_type, registration_number, accreditation_number, primary_phone, secondary_phone, emergency_phone, email, website, physical_address, city, province, postal_code, country, latitude, longitude, google_place_id, description, year_established, ownership_type, bed_count, operating_hours, services, specialties, languages_spoken, facilities, accepts_medical_aid, medical_aid_providers, payment_methods, fee_structure, accreditation_body, accreditation_expiry, certifications, is_verified, verification_status, verification_notes, verified_by, verification_date, patient_capacity, average_wait_time_minutes, rating, review_count, contact_person_name, contact_person_role, contact_person_phone, contact_person_email, created_at, updated_at FROM clinics
WHERE owner_user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

// ============================================
// PROVIDER REGISTRATION QUERIES
// ============================================
func (q *Queries) GetClinicByOwner(ctx context.Context, ownerUserID pgtype.UUID) (Clinic, error) {
	row := q.db.QueryRow(ctx, getClinicByOwner, ownerUserID)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.OwnerUserID,
		&i.ClinicName,
		&i.ClinicType,
		&i.RegistrationNumber,
		&i.AccreditationNumber,
		&i.PrimaryPhone,
		&i.SecondaryPhone,
		&i.EmergencyPhone,
		&i.Email,
		&i.Website,
		&i.PhysicalAddress,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.GooglePlaceID,
		&i.Description,
		&i.YearEstablished,
		&i.OwnershipType,
		&i.BedCount,
		&i.OperatingHours,
		&i.Services,
		&i.Specialties,
		&i.LanguagesSpoken,
		&i.Facilities,
		&i.AcceptsMedicalAid,
		&i.MedicalAidProviders,
		&i.PaymentMethods,
		&i.FeeStructure,
		&i.AccreditationBody,
		&i.AccreditationExpiry,
		&i.Certifications,
		&i.IsVerified,
		&i.VerificationStatus,
		&i.VerificationNotes,
		&i.VerifiedBy,
		&i.VerificationDate,
		&i.PatientCapacity,
		&i.AverageWaitTimeMinutes,
		&i.Rating,
		&i.ReviewCount,
		&i.ContactPersonName,
		&i.ContactPersonRole,
		&i.ContactPersonPhone,
		&i.ContactPersonEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClinicVerificationStatus = `-- name: GetClinicVerificationStatus :one
SELECT 
    id,
    clinic_name,
    verification_status,
    is_verified,
    verification_notes,
    verification_date,
    created_at
FROM clinics
WHERE id = $1
`

type GetClinicVerificationStatusRow struct {
	ID                 pgtype.UUID      `json:"id"`
	ClinicName         string           `json:"clinic_name"`
	VerificationStatus pgtype.Text      `json:"verification_status"`
	IsVerified         pgtype.Bool      `json:"is_verified"`
	VerificationNotes  pgtype.Text      `json:"verification_notes"`
	VerificationDate   pgtype.Timestamp `json:"verification_date"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetClinicVerificationStatus(ctx context.Context, id pgtype.UUID) (GetClinicVerificationStatusRow, error) {
	row := q.db.QueryRow(ctx, getClinicVerificationStatus, id)
	var i GetClinicVerificationStatusRow
	err := row.Scan(
		&i.ID,
		&i.ClinicName,
		&i.VerificationStatus,
		&i.IsVerified,
		&i.VerificationNotes,
		&i.VerificationDate,
		&i.CreatedAt,
	)
	return i, err
}

const getClinicWithOwnerInfo = `-- name: GetClinicWithOwnerInfo :one
SELECT 
    c.id, c.created_by, c.owner_user_id, c.clinic_name, c.clinic_type, c.registration_number, c.accreditation_number, c.primary_phone, c.secondary_phone, c.emergency_phone, c.email, c.website, c.physical_address, c.city, c.province, c.postal_code, c.country, c.latitude, c.longitude, c.google_place_id, c.description, c.year_established, c.ownership_type, c.bed_count, c.operating_hours, c.services, c.specialties, c.languages_spoken, c.facilities, c.accepts_medical_aid, c.medical_aid_providers, c.payment_methods, c.fee_structure, c.accreditation_body, c.accreditation_expiry, c.certifications, c.is_verified, c.verification_status, c.verification_notes, c.verified_by, c.verification_date, c.patient_capacity, c.average_wait_time_minutes, c.rating, c.review_count, c.contact_person_name, c.contact_person_role, c.contact_person_phone, c.contact_person_email, c.created_at, c.updated_at,
    u.email as owner_email,
    u.phone as owner_phone,
    cs.first_name as owner_first_name,
    cs.last_name as owner_last_name
FROM clinics c
LEFT JOIN users u ON c.owner_user_id = u.id
LEFT JOIN clinic_staff cs ON c.owner_user_id = cs.user_id AND cs.clinic_id = c.id
WHERE c.id = $1
`

type GetClinicWithOwnerInfoRow struct {
	ID                     pgtype.UUID      `json:"id"`
	CreatedBy              pgtype.UUID      `json:"created_by"`
	OwnerUserID            pgtype.UUID      `json:"owner_user_id"`
	ClinicName             string           `json:"clinic_name"`
	ClinicType             string           `json:"clinic_type"`
	RegistrationNumber     pgtype.Text      `json:"registration_number"`
	AccreditationNumber    pgtype.Text      `json:"accreditation_number"`
	PrimaryPhone           pgtype.Text      `json:"primary_phone"`
	SecondaryPhone         pgtype.Text      `json:"secondary_phone"`
	EmergencyPhone         pgtype.Text      `json:"emergency_phone"`
	Email                  pgtype.Text      `json:"email"`
	Website                pgtype.Text      `json:"website"`
	PhysicalAddress        string           `json:"physical_address"`
	City                   pgtype.Text      `json:"city"`
	Province               pgtype.Text      `json:"province"`
	PostalCode             pgtype.Text      `json:"postal_code"`
	Country                pgtype.Text      `json:"country"`
	Latitude               pgtype.Numeric   `json:"latitude"`
	Longitude              pgtype.Numeric   `json:"longitude"`
	GooglePlaceID          pgtype.Text      `json:"google_place_id"`
	Description            pgtype.Text      `json:"description"`
	YearEstablished        pgtype.Int4      `json:"year_established"`
	OwnershipType          pgtype.Text      `json:"ownership_type"`
	BedCount               pgtype.Int4      `json:"bed_count"`
	OperatingHours         []byte           `json:"operating_hours"`
	Services               []byte           `json:"services"`
	Specialties            []byte           `json:"specialties"`
	LanguagesSpoken        []string         `json:"languages_spoken"`
	Facilities             []byte           `json:"facilities"`
	AcceptsMedicalAid      pgtype.Bool      `json:"accepts_medical_aid"`
	MedicalAidProviders    []byte           `json:"medical_aid_providers"`
	PaymentMethods         []byte           `json:"payment_methods"`
	FeeStructure           pgtype.Text      `json:"fee_structure"`
	AccreditationBody      pgtype.Text      `json:"accreditation_body"`
	AccreditationExpiry    pgtype.Date      `json:"accreditation_expiry"`
	Certifications         []byte           `json:"certifications"`
	IsVerified             pgtype.Bool      `json:"is_verified"`
	VerificationStatus     pgtype.Text      `json:"verification_status"`
	VerificationNotes      pgtype.Text      `json:"verification_notes"`
	VerifiedBy             pgtype.UUID      `json:"verified_by"`
	VerificationDate       pgtype.Timestamp `json:"verification_date"`
	PatientCapacity        pgtype.Int4      `json:"patient_capacity"`
	AverageWaitTimeMinutes pgtype.Int4      `json:"average_wait_time_minutes"`
	Rating                 pgtype.Numeric   `json:"rating"`
	ReviewCount            pgtype.Int4      `json:"review_count"`
	ContactPersonName      pgtype.Text      `json:"contact_person_name"`
	ContactPersonRole      pgtype.Text      `json:"contact_person_role"`
	ContactPersonPhone     pgtype.Text      `json:"contact_person_phone"`
	ContactPersonEmail     pgtype.Text      `json:"contact_person_email"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	OwnerEmail             pgtype.Text      `json:"owner_email"`
	OwnerPhone             pgtype.Text      `json:"owner_phone"`
	OwnerFirstName         pgtype.Text      `json:"owner_first_name"`
	OwnerLastName          pgtype.Text      `json:"owner_last_name"`
}

func (q *Queries) GetClinicWithOwnerInfo(ctx context.Context, id pgtype.UUID) (GetClinicWithOwnerInfoRow, error) {
	row := q.db.QueryRow(ctx, getClinicWithOwnerInfo, id)
	var i GetClinicWithOwnerInfoRow
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.OwnerUserID,
		&i.ClinicName,
		&i.ClinicType,
		&i.RegistrationNumber,
		&i.AccreditationNumber,
		&i.PrimaryPhone,
		&i.SecondaryPhone,
		&i.EmergencyPhone,
		&i.Email,
		&i.Website,
		&i.PhysicalAddress,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.GooglePlaceID,
		&i.Description,
		&i.YearEstablished,
		&i.OwnershipType,
		&i.BedCount,
		&i.OperatingHours,
		&i.Services,
		&i.Specialties,
		&i.LanguagesSpoken,
		&i.Facilities,
		&i.AcceptsMedicalAid,
		&i.MedicalAidProviders,
		&i.PaymentMethods,
		&i.FeeStructure,
		&i.AccreditationBody,
		&i.AccreditationExpiry,
		&i.Certifications,
		&i.IsVerified,
		&i.VerificationStatus,
		&i.VerificationNotes,
		&i.VerifiedBy,
		&i.VerificationDate,
		&i.PatientCapacity,
		&i.AverageWaitTimeMinutes,
		&i.Rating,
		&i.ReviewCount,
		&i.ContactPersonName,
		&i.ContactPersonRole,
		&i.ContactPersonPhone,
		&i.ContactPersonEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerEmail,
		&i.OwnerPhone,
		&i.OwnerFirstName,
		&i.OwnerLastName,
	)
	return i, err
}

const getClinicsByCreator = `-- name: GetClinicsByCreator :many
SELECT id, created_by, owner_user_id, clinic_name, clinic_type, registration_number, accreditation_number, primary_phone, secondary_phone, emergency_phone, email, website, physical_address, city, province, postal_code, country, latitude, longitude, google_place_id, description, year_established, ownership_type, bed_count, operating_hours, services, specialties, languages_spoken, facilities, accepts_medical_aid, medical_aid_providers, payment_methods, fee_structure, accreditation_body, accreditation_expiry, certifications, is_verified, verification_status, verification_notes, verified_by, verification_date, patient_capacity, average_wait_time_minutes, rating, review_count, contact_person_name, contact_person_role, contact_person_phone, contact_person_email, created_at, updated_at FROM clinics
WHERE created_by = $1
ORDER BY created_at DESC
`

func (q *Queries) GetClinicsByCreator(ctx context.Context, createdBy pgtype.UUID) ([]Clinic, error) {
	rows, err := q.db.Query(ctx, getClinicsByCreator, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Clinic{}
	for rows.Next() {
		var i Clinic
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.OwnerUserID,
			&i.ClinicName,
			&i.ClinicType,
			&i.RegistrationNumber,
			&i.AccreditationNumber,
			&i.PrimaryPhone,
			&i.SecondaryPhone,
			&i.EmergencyPhone,
			&i.Email,
			&i.Website,
			&i.PhysicalAddress,
			&i.City,
			&i.Province,
			&i.PostalCode,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.GooglePlaceID,
			&i.Description,
			&i.YearEstablished,
			&i.OwnershipType,
			&i.BedCount,
			&i.OperatingHours,
			&i.Services,
			&i.Specialties,
			&i.LanguagesSpoken,
			&i.Facilities,
			&i.AcceptsMedicalAid,
			&i.MedicalAidProviders,
			&i.PaymentMethods,
			&i.FeeStructure,
			&i.AccreditationBody,
			&i.AccreditationExpiry,
			&i.Certifications,
			&i.IsVerified,
			&i.VerificationStatus,
			&i.VerificationNotes,
			&i.VerifiedBy,
			&i.VerificationDate,
			&i.PatientCapacity,
			&i.AverageWaitTimeMinutes,
			&i.Rating,
			&i.ReviewCount,
			&i.ContactPersonName,
			&i.ContactPersonRole,
			&i.ContactPersonPhone,
			&i.ContactPersonEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingVerificationClinics = `-- name: GetPendingVerificationClinics :many
SELECT 
    id, clinic_name, clinic_type, registration_number,
    city, province, email, primary_phone,
    created_at, verification_status
FROM clinics
WHERE verification_status = 'pending'
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type GetPendingVerificationClinicsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetPendingVerificationClinicsRow struct {
	ID                 pgtype.UUID      `json:"id"`
	ClinicName         string           `json:"clinic_name"`
	ClinicType         string           `json:"clinic_type"`
	RegistrationNumber pgtype.Text      `json:"registration_number"`
	City               pgtype.Text      `json:"city"`
	Province           pgtype.Text      `json:"province"`
	Email              pgtype.Text      `json:"email"`
	PrimaryPhone       pgtype.Text      `json:"primary_phone"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	VerificationStatus pgtype.Text      `json:"verification_status"`
}

func (q *Queries) GetPendingVerificationClinics(ctx context.Context, arg GetPendingVerificationClinicsParams) ([]GetPendingVerificationClinicsRow, error) {
	rows, err := q.db.Query(ctx, getPendingVerificationClinics, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingVerificationClinicsRow{}
	for rows.Next() {
		var i GetPendingVerificationClinicsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClinicName,
			&i.ClinicType,
			&i.RegistrationNumber,
			&i.City,
			&i.Province,
			&i.Email,
			&i.PrimaryPhone,
			&i.CreatedAt,
			&i.VerificationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVerifiedClinics = `-- name: GetVerifiedClinics :many
SELECT 
    id, clinic_name, clinic_type, city, province,
    physical_address, primary_phone, email,
    rating, review_count, created_at
FROM clinics
WHERE verification_status = 'verified'
ORDER BY rating DESC NULLS LAST
LIMIT $1 OFFSET $2
`

type GetVerifiedClinicsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetVerifiedClinicsRow struct {
	ID              pgtype.UUID      `json:"id"`
	ClinicName      string           `json:"clinic_name"`
	ClinicType      string           `json:"clinic_type"`
	City            pgtype.Text      `json:"city"`
	Province        pgtype.Text      `json:"province"`
	PhysicalAddress string           `json:"physical_address"`
	PrimaryPhone    pgtype.Text      `json:"primary_phone"`
	Email           pgtype.Text      `json:"email"`
	Rating          pgtype.Numeric   `json:"rating"`
	ReviewCount     pgtype.Int4      `json:"review_count"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetVerifiedClinics(ctx context.Context, arg GetVerifiedClinicsParams) ([]GetVerifiedClinicsRow, error) {
	rows, err := q.db.Query(ctx, getVerifiedClinics, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVerifiedClinicsRow{}
	for rows.Next() {
		var i GetVerifiedClinicsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClinicName,
			&i.ClinicType,
			&i.City,
			&i.Province,
			&i.PhysicalAddress,
			&i.PrimaryPhone,
			&i.Email,
			&i.Rating,
			&i.ReviewCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClinics = `-- name: ListClinics :many

SELECT 
    id, clinic_name, clinic_type, city, province,
    physical_address, primary_phone, email,
    is_verified, verification_status,
    rating, review_count, created_at
FROM clinics
WHERE 
    ($1::VARCHAR IS NULL OR clinic_type = $1)
    AND ($2::VARCHAR IS NULL OR province = $2)
    AND ($3::VARCHAR IS NULL OR city = $3)
    AND ($4::VARCHAR IS NULL OR verification_status = $4)
ORDER BY rating DESC NULLS LAST, created_at DESC
LIMIT $5 OFFSET $6
`

type ListClinicsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListClinicsRow struct {
	ID                 pgtype.UUID      `json:"id"`
	ClinicName         string           `json:"clinic_name"`
	ClinicType         string           `json:"clinic_type"`
	City               pgtype.Text      `json:"city"`
	Province           pgtype.Text      `json:"province"`
	PhysicalAddress    string           `json:"physical_address"`
	PrimaryPhone       pgtype.Text      `json:"primary_phone"`
	Email              pgtype.Text      `json:"email"`
	IsVerified         pgtype.Bool      `json:"is_verified"`
	VerificationStatus pgtype.Text      `json:"verification_status"`
	Rating             pgtype.Numeric   `json:"rating"`
	ReviewCount        pgtype.Int4      `json:"review_count"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

// ============================================
// FILTERING & LISTING
// ============================================
func (q *Queries) ListClinics(ctx context.Context, arg ListClinicsParams) ([]ListClinicsRow, error) {
	rows, err := q.db.Query(ctx, listClinics,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClinicsRow{}
	for rows.Next() {
		var i ListClinicsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClinicName,
			&i.ClinicType,
			&i.City,
			&i.Province,
			&i.PhysicalAddress,
			&i.PrimaryPhone,
			&i.Email,
			&i.IsVerified,
			&i.VerificationStatus,
			&i.Rating,
			&i.ReviewCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateClinic = `-- name: ReactivateClinic :exec
UPDATE clinics
SET 
    verification_status = 'pending',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ReactivateClinic(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, reactivateClinic, id)
	return err
}

const rejectClinicVerification = `-- name: RejectClinicVerification :exec
UPDATE clinics
SET 
    is_verified = FALSE,
    verification_status = 'rejected',
    verified_by = $2,
    verification_date = NOW(),
    verification_notes = $3,
    updated_at = NOW()
WHERE id = $1
`

type RejectClinicVerificationParams struct {
	ID                pgtype.UUID `json:"id"`
	VerifiedBy        pgtype.UUID `json:"verified_by"`
	VerificationNotes pgtype.Text `json:"verification_notes"`
}

func (q *Queries) RejectClinicVerification(ctx context.Context, arg RejectClinicVerificationParams) error {
	_, err := q.db.Exec(ctx, rejectClinicVerification, arg.ID, arg.VerifiedBy, arg.VerificationNotes)
	return err
}

const searchClinics = `-- name: SearchClinics :many

SELECT 
    id, clinic_name, clinic_type, city, province,
    physical_address, primary_phone, email,
    rating, review_count, verification_status,
    accepts_medical_aid, created_at
FROM clinics
WHERE 
    (clinic_name ILIKE '%' || $1 || '%'
    OR physical_address ILIKE '%' || $1 || '%'
    OR city ILIKE '%' || $1 || '%')
    AND ($2::VARCHAR IS NULL OR province = $2)
    AND ($3::VARCHAR IS NULL OR city = $3)
    AND ($4::VARCHAR IS NULL OR clinic_type = $4)
    AND verification_status = 'verified'
ORDER BY 
    CASE WHEN clinic_name ILIKE $1 || '%' THEN 1 ELSE 2 END,
    rating DESC NULLS LAST,
    review_count DESC
LIMIT $5 OFFSET $6
`

type SearchClinicsParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Column2 string      `json:"column_2"`
	Column3 string      `json:"column_3"`
	Column4 string      `json:"column_4"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type SearchClinicsRow struct {
	ID                 pgtype.UUID      `json:"id"`
	ClinicName         string           `json:"clinic_name"`
	ClinicType         string           `json:"clinic_type"`
	City               pgtype.Text      `json:"city"`
	Province           pgtype.Text      `json:"province"`
	PhysicalAddress    string           `json:"physical_address"`
	PrimaryPhone       pgtype.Text      `json:"primary_phone"`
	Email              pgtype.Text      `json:"email"`
	Rating             pgtype.Numeric   `json:"rating"`
	ReviewCount        pgtype.Int4      `json:"review_count"`
	VerificationStatus pgtype.Text      `json:"verification_status"`
	AcceptsMedicalAid  pgtype.Bool      `json:"accepts_medical_aid"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

// ============================================
// SEARCH & DISCOVERY
// ============================================
func (q *Queries) SearchClinics(ctx context.Context, arg SearchClinicsParams) ([]SearchClinicsRow, error) {
	rows, err := q.db.Query(ctx, searchClinics,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchClinicsRow{}
	for rows.Next() {
		var i SearchClinicsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClinicName,
			&i.ClinicType,
			&i.City,
			&i.Province,
			&i.PhysicalAddress,
			&i.PrimaryPhone,
			&i.Email,
			&i.Rating,
			&i.ReviewCount,
			&i.VerificationStatus,
			&i.AcceptsMedicalAid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClinic = `-- name: UpdateClinic :exec
UPDATE clinics
SET 
    clinic_name = COALESCE($2, clinic_name),
    clinic_type = COALESCE($3, clinic_type),
    primary_phone = COALESCE($4, primary_phone),
    secondary_phone = COALESCE($5, secondary_phone),
    emergency_phone = COALESCE($6, emergency_phone),
    email = COALESCE($7, email),
    website = COALESCE($8, website),
    description = COALESCE($9, description),
    operating_hours = COALESCE($10, operating_hours),
    updated_at = NOW()
WHERE id = $1
`

type UpdateClinicParams struct {
	ID             pgtype.UUID `json:"id"`
	ClinicName     string      `json:"clinic_name"`
	ClinicType     string      `json:"clinic_type"`
	PrimaryPhone   pgtype.Text `json:"primary_phone"`
	SecondaryPhone pgtype.Text `json:"secondary_phone"`
	EmergencyPhone pgtype.Text `json:"emergency_phone"`
	Email          pgtype.Text `json:"email"`
	Website        pgtype.Text `json:"website"`
	Description    pgtype.Text `json:"description"`
	OperatingHours []byte      `json:"operating_hours"`
}

func (q *Queries) UpdateClinic(ctx context.Context, arg UpdateClinicParams) error {
	_, err := q.db.Exec(ctx, updateClinic,
		arg.ID,
		arg.ClinicName,
		arg.ClinicType,
		arg.PrimaryPhone,
		arg.SecondaryPhone,
		arg.EmergencyPhone,
		arg.Email,
		arg.Website,
		arg.Description,
		arg.OperatingHours,
	)
	return err
}

const updateClinicOwner = `-- name: UpdateClinicOwner :exec
UPDATE clinics
SET 
    owner_user_id = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateClinicOwnerParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) UpdateClinicOwner(ctx context.Context, arg UpdateClinicOwnerParams) error {
	_, err := q.db.Exec(ctx, updateClinicOwner, arg.ID, arg.OwnerUserID)
	return err
}

const updateClinicVerificationStatus = `-- name: UpdateClinicVerificationStatus :exec
UPDATE clinics
SET 
    verification_status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateClinicVerificationStatusParams struct {
	ID                 pgtype.UUID `json:"id"`
	VerificationStatus pgtype.Text `json:"verification_status"`
}

func (q *Queries) UpdateClinicVerificationStatus(ctx context.Context, arg UpdateClinicVerificationStatusParams) error {
	_, err := q.db.Exec(ctx, updateClinicVerificationStatus, arg.ID, arg.VerificationStatus)
	return err
}

const verifyClinic = `-- name: VerifyClinic :exec

UPDATE clinics
SET 
    is_verified = TRUE,
    verification_status = 'verified',
    verified_by = $2,
    verification_date = NOW(),
    verification_notes = $3,
    updated_at = NOW()
WHERE id = $1
`

type VerifyClinicParams struct {
	ID                pgtype.UUID `json:"id"`
	VerifiedBy        pgtype.UUID `json:"verified_by"`
	VerificationNotes pgtype.Text `json:"verification_notes"`
}

// ============================================
// VERIFICATION & STATUS
// ============================================
func (q *Queries) VerifyClinic(ctx context.Context, arg VerifyClinicParams) error {
	_, err := q.db.Exec(ctx, verifyClinic, arg.ID, arg.VerifiedBy, arg.VerificationNotes)
	return err
}
