// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consultation_notes.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConsultationNote = `-- name: CreateConsultationNote :one

INSERT INTO consultation_notes (
    consultation_id, authored_by_staff_id
)
VALUES ($1, $2)
RETURNING id, consultation_id, authored_by_staff_id, subjective, objective, assessment, plan, diagnosis_codes, prescription_issued, prescription_details, referral_required, referral_type, referral_notes, follow_up_recommended, follow_up_timeframe, is_finalised, finalised_at, created_at, updated_at
`

type CreateConsultationNoteParams struct {
	ConsultationID    pgtype.UUID `json:"consultation_id"`
	AuthoredByStaffID pgtype.UUID `json:"authored_by_staff_id"`
}

// ============================================
// CORE WRITE OPERATIONS
// ============================================
// Provider opens the notes panel → create draft immediately.
func (q *Queries) CreateConsultationNote(ctx context.Context, arg CreateConsultationNoteParams) (ConsultationNote, error) {
	row := q.db.QueryRow(ctx, createConsultationNote, arg.ConsultationID, arg.AuthoredByStaffID)
	var i ConsultationNote
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.AuthoredByStaffID,
		&i.Subjective,
		&i.Objective,
		&i.Assessment,
		&i.Plan,
		&i.DiagnosisCodes,
		&i.PrescriptionIssued,
		&i.PrescriptionDetails,
		&i.ReferralRequired,
		&i.ReferralType,
		&i.ReferralNotes,
		&i.FollowUpRecommended,
		&i.FollowUpTimeframe,
		&i.IsFinalised,
		&i.FinalisedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finaliseConsultationNote = `-- name: FinaliseConsultationNote :one
UPDATE consultation_notes
SET
    is_finalised = true,
    finalised_at = NOW(),
    updated_at   = NOW()
WHERE id = $1
  AND is_finalised = false
RETURNING id, consultation_id, authored_by_staff_id, subjective, objective, assessment, plan, diagnosis_codes, prescription_issued, prescription_details, referral_required, referral_type, referral_notes, follow_up_recommended, follow_up_timeframe, is_finalised, finalised_at, created_at, updated_at
`

// Locks the note. Called when provider clicks "End Consultation".
func (q *Queries) FinaliseConsultationNote(ctx context.Context, id pgtype.UUID) (ConsultationNote, error) {
	row := q.db.QueryRow(ctx, finaliseConsultationNote, id)
	var i ConsultationNote
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.AuthoredByStaffID,
		&i.Subjective,
		&i.Objective,
		&i.Assessment,
		&i.Plan,
		&i.DiagnosisCodes,
		&i.PrescriptionIssued,
		&i.PrescriptionDetails,
		&i.ReferralRequired,
		&i.ReferralType,
		&i.ReferralNotes,
		&i.FollowUpRecommended,
		&i.FollowUpTimeframe,
		&i.IsFinalised,
		&i.FinalisedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finaliseNoteByConsultation = `-- name: FinaliseNoteByConsultation :one
UPDATE consultation_notes
SET
    is_finalised = true,
    finalised_at = NOW(),
    updated_at   = NOW()
WHERE consultation_id = $1
  AND is_finalised = false
RETURNING id, consultation_id, authored_by_staff_id, subjective, objective, assessment, plan, diagnosis_codes, prescription_issued, prescription_details, referral_required, referral_type, referral_notes, follow_up_recommended, follow_up_timeframe, is_finalised, finalised_at, created_at, updated_at
`

// Alternative: lock by consultation_id (more natural from the service layer).
func (q *Queries) FinaliseNoteByConsultation(ctx context.Context, consultationID pgtype.UUID) (ConsultationNote, error) {
	row := q.db.QueryRow(ctx, finaliseNoteByConsultation, consultationID)
	var i ConsultationNote
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.AuthoredByStaffID,
		&i.Subjective,
		&i.Objective,
		&i.Assessment,
		&i.Plan,
		&i.DiagnosisCodes,
		&i.PrescriptionIssued,
		&i.PrescriptionDetails,
		&i.ReferralRequired,
		&i.ReferralType,
		&i.ReferralNotes,
		&i.FollowUpRecommended,
		&i.FollowUpTimeframe,
		&i.IsFinalised,
		&i.FinalisedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNoteByConsultationID = `-- name: GetNoteByConsultationID :one
SELECT id, consultation_id, authored_by_staff_id, subjective, objective, assessment, plan, diagnosis_codes, prescription_issued, prescription_details, referral_required, referral_type, referral_notes, follow_up_recommended, follow_up_timeframe, is_finalised, finalised_at, created_at, updated_at FROM consultation_notes
WHERE consultation_id = $1
`

// Primary read path — get the note for a given consultation.
func (q *Queries) GetNoteByConsultationID(ctx context.Context, consultationID pgtype.UUID) (ConsultationNote, error) {
	row := q.db.QueryRow(ctx, getNoteByConsultationID, consultationID)
	var i ConsultationNote
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.AuthoredByStaffID,
		&i.Subjective,
		&i.Objective,
		&i.Assessment,
		&i.Plan,
		&i.DiagnosisCodes,
		&i.PrescriptionIssued,
		&i.PrescriptionDetails,
		&i.ReferralRequired,
		&i.ReferralType,
		&i.ReferralNotes,
		&i.FollowUpRecommended,
		&i.FollowUpTimeframe,
		&i.IsFinalised,
		&i.FinalisedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNoteByID = `-- name: GetNoteByID :one

SELECT id, consultation_id, authored_by_staff_id, subjective, objective, assessment, plan, diagnosis_codes, prescription_issued, prescription_details, referral_required, referral_type, referral_notes, follow_up_recommended, follow_up_timeframe, is_finalised, finalised_at, created_at, updated_at FROM consultation_notes
WHERE id = $1
`

// ============================================
// READ OPERATIONS
// ============================================
func (q *Queries) GetNoteByID(ctx context.Context, id pgtype.UUID) (ConsultationNote, error) {
	row := q.db.QueryRow(ctx, getNoteByID, id)
	var i ConsultationNote
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.AuthoredByStaffID,
		&i.Subjective,
		&i.Objective,
		&i.Assessment,
		&i.Plan,
		&i.DiagnosisCodes,
		&i.PrescriptionIssued,
		&i.PrescriptionDetails,
		&i.ReferralRequired,
		&i.ReferralType,
		&i.ReferralNotes,
		&i.FollowUpRecommended,
		&i.FollowUpTimeframe,
		&i.IsFinalised,
		&i.FinalisedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNoteWithProviderInfo = `-- name: GetNoteWithProviderInfo :one
SELECT
    cn.id, cn.consultation_id, cn.authored_by_staff_id, cn.subjective, cn.objective, cn.assessment, cn.plan, cn.diagnosis_codes, cn.prescription_issued, cn.prescription_details, cn.referral_required, cn.referral_type, cn.referral_notes, cn.follow_up_recommended, cn.follow_up_timeframe, cn.is_finalised, cn.finalised_at, cn.created_at, cn.updated_at,
    cs.first_name       AS provider_first_name,
    cs.last_name        AS provider_last_name,
    cs.professional_title,
    cs.specialization,
    cs.hpcs_number
FROM consultation_notes cn
JOIN clinic_staff cs ON cs.id = cn.authored_by_staff_id
WHERE cn.consultation_id = $1
`

type GetNoteWithProviderInfoRow struct {
	ID                  pgtype.UUID      `json:"id"`
	ConsultationID      pgtype.UUID      `json:"consultation_id"`
	AuthoredByStaffID   pgtype.UUID      `json:"authored_by_staff_id"`
	Subjective          pgtype.Text      `json:"subjective"`
	Objective           pgtype.Text      `json:"objective"`
	Assessment          pgtype.Text      `json:"assessment"`
	Plan                pgtype.Text      `json:"plan"`
	DiagnosisCodes      []string         `json:"diagnosis_codes"`
	PrescriptionIssued  bool             `json:"prescription_issued"`
	PrescriptionDetails []byte           `json:"prescription_details"`
	ReferralRequired    bool             `json:"referral_required"`
	ReferralType        pgtype.Text      `json:"referral_type"`
	ReferralNotes       pgtype.Text      `json:"referral_notes"`
	FollowUpRecommended bool             `json:"follow_up_recommended"`
	FollowUpTimeframe   pgtype.Text      `json:"follow_up_timeframe"`
	IsFinalised         bool             `json:"is_finalised"`
	FinalisedAt         pgtype.Timestamp `json:"finalised_at"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	ProviderFirstName   string           `json:"provider_first_name"`
	ProviderLastName    string           `json:"provider_last_name"`
	ProfessionalTitle   pgtype.Text      `json:"professional_title"`
	Specialization      pgtype.Text      `json:"specialization"`
	HpcsNumber          pgtype.Text      `json:"hpcs_number"`
}

// Hydrated view for patient record / admin audit.
func (q *Queries) GetNoteWithProviderInfo(ctx context.Context, consultationID pgtype.UUID) (GetNoteWithProviderInfoRow, error) {
	row := q.db.QueryRow(ctx, getNoteWithProviderInfo, consultationID)
	var i GetNoteWithProviderInfoRow
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.AuthoredByStaffID,
		&i.Subjective,
		&i.Objective,
		&i.Assessment,
		&i.Plan,
		&i.DiagnosisCodes,
		&i.PrescriptionIssued,
		&i.PrescriptionDetails,
		&i.ReferralRequired,
		&i.ReferralType,
		&i.ReferralNotes,
		&i.FollowUpRecommended,
		&i.FollowUpTimeframe,
		&i.IsFinalised,
		&i.FinalisedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderFirstName,
		&i.ProviderLastName,
		&i.ProfessionalTitle,
		&i.Specialization,
		&i.HpcsNumber,
	)
	return i, err
}

const getPatientNoteHistory = `-- name: GetPatientNoteHistory :many

SELECT
    cn.id,
    cn.consultation_id,
    cn.subjective,
    cn.assessment,
    cn.plan,
    cn.diagnosis_codes,
    cn.prescription_issued,
    cn.prescription_details,
    cn.referral_required,
    cn.referral_type,
    cn.follow_up_recommended,
    cn.follow_up_timeframe,
    cn.finalised_at,
    cs.first_name       AS provider_first_name,
    cs.last_name        AS provider_last_name,
    cs.professional_title
FROM consultation_notes cn
JOIN consultations    c  ON c.id  = cn.consultation_id
JOIN clinic_staff    cs  ON cs.id = cn.authored_by_staff_id
WHERE
    c.patient_id    = $1
    AND cn.is_finalised = true
ORDER BY cn.finalised_at DESC
`

type GetPatientNoteHistoryRow struct {
	ID                  pgtype.UUID      `json:"id"`
	ConsultationID      pgtype.UUID      `json:"consultation_id"`
	Subjective          pgtype.Text      `json:"subjective"`
	Assessment          pgtype.Text      `json:"assessment"`
	Plan                pgtype.Text      `json:"plan"`
	DiagnosisCodes      []string         `json:"diagnosis_codes"`
	PrescriptionIssued  bool             `json:"prescription_issued"`
	PrescriptionDetails []byte           `json:"prescription_details"`
	ReferralRequired    bool             `json:"referral_required"`
	ReferralType        pgtype.Text      `json:"referral_type"`
	FollowUpRecommended bool             `json:"follow_up_recommended"`
	FollowUpTimeframe   pgtype.Text      `json:"follow_up_timeframe"`
	FinalisedAt         pgtype.Timestamp `json:"finalised_at"`
	ProviderFirstName   string           `json:"provider_first_name"`
	ProviderLastName    string           `json:"provider_last_name"`
	ProfessionalTitle   pgtype.Text      `json:"professional_title"`
}

// ============================================
// PATIENT RECORD ACCESS
// ============================================
// All finalised notes for a patient (their full telemedicine record).
func (q *Queries) GetPatientNoteHistory(ctx context.Context, patientID pgtype.UUID) ([]GetPatientNoteHistoryRow, error) {
	rows, err := q.db.Query(ctx, getPatientNoteHistory, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPatientNoteHistoryRow{}
	for rows.Next() {
		var i GetPatientNoteHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ConsultationID,
			&i.Subjective,
			&i.Assessment,
			&i.Plan,
			&i.DiagnosisCodes,
			&i.PrescriptionIssued,
			&i.PrescriptionDetails,
			&i.ReferralRequired,
			&i.ReferralType,
			&i.FollowUpRecommended,
			&i.FollowUpTimeframe,
			&i.FinalisedAt,
			&i.ProviderFirstName,
			&i.ProviderLastName,
			&i.ProfessionalTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProviderNoteHistory = `-- name: GetProviderNoteHistory :many

SELECT
    cn.id,
    cn.consultation_id,
    cn.assessment,
    cn.plan,
    cn.diagnosis_codes,
    cn.prescription_issued,
    cn.referral_required,
    cn.follow_up_recommended,
    cn.finalised_at,
    pp.first_name AS patient_first_name,
    pp.last_name  AS patient_last_name
FROM consultation_notes cn
JOIN consultations    c  ON c.id  = cn.consultation_id
JOIN patient_profiles pp ON pp.id = c.patient_id
WHERE
    cn.authored_by_staff_id = $1
    AND cn.is_finalised     = true
ORDER BY cn.finalised_at DESC
LIMIT  $2
OFFSET $3
`

type GetProviderNoteHistoryParams struct {
	AuthoredByStaffID pgtype.UUID `json:"authored_by_staff_id"`
	Limit             int32       `json:"limit"`
	Offset            int32       `json:"offset"`
}

type GetProviderNoteHistoryRow struct {
	ID                  pgtype.UUID      `json:"id"`
	ConsultationID      pgtype.UUID      `json:"consultation_id"`
	Assessment          pgtype.Text      `json:"assessment"`
	Plan                pgtype.Text      `json:"plan"`
	DiagnosisCodes      []string         `json:"diagnosis_codes"`
	PrescriptionIssued  bool             `json:"prescription_issued"`
	ReferralRequired    bool             `json:"referral_required"`
	FollowUpRecommended bool             `json:"follow_up_recommended"`
	FinalisedAt         pgtype.Timestamp `json:"finalised_at"`
	PatientFirstName    string           `json:"patient_first_name"`
	PatientLastName     string           `json:"patient_last_name"`
}

// ============================================
// PROVIDER HISTORY
// ============================================
// All finalised notes written by a provider, newest first.
func (q *Queries) GetProviderNoteHistory(ctx context.Context, arg GetProviderNoteHistoryParams) ([]GetProviderNoteHistoryRow, error) {
	rows, err := q.db.Query(ctx, getProviderNoteHistory, arg.AuthoredByStaffID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProviderNoteHistoryRow{}
	for rows.Next() {
		var i GetProviderNoteHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ConsultationID,
			&i.Assessment,
			&i.Plan,
			&i.DiagnosisCodes,
			&i.PrescriptionIssued,
			&i.ReferralRequired,
			&i.FollowUpRecommended,
			&i.FinalisedAt,
			&i.PatientFirstName,
			&i.PatientLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isNoteFinalisedForConsultation = `-- name: IsNoteFinalisedForConsultation :one
SELECT is_finalised FROM consultation_notes
WHERE consultation_id = $1
`

func (q *Queries) IsNoteFinalisedForConsultation(ctx context.Context, consultationID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isNoteFinalisedForConsultation, consultationID)
	var is_finalised bool
	err := row.Scan(&is_finalised)
	return is_finalised, err
}

const noteExistsForConsultation = `-- name: NoteExistsForConsultation :one

SELECT EXISTS(
    SELECT 1 FROM consultation_notes
    WHERE consultation_id = $1
) AS exists
`

// ============================================
// QUICK CHECKS
// ============================================
func (q *Queries) NoteExistsForConsultation(ctx context.Context, consultationID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, noteExistsForConsultation, consultationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateConsultationNote = `-- name: UpdateConsultationNote :one
UPDATE consultation_notes
SET
    subjective           = COALESCE($2, subjective),
    objective            = COALESCE($3, objective),
    assessment           = COALESCE($4, assessment),
    plan                 = COALESCE($5, plan),
    diagnosis_codes      = COALESCE($6, diagnosis_codes),
    prescription_issued  = COALESCE($7, prescription_issued),
    prescription_details = COALESCE($8::jsonb, prescription_details),
    referral_required    = COALESCE($9, referral_required),
    referral_type        = COALESCE($10, referral_type),
    referral_notes       = COALESCE($11, referral_notes),
    follow_up_recommended = COALESCE($12, follow_up_recommended),
    follow_up_timeframe  = COALESCE($13, follow_up_timeframe),
    updated_at           = NOW()
WHERE id = $1
  AND is_finalised = false
RETURNING id, consultation_id, authored_by_staff_id, subjective, objective, assessment, plan, diagnosis_codes, prescription_issued, prescription_details, referral_required, referral_type, referral_notes, follow_up_recommended, follow_up_timeframe, is_finalised, finalised_at, created_at, updated_at
`

type UpdateConsultationNoteParams struct {
	ID                  pgtype.UUID     `json:"id"`
	Subjective          pgtype.Text     `json:"subjective"`
	Objective           pgtype.Text     `json:"objective"`
	Assessment          pgtype.Text     `json:"assessment"`
	Plan                pgtype.Text     `json:"plan"`
	DiagnosisCodes      []string        `json:"diagnosis_codes"`
	PrescriptionIssued  bool            `json:"prescription_issued"`
	Column8             json.RawMessage `json:"column_8"`
	ReferralRequired    bool            `json:"referral_required"`
	ReferralType        pgtype.Text     `json:"referral_type"`
	ReferralNotes       pgtype.Text     `json:"referral_notes"`
	FollowUpRecommended bool            `json:"follow_up_recommended"`
	FollowUpTimeframe   pgtype.Text     `json:"follow_up_timeframe"`
}

// Auto-save as provider types. Blocked once is_finalised = true (enforced at service layer).
func (q *Queries) UpdateConsultationNote(ctx context.Context, arg UpdateConsultationNoteParams) (ConsultationNote, error) {
	row := q.db.QueryRow(ctx, updateConsultationNote,
		arg.ID,
		arg.Subjective,
		arg.Objective,
		arg.Assessment,
		arg.Plan,
		arg.DiagnosisCodes,
		arg.PrescriptionIssued,
		arg.Column8,
		arg.ReferralRequired,
		arg.ReferralType,
		arg.ReferralNotes,
		arg.FollowUpRecommended,
		arg.FollowUpTimeframe,
	)
	var i ConsultationNote
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.AuthoredByStaffID,
		&i.Subjective,
		&i.Objective,
		&i.Assessment,
		&i.Plan,
		&i.DiagnosisCodes,
		&i.PrescriptionIssued,
		&i.PrescriptionDetails,
		&i.ReferralRequired,
		&i.ReferralType,
		&i.ReferralNotes,
		&i.FollowUpRecommended,
		&i.FollowUpTimeframe,
		&i.IsFinalised,
		&i.FinalisedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
