// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: data_access_logs.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDataAccessLogs = `-- name: GetDataAccessLogs :many
SELECT id, accessed_by_user_id, accessed_by_role, accessed_resource_type,
    accessed_resource_id, access_type, access_reason, 
    is_emergency_access, accessed_at
FROM data_access_logs
WHERE accessed_user_id = $1
ORDER BY accessed_at DESC
LIMIT $2 OFFSET $3
`

type GetDataAccessLogsParams struct {
	AccessedUserID pgtype.UUID `json:"accessed_user_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

type GetDataAccessLogsRow struct {
	ID                   pgtype.UUID      `json:"id"`
	AccessedByUserID     pgtype.UUID      `json:"accessed_by_user_id"`
	AccessedByRole       pgtype.Text      `json:"accessed_by_role"`
	AccessedResourceType pgtype.Text      `json:"accessed_resource_type"`
	AccessedResourceID   pgtype.UUID      `json:"accessed_resource_id"`
	AccessType           pgtype.Text      `json:"access_type"`
	AccessReason         pgtype.Text      `json:"access_reason"`
	IsEmergencyAccess    pgtype.Bool      `json:"is_emergency_access"`
	AccessedAt           pgtype.Timestamp `json:"accessed_at"`
}

func (q *Queries) GetDataAccessLogs(ctx context.Context, arg GetDataAccessLogsParams) ([]GetDataAccessLogsRow, error) {
	rows, err := q.db.Query(ctx, getDataAccessLogs, arg.AccessedUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDataAccessLogsRow{}
	for rows.Next() {
		var i GetDataAccessLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccessedByUserID,
			&i.AccessedByRole,
			&i.AccessedResourceType,
			&i.AccessedResourceID,
			&i.AccessType,
			&i.AccessReason,
			&i.IsEmergencyAccess,
			&i.AccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logDataAccess = `-- name: LogDataAccess :exec
INSERT INTO data_access_logs (
    accessed_by_user_id, accessed_by_role, accessed_user_id,
    accessed_resource_type, accessed_resource_id, access_type,
    access_reason, is_emergency_access, ip_address, user_agent
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type LogDataAccessParams struct {
	AccessedByUserID     pgtype.UUID `json:"accessed_by_user_id"`
	AccessedByRole       pgtype.Text `json:"accessed_by_role"`
	AccessedUserID       pgtype.UUID `json:"accessed_user_id"`
	AccessedResourceType pgtype.Text `json:"accessed_resource_type"`
	AccessedResourceID   pgtype.UUID `json:"accessed_resource_id"`
	AccessType           pgtype.Text `json:"access_type"`
	AccessReason         pgtype.Text `json:"access_reason"`
	IsEmergencyAccess    pgtype.Bool `json:"is_emergency_access"`
	IpAddress            *netip.Addr `json:"ip_address"`
	UserAgent            pgtype.Text `json:"user_agent"`
}

func (q *Queries) LogDataAccess(ctx context.Context, arg LogDataAccessParams) error {
	_, err := q.db.Exec(ctx, logDataAccess,
		arg.AccessedByUserID,
		arg.AccessedByRole,
		arg.AccessedUserID,
		arg.AccessedResourceType,
		arg.AccessedResourceID,
		arg.AccessType,
		arg.AccessReason,
		arg.IsEmergencyAccess,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}
