// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dependent_health_records.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addDependentHealthRecord = `-- name: AddDependentHealthRecord :one


INSERT INTO dependent_health_records (
    dependent_id, record_type, record_date, weight_kg, height_cm,
    head_circumference_cm, temperature_c, notes, provider_name,
    clinic_name, next_appointment_date, documents
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, dependent_id, record_type, record_date, weight_kg, height_cm, head_circumference_cm, temperature_c, notes, provider_name, clinic_name, next_appointment_date, documents, created_at
`

type AddDependentHealthRecordParams struct {
	DependentID         pgtype.UUID    `json:"dependent_id"`
	RecordType          pgtype.Text    `json:"record_type"`
	RecordDate          pgtype.Date    `json:"record_date"`
	WeightKg            pgtype.Numeric `json:"weight_kg"`
	HeightCm            pgtype.Numeric `json:"height_cm"`
	HeadCircumferenceCm pgtype.Numeric `json:"head_circumference_cm"`
	TemperatureC        pgtype.Numeric `json:"temperature_c"`
	Notes               pgtype.Text    `json:"notes"`
	ProviderName        pgtype.Text    `json:"provider_name"`
	ClinicName          pgtype.Text    `json:"clinic_name"`
	NextAppointmentDate pgtype.Date    `json:"next_appointment_date"`
	Documents           []byte         `json:"documents"`
}

// ============================================
// DEPENDENT HEALTH RECORDS REPOSITORY QUERIES
// Maps to: Part of PatientRepository interface
// Domain: Dependent Health Records & Growth Tracking
// ============================================
// ============================================
// CORE CRUD OPERATIONS
// ============================================
func (q *Queries) AddDependentHealthRecord(ctx context.Context, arg AddDependentHealthRecordParams) (DependentHealthRecord, error) {
	row := q.db.QueryRow(ctx, addDependentHealthRecord,
		arg.DependentID,
		arg.RecordType,
		arg.RecordDate,
		arg.WeightKg,
		arg.HeightCm,
		arg.HeadCircumferenceCm,
		arg.TemperatureC,
		arg.Notes,
		arg.ProviderName,
		arg.ClinicName,
		arg.NextAppointmentDate,
		arg.Documents,
	)
	var i DependentHealthRecord
	err := row.Scan(
		&i.ID,
		&i.DependentID,
		&i.RecordType,
		&i.RecordDate,
		&i.WeightKg,
		&i.HeightCm,
		&i.HeadCircumferenceCm,
		&i.TemperatureC,
		&i.Notes,
		&i.ProviderName,
		&i.ClinicName,
		&i.NextAppointmentDate,
		&i.Documents,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDependentHealthRecord = `-- name: DeleteDependentHealthRecord :exec
DELETE FROM dependent_health_records WHERE id = $1
`

func (q *Queries) DeleteDependentHealthRecord(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDependentHealthRecord, id)
	return err
}

const getDependentHealthRecord = `-- name: GetDependentHealthRecord :one
SELECT id, dependent_id, record_type, record_date, weight_kg, height_cm, head_circumference_cm, temperature_c, notes, provider_name, clinic_name, next_appointment_date, documents, created_at FROM dependent_health_records
WHERE id = $1
`

func (q *Queries) GetDependentHealthRecord(ctx context.Context, id pgtype.UUID) (DependentHealthRecord, error) {
	row := q.db.QueryRow(ctx, getDependentHealthRecord, id)
	var i DependentHealthRecord
	err := row.Scan(
		&i.ID,
		&i.DependentID,
		&i.RecordType,
		&i.RecordDate,
		&i.WeightKg,
		&i.HeightCm,
		&i.HeadCircumferenceCm,
		&i.TemperatureC,
		&i.Notes,
		&i.ProviderName,
		&i.ClinicName,
		&i.NextAppointmentDate,
		&i.Documents,
		&i.CreatedAt,
	)
	return i, err
}

const getDependentHealthRecords = `-- name: GetDependentHealthRecords :many

SELECT 
    id, dependent_id, record_type, record_date, weight_kg,
    height_cm, head_circumference_cm, temperature_c, notes,
    provider_name, clinic_name, next_appointment_date, created_at
FROM dependent_health_records
WHERE dependent_id = $1
ORDER BY record_date DESC
`

type GetDependentHealthRecordsRow struct {
	ID                  pgtype.UUID      `json:"id"`
	DependentID         pgtype.UUID      `json:"dependent_id"`
	RecordType          pgtype.Text      `json:"record_type"`
	RecordDate          pgtype.Date      `json:"record_date"`
	WeightKg            pgtype.Numeric   `json:"weight_kg"`
	HeightCm            pgtype.Numeric   `json:"height_cm"`
	HeadCircumferenceCm pgtype.Numeric   `json:"head_circumference_cm"`
	TemperatureC        pgtype.Numeric   `json:"temperature_c"`
	Notes               pgtype.Text      `json:"notes"`
	ProviderName        pgtype.Text      `json:"provider_name"`
	ClinicName          pgtype.Text      `json:"clinic_name"`
	NextAppointmentDate pgtype.Date      `json:"next_appointment_date"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
}

// ============================================
// QUERYING BY DEPENDENT
// ============================================
func (q *Queries) GetDependentHealthRecords(ctx context.Context, dependentID pgtype.UUID) ([]GetDependentHealthRecordsRow, error) {
	rows, err := q.db.Query(ctx, getDependentHealthRecords, dependentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDependentHealthRecordsRow{}
	for rows.Next() {
		var i GetDependentHealthRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.DependentID,
			&i.RecordType,
			&i.RecordDate,
			&i.WeightKg,
			&i.HeightCm,
			&i.HeadCircumferenceCm,
			&i.TemperatureC,
			&i.Notes,
			&i.ProviderName,
			&i.ClinicName,
			&i.NextAppointmentDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGrowthRecords = `-- name: GetGrowthRecords :many
SELECT 
    id, record_date, weight_kg, height_cm, head_circumference_cm, notes
FROM dependent_health_records
WHERE 
    dependent_id = $1
    AND record_type = 'growth_check'
ORDER BY record_date DESC
`

type GetGrowthRecordsRow struct {
	ID                  pgtype.UUID    `json:"id"`
	RecordDate          pgtype.Date    `json:"record_date"`
	WeightKg            pgtype.Numeric `json:"weight_kg"`
	HeightCm            pgtype.Numeric `json:"height_cm"`
	HeadCircumferenceCm pgtype.Numeric `json:"head_circumference_cm"`
	Notes               pgtype.Text    `json:"notes"`
}

func (q *Queries) GetGrowthRecords(ctx context.Context, dependentID pgtype.UUID) ([]GetGrowthRecordsRow, error) {
	rows, err := q.db.Query(ctx, getGrowthRecords, dependentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGrowthRecordsRow{}
	for rows.Next() {
		var i GetGrowthRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecordDate,
			&i.WeightKg,
			&i.HeightCm,
			&i.HeadCircumferenceCm,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDependentHealthRecord = `-- name: UpdateDependentHealthRecord :exec
UPDATE dependent_health_records
SET 
    record_type = COALESCE($2, record_type),
    weight_kg = COALESCE($3, weight_kg),
    height_cm = COALESCE($4, height_cm),
    head_circumference_cm = COALESCE($5, head_circumference_cm),
    temperature_c = COALESCE($6, temperature_c),
    notes = COALESCE($7, notes),
    next_appointment_date = COALESCE($8, next_appointment_date)
WHERE id = $1
`

type UpdateDependentHealthRecordParams struct {
	ID                  pgtype.UUID    `json:"id"`
	RecordType          pgtype.Text    `json:"record_type"`
	WeightKg            pgtype.Numeric `json:"weight_kg"`
	HeightCm            pgtype.Numeric `json:"height_cm"`
	HeadCircumferenceCm pgtype.Numeric `json:"head_circumference_cm"`
	TemperatureC        pgtype.Numeric `json:"temperature_c"`
	Notes               pgtype.Text    `json:"notes"`
	NextAppointmentDate pgtype.Date    `json:"next_appointment_date"`
}

func (q *Queries) UpdateDependentHealthRecord(ctx context.Context, arg UpdateDependentHealthRecordParams) error {
	_, err := q.db.Exec(ctx, updateDependentHealthRecord,
		arg.ID,
		arg.RecordType,
		arg.WeightKg,
		arg.HeightCm,
		arg.HeadCircumferenceCm,
		arg.TemperatureC,
		arg.Notes,
		arg.NextAppointmentDate,
	)
	return err
}
