// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: forum.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countForumComments = `-- name: CountForumComments :one
SELECT COUNT(*) FROM forum_comments WHERE post_id = $1
`

func (q *Queries) CountForumComments(ctx context.Context, postID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countForumComments, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countForumPosts = `-- name: CountForumPosts :one
SELECT COUNT(*) FROM forum_posts
`

func (q *Queries) CountForumPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countForumPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createForumComment = `-- name: CreateForumComment :one
INSERT INTO forum_comments (post_id, author_id, content)
VALUES ($1, $2, $3)
RETURNING id, post_id, author_id, content, created_at, updated_at
`

type CreateForumCommentParams struct {
	PostID   pgtype.UUID `json:"post_id"`
	AuthorID pgtype.UUID `json:"author_id"`
	Content  string      `json:"content"`
}

func (q *Queries) CreateForumComment(ctx context.Context, arg CreateForumCommentParams) (ForumComment, error) {
	row := q.db.QueryRow(ctx, createForumComment, arg.PostID, arg.AuthorID, arg.Content)
	var i ForumComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createForumPost = `-- name: CreateForumPost :one
INSERT INTO forum_posts (author_id, title, content, category)
VALUES ($1, $2, $3, $4)
RETURNING id, author_id, title, content, category, is_pinned, view_count, created_at, updated_at
`

type CreateForumPostParams struct {
	AuthorID pgtype.UUID `json:"author_id"`
	Title    string      `json:"title"`
	Content  string      `json:"content"`
	Category string      `json:"category"`
}

func (q *Queries) CreateForumPost(ctx context.Context, arg CreateForumPostParams) (ForumPost, error) {
	row := q.db.QueryRow(ctx, createForumPost,
		arg.AuthorID,
		arg.Title,
		arg.Content,
		arg.Category,
	)
	var i ForumPost
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.IsPinned,
		&i.ViewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteForumComment = `-- name: DeleteForumComment :exec
DELETE FROM forum_comments WHERE id = $1 AND author_id = $2
`

type DeleteForumCommentParams struct {
	ID       pgtype.UUID `json:"id"`
	AuthorID pgtype.UUID `json:"author_id"`
}

func (q *Queries) DeleteForumComment(ctx context.Context, arg DeleteForumCommentParams) error {
	_, err := q.db.Exec(ctx, deleteForumComment, arg.ID, arg.AuthorID)
	return err
}

const deleteForumPost = `-- name: DeleteForumPost :exec
DELETE FROM forum_posts WHERE id = $1 AND author_id = $2
`

type DeleteForumPostParams struct {
	ID       pgtype.UUID `json:"id"`
	AuthorID pgtype.UUID `json:"author_id"`
}

func (q *Queries) DeleteForumPost(ctx context.Context, arg DeleteForumPostParams) error {
	_, err := q.db.Exec(ctx, deleteForumPost, arg.ID, arg.AuthorID)
	return err
}

const getForumPostByID = `-- name: GetForumPostByID :one
SELECT fp.id, fp.author_id, fp.title, fp.content, fp.category, fp.is_pinned, fp.view_count, fp.created_at, fp.updated_at, u.email as author_email, u.role as author_role
FROM forum_posts fp
JOIN users u ON fp.author_id = u.id
WHERE fp.id = $1
`

type GetForumPostByIDRow struct {
	ID          pgtype.UUID      `json:"id"`
	AuthorID    pgtype.UUID      `json:"author_id"`
	Title       string           `json:"title"`
	Content     string           `json:"content"`
	Category    string           `json:"category"`
	IsPinned    pgtype.Bool      `json:"is_pinned"`
	ViewCount   pgtype.Int4      `json:"view_count"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	AuthorEmail string           `json:"author_email"`
	AuthorRole  string           `json:"author_role"`
}

func (q *Queries) GetForumPostByID(ctx context.Context, id pgtype.UUID) (GetForumPostByIDRow, error) {
	row := q.db.QueryRow(ctx, getForumPostByID, id)
	var i GetForumPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.IsPinned,
		&i.ViewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorEmail,
		&i.AuthorRole,
	)
	return i, err
}

const incrementForumPostView = `-- name: IncrementForumPostView :exec
UPDATE forum_posts SET view_count = view_count + 1 WHERE id = $1
`

func (q *Queries) IncrementForumPostView(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementForumPostView, id)
	return err
}

const listForumComments = `-- name: ListForumComments :many
SELECT fc.id, fc.post_id, fc.author_id, fc.content, fc.created_at, fc.updated_at, u.email as author_email, u.role as author_role
FROM forum_comments fc
JOIN users u ON fc.author_id = u.id
WHERE fc.post_id = $1
ORDER BY fc.created_at ASC
LIMIT $2 OFFSET $3
`

type ListForumCommentsParams struct {
	PostID pgtype.UUID `json:"post_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListForumCommentsRow struct {
	ID          pgtype.UUID      `json:"id"`
	PostID      pgtype.UUID      `json:"post_id"`
	AuthorID    pgtype.UUID      `json:"author_id"`
	Content     string           `json:"content"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	AuthorEmail string           `json:"author_email"`
	AuthorRole  string           `json:"author_role"`
}

func (q *Queries) ListForumComments(ctx context.Context, arg ListForumCommentsParams) ([]ListForumCommentsRow, error) {
	rows, err := q.db.Query(ctx, listForumComments, arg.PostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListForumCommentsRow{}
	for rows.Next() {
		var i ListForumCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorEmail,
			&i.AuthorRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForumPosts = `-- name: ListForumPosts :many
SELECT fp.id, fp.author_id, fp.title, fp.content, fp.category, fp.is_pinned, fp.view_count, fp.created_at, fp.updated_at, u.email as author_email, u.role as author_role,
    (SELECT COUNT(*) FROM forum_comments fc WHERE fc.post_id = fp.id) as comment_count
FROM forum_posts fp
JOIN users u ON fp.author_id = u.id
ORDER BY fp.is_pinned DESC, fp.created_at DESC
LIMIT $1 OFFSET $2
`

type ListForumPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListForumPostsRow struct {
	ID           pgtype.UUID      `json:"id"`
	AuthorID     pgtype.UUID      `json:"author_id"`
	Title        string           `json:"title"`
	Content      string           `json:"content"`
	Category     string           `json:"category"`
	IsPinned     pgtype.Bool      `json:"is_pinned"`
	ViewCount    pgtype.Int4      `json:"view_count"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	AuthorEmail  string           `json:"author_email"`
	AuthorRole   string           `json:"author_role"`
	CommentCount int64            `json:"comment_count"`
}

func (q *Queries) ListForumPosts(ctx context.Context, arg ListForumPostsParams) ([]ListForumPostsRow, error) {
	rows, err := q.db.Query(ctx, listForumPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListForumPostsRow{}
	for rows.Next() {
		var i ListForumPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Content,
			&i.Category,
			&i.IsPinned,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorEmail,
			&i.AuthorRole,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateForumPost = `-- name: UpdateForumPost :one
UPDATE forum_posts
SET title = $2, content = $3, category = $4, updated_at = NOW()
WHERE id = $1 AND author_id = $5
RETURNING id, author_id, title, content, category, is_pinned, view_count, created_at, updated_at
`

type UpdateForumPostParams struct {
	ID       pgtype.UUID `json:"id"`
	Title    string      `json:"title"`
	Content  string      `json:"content"`
	Category string      `json:"category"`
	AuthorID pgtype.UUID `json:"author_id"`
}

func (q *Queries) UpdateForumPost(ctx context.Context, arg UpdateForumPostParams) (ForumPost, error) {
	row := q.db.QueryRow(ctx, updateForumPost,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Category,
		arg.AuthorID,
	)
	var i ForumPost
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.IsPinned,
		&i.ViewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
