// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patient_medications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPatientMedication = `-- name: AddPatientMedication :one


INSERT INTO patient_medications (
    patient_id, medication_name, generic_name, dosage, frequency,
    route, prescribing_doctor, pharmacy_name, prescription_date,
    start_date, end_date, reason_for_medication, status,
    side_effects, instructions
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, patient_id, medication_name, generic_name, dosage, frequency, route, prescribing_doctor, pharmacy_name, prescription_date, start_date, end_date, reason_for_medication, status, side_effects, instructions, created_at, updated_at
`

type AddPatientMedicationParams struct {
	PatientID           pgtype.UUID `json:"patient_id"`
	MedicationName      string      `json:"medication_name"`
	GenericName         pgtype.Text `json:"generic_name"`
	Dosage              pgtype.Text `json:"dosage"`
	Frequency           pgtype.Text `json:"frequency"`
	Route               pgtype.Text `json:"route"`
	PrescribingDoctor   pgtype.Text `json:"prescribing_doctor"`
	PharmacyName        pgtype.Text `json:"pharmacy_name"`
	PrescriptionDate    pgtype.Date `json:"prescription_date"`
	StartDate           pgtype.Date `json:"start_date"`
	EndDate             pgtype.Date `json:"end_date"`
	ReasonForMedication pgtype.Text `json:"reason_for_medication"`
	Status              pgtype.Text `json:"status"`
	SideEffects         pgtype.Text `json:"side_effects"`
	Instructions        pgtype.Text `json:"instructions"`
}

// ============================================
// PATIENT MEDICATIONS REPOSITORY QUERIES
// Maps to: Part of PatientRepository interface
// Domain: Patient Medication Management
// ============================================
// ============================================
// CORE CRUD OPERATIONS
// ============================================
func (q *Queries) AddPatientMedication(ctx context.Context, arg AddPatientMedicationParams) (PatientMedication, error) {
	row := q.db.QueryRow(ctx, addPatientMedication,
		arg.PatientID,
		arg.MedicationName,
		arg.GenericName,
		arg.Dosage,
		arg.Frequency,
		arg.Route,
		arg.PrescribingDoctor,
		arg.PharmacyName,
		arg.PrescriptionDate,
		arg.StartDate,
		arg.EndDate,
		arg.ReasonForMedication,
		arg.Status,
		arg.SideEffects,
		arg.Instructions,
	)
	var i PatientMedication
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.MedicationName,
		&i.GenericName,
		&i.Dosage,
		&i.Frequency,
		&i.Route,
		&i.PrescribingDoctor,
		&i.PharmacyName,
		&i.PrescriptionDate,
		&i.StartDate,
		&i.EndDate,
		&i.ReasonForMedication,
		&i.Status,
		&i.SideEffects,
		&i.Instructions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePatientMedication = `-- name: DeletePatientMedication :exec
DELETE FROM patient_medications WHERE id = $1
`

func (q *Queries) DeletePatientMedication(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePatientMedication, id)
	return err
}

const getActiveMedications = `-- name: GetActiveMedications :many
SELECT 
    id, medication_name, generic_name, dosage, frequency,
    route, prescribing_doctor, start_date, reason_for_medication, instructions
FROM patient_medications
WHERE 
    patient_id = $1
    AND status = 'active'
ORDER BY start_date DESC
`

type GetActiveMedicationsRow struct {
	ID                  pgtype.UUID `json:"id"`
	MedicationName      string      `json:"medication_name"`
	GenericName         pgtype.Text `json:"generic_name"`
	Dosage              pgtype.Text `json:"dosage"`
	Frequency           pgtype.Text `json:"frequency"`
	Route               pgtype.Text `json:"route"`
	PrescribingDoctor   pgtype.Text `json:"prescribing_doctor"`
	StartDate           pgtype.Date `json:"start_date"`
	ReasonForMedication pgtype.Text `json:"reason_for_medication"`
	Instructions        pgtype.Text `json:"instructions"`
}

func (q *Queries) GetActiveMedications(ctx context.Context, patientID pgtype.UUID) ([]GetActiveMedicationsRow, error) {
	rows, err := q.db.Query(ctx, getActiveMedications, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveMedicationsRow{}
	for rows.Next() {
		var i GetActiveMedicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.MedicationName,
			&i.GenericName,
			&i.Dosage,
			&i.Frequency,
			&i.Route,
			&i.PrescribingDoctor,
			&i.StartDate,
			&i.ReasonForMedication,
			&i.Instructions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPatientMedication = `-- name: GetPatientMedication :one
SELECT id, patient_id, medication_name, generic_name, dosage, frequency, route, prescribing_doctor, pharmacy_name, prescription_date, start_date, end_date, reason_for_medication, status, side_effects, instructions, created_at, updated_at FROM patient_medications
WHERE id = $1
`

func (q *Queries) GetPatientMedication(ctx context.Context, id pgtype.UUID) (PatientMedication, error) {
	row := q.db.QueryRow(ctx, getPatientMedication, id)
	var i PatientMedication
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.MedicationName,
		&i.GenericName,
		&i.Dosage,
		&i.Frequency,
		&i.Route,
		&i.PrescribingDoctor,
		&i.PharmacyName,
		&i.PrescriptionDate,
		&i.StartDate,
		&i.EndDate,
		&i.ReasonForMedication,
		&i.Status,
		&i.SideEffects,
		&i.Instructions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatientMedications = `-- name: GetPatientMedications :many

SELECT 
    id, patient_id, medication_name, generic_name, dosage,
    frequency, route, prescribing_doctor, start_date, end_date,
    reason_for_medication, status, instructions, side_effects,
    created_at, updated_at
FROM patient_medications
WHERE 
    patient_id = $1
    AND ($2::VARCHAR IS NULL OR status = $2)
ORDER BY 
    CASE status
        WHEN 'active' THEN 1
        WHEN 'completed' THEN 2
        WHEN 'discontinued' THEN 3
        ELSE 4
    END,
    start_date DESC
`

type GetPatientMedicationsParams struct {
	PatientID pgtype.UUID `json:"patient_id"`
	Column2   string      `json:"column_2"`
}

type GetPatientMedicationsRow struct {
	ID                  pgtype.UUID      `json:"id"`
	PatientID           pgtype.UUID      `json:"patient_id"`
	MedicationName      string           `json:"medication_name"`
	GenericName         pgtype.Text      `json:"generic_name"`
	Dosage              pgtype.Text      `json:"dosage"`
	Frequency           pgtype.Text      `json:"frequency"`
	Route               pgtype.Text      `json:"route"`
	PrescribingDoctor   pgtype.Text      `json:"prescribing_doctor"`
	StartDate           pgtype.Date      `json:"start_date"`
	EndDate             pgtype.Date      `json:"end_date"`
	ReasonForMedication pgtype.Text      `json:"reason_for_medication"`
	Status              pgtype.Text      `json:"status"`
	Instructions        pgtype.Text      `json:"instructions"`
	SideEffects         pgtype.Text      `json:"side_effects"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

// ============================================
// QUERYING BY PATIENT
// ============================================
func (q *Queries) GetPatientMedications(ctx context.Context, arg GetPatientMedicationsParams) ([]GetPatientMedicationsRow, error) {
	rows, err := q.db.Query(ctx, getPatientMedications, arg.PatientID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPatientMedicationsRow{}
	for rows.Next() {
		var i GetPatientMedicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.MedicationName,
			&i.GenericName,
			&i.Dosage,
			&i.Frequency,
			&i.Route,
			&i.PrescribingDoctor,
			&i.StartDate,
			&i.EndDate,
			&i.ReasonForMedication,
			&i.Status,
			&i.Instructions,
			&i.SideEffects,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatientMedication = `-- name: UpdatePatientMedication :exec
UPDATE patient_medications
SET 
    medication_name = COALESCE($2, medication_name),
    generic_name = COALESCE($3, generic_name),
    dosage = COALESCE($4, dosage),
    frequency = COALESCE($5, frequency),
    route = COALESCE($6, route),
    end_date = COALESCE($7, end_date),
    status = COALESCE($8, status),
    side_effects = COALESCE($9, side_effects),
    instructions = COALESCE($10, instructions),
    updated_at = NOW()
WHERE id = $1
`

type UpdatePatientMedicationParams struct {
	ID             pgtype.UUID `json:"id"`
	MedicationName string      `json:"medication_name"`
	GenericName    pgtype.Text `json:"generic_name"`
	Dosage         pgtype.Text `json:"dosage"`
	Frequency      pgtype.Text `json:"frequency"`
	Route          pgtype.Text `json:"route"`
	EndDate        pgtype.Date `json:"end_date"`
	Status         pgtype.Text `json:"status"`
	SideEffects    pgtype.Text `json:"side_effects"`
	Instructions   pgtype.Text `json:"instructions"`
}

func (q *Queries) UpdatePatientMedication(ctx context.Context, arg UpdatePatientMedicationParams) error {
	_, err := q.db.Exec(ctx, updatePatientMedication,
		arg.ID,
		arg.MedicationName,
		arg.GenericName,
		arg.Dosage,
		arg.Frequency,
		arg.Route,
		arg.EndDate,
		arg.Status,
		arg.SideEffects,
		arg.Instructions,
	)
	return err
}
