// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patient_dependents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPatientDependent = `-- name: AddPatientDependent :one


INSERT INTO patient_dependents (
    patient_id, first_name, last_name, date_of_birth, gender, relationship,
    blood_type, health_status, primary_pediatrician, clinic_id,
    birth_weight_kg, birth_height_cm, school_name, grade,
    has_legal_guardianship, guardianship_document_url,
    has_special_needs, special_needs_description
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING id, patient_id, first_name, last_name, date_of_birth, gender, relationship, blood_type, health_status, primary_pediatrician, clinic_id, birth_weight_kg, birth_height_cm, school_name, grade, has_legal_guardianship, guardianship_document_url, has_special_needs, special_needs_description, created_at, updated_at
`

type AddPatientDependentParams struct {
	PatientID               pgtype.UUID    `json:"patient_id"`
	FirstName               string         `json:"first_name"`
	LastName                string         `json:"last_name"`
	DateOfBirth             pgtype.Date    `json:"date_of_birth"`
	Gender                  pgtype.Text    `json:"gender"`
	Relationship            string         `json:"relationship"`
	BloodType               pgtype.Text    `json:"blood_type"`
	HealthStatus            pgtype.Text    `json:"health_status"`
	PrimaryPediatrician     pgtype.Text    `json:"primary_pediatrician"`
	ClinicID                pgtype.UUID    `json:"clinic_id"`
	BirthWeightKg           pgtype.Numeric `json:"birth_weight_kg"`
	BirthHeightCm           pgtype.Numeric `json:"birth_height_cm"`
	SchoolName              pgtype.Text    `json:"school_name"`
	Grade                   pgtype.Text    `json:"grade"`
	HasLegalGuardianship    pgtype.Bool    `json:"has_legal_guardianship"`
	GuardianshipDocumentUrl pgtype.Text    `json:"guardianship_document_url"`
	HasSpecialNeeds         pgtype.Bool    `json:"has_special_needs"`
	SpecialNeedsDescription pgtype.Text    `json:"special_needs_description"`
}

// ============================================
// PATIENT DEPENDENTS REPOSITORY QUERIES
// Maps to: Part of PatientRepository interface
// Domain: Patient Dependent (Children/Wards) Management
// ============================================
// ============================================
// CORE CRUD OPERATIONS
// ============================================
func (q *Queries) AddPatientDependent(ctx context.Context, arg AddPatientDependentParams) (PatientDependent, error) {
	row := q.db.QueryRow(ctx, addPatientDependent,
		arg.PatientID,
		arg.FirstName,
		arg.LastName,
		arg.DateOfBirth,
		arg.Gender,
		arg.Relationship,
		arg.BloodType,
		arg.HealthStatus,
		arg.PrimaryPediatrician,
		arg.ClinicID,
		arg.BirthWeightKg,
		arg.BirthHeightCm,
		arg.SchoolName,
		arg.Grade,
		arg.HasLegalGuardianship,
		arg.GuardianshipDocumentUrl,
		arg.HasSpecialNeeds,
		arg.SpecialNeedsDescription,
	)
	var i PatientDependent
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Relationship,
		&i.BloodType,
		&i.HealthStatus,
		&i.PrimaryPediatrician,
		&i.ClinicID,
		&i.BirthWeightKg,
		&i.BirthHeightCm,
		&i.SchoolName,
		&i.Grade,
		&i.HasLegalGuardianship,
		&i.GuardianshipDocumentUrl,
		&i.HasSpecialNeeds,
		&i.SpecialNeedsDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePatientDependent = `-- name: DeletePatientDependent :exec
DELETE FROM patient_dependents WHERE id = $1
`

func (q *Queries) DeletePatientDependent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePatientDependent, id)
	return err
}

const getDependentChildren = `-- name: GetDependentChildren :many
SELECT 
    id, first_name, last_name, date_of_birth, gender,
    health_status, school_name, grade
FROM patient_dependents
WHERE 
    patient_id = $1
    AND relationship = 'child'
ORDER BY date_of_birth DESC
`

type GetDependentChildrenRow struct {
	ID           pgtype.UUID `json:"id"`
	FirstName    string      `json:"first_name"`
	LastName     string      `json:"last_name"`
	DateOfBirth  pgtype.Date `json:"date_of_birth"`
	Gender       pgtype.Text `json:"gender"`
	HealthStatus pgtype.Text `json:"health_status"`
	SchoolName   pgtype.Text `json:"school_name"`
	Grade        pgtype.Text `json:"grade"`
}

func (q *Queries) GetDependentChildren(ctx context.Context, patientID pgtype.UUID) ([]GetDependentChildrenRow, error) {
	rows, err := q.db.Query(ctx, getDependentChildren, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDependentChildrenRow{}
	for rows.Next() {
		var i GetDependentChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.DateOfBirth,
			&i.Gender,
			&i.HealthStatus,
			&i.SchoolName,
			&i.Grade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPatientDependent = `-- name: GetPatientDependent :one
SELECT id, patient_id, first_name, last_name, date_of_birth, gender, relationship, blood_type, health_status, primary_pediatrician, clinic_id, birth_weight_kg, birth_height_cm, school_name, grade, has_legal_guardianship, guardianship_document_url, has_special_needs, special_needs_description, created_at, updated_at FROM patient_dependents
WHERE id = $1
`

func (q *Queries) GetPatientDependent(ctx context.Context, id pgtype.UUID) (PatientDependent, error) {
	row := q.db.QueryRow(ctx, getPatientDependent, id)
	var i PatientDependent
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Relationship,
		&i.BloodType,
		&i.HealthStatus,
		&i.PrimaryPediatrician,
		&i.ClinicID,
		&i.BirthWeightKg,
		&i.BirthHeightCm,
		&i.SchoolName,
		&i.Grade,
		&i.HasLegalGuardianship,
		&i.GuardianshipDocumentUrl,
		&i.HasSpecialNeeds,
		&i.SpecialNeedsDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatientDependents = `-- name: GetPatientDependents :many

SELECT 
    id, patient_id, first_name, last_name, date_of_birth,
    gender, relationship, blood_type, health_status,
    primary_pediatrician, school_name, grade,
    has_special_needs, created_at, updated_at
FROM patient_dependents
WHERE patient_id = $1
ORDER BY date_of_birth DESC
`

type GetPatientDependentsRow struct {
	ID                  pgtype.UUID      `json:"id"`
	PatientID           pgtype.UUID      `json:"patient_id"`
	FirstName           string           `json:"first_name"`
	LastName            string           `json:"last_name"`
	DateOfBirth         pgtype.Date      `json:"date_of_birth"`
	Gender              pgtype.Text      `json:"gender"`
	Relationship        string           `json:"relationship"`
	BloodType           pgtype.Text      `json:"blood_type"`
	HealthStatus        pgtype.Text      `json:"health_status"`
	PrimaryPediatrician pgtype.Text      `json:"primary_pediatrician"`
	SchoolName          pgtype.Text      `json:"school_name"`
	Grade               pgtype.Text      `json:"grade"`
	HasSpecialNeeds     pgtype.Bool      `json:"has_special_needs"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

// ============================================
// QUERYING BY PATIENT
// ============================================
func (q *Queries) GetPatientDependents(ctx context.Context, patientID pgtype.UUID) ([]GetPatientDependentsRow, error) {
	rows, err := q.db.Query(ctx, getPatientDependents, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPatientDependentsRow{}
	for rows.Next() {
		var i GetPatientDependentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.FirstName,
			&i.LastName,
			&i.DateOfBirth,
			&i.Gender,
			&i.Relationship,
			&i.BloodType,
			&i.HealthStatus,
			&i.PrimaryPediatrician,
			&i.SchoolName,
			&i.Grade,
			&i.HasSpecialNeeds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatientDependent = `-- name: UpdatePatientDependent :exec
UPDATE patient_dependents
SET 
    first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    date_of_birth = COALESCE($4, date_of_birth),
    gender = COALESCE($5, gender),
    blood_type = COALESCE($6, blood_type),
    health_status = COALESCE($7, health_status),
    primary_pediatrician = COALESCE($8, primary_pediatrician),
    clinic_id = COALESCE($9, clinic_id),
    school_name = COALESCE($10, school_name),
    grade = COALESCE($11, grade),
    has_special_needs = COALESCE($12, has_special_needs),
    special_needs_description = COALESCE($13, special_needs_description),
    updated_at = NOW()
WHERE id = $1
`

type UpdatePatientDependentParams struct {
	ID                      pgtype.UUID `json:"id"`
	FirstName               string      `json:"first_name"`
	LastName                string      `json:"last_name"`
	DateOfBirth             pgtype.Date `json:"date_of_birth"`
	Gender                  pgtype.Text `json:"gender"`
	BloodType               pgtype.Text `json:"blood_type"`
	HealthStatus            pgtype.Text `json:"health_status"`
	PrimaryPediatrician     pgtype.Text `json:"primary_pediatrician"`
	ClinicID                pgtype.UUID `json:"clinic_id"`
	SchoolName              pgtype.Text `json:"school_name"`
	Grade                   pgtype.Text `json:"grade"`
	HasSpecialNeeds         pgtype.Bool `json:"has_special_needs"`
	SpecialNeedsDescription pgtype.Text `json:"special_needs_description"`
}

func (q *Queries) UpdatePatientDependent(ctx context.Context, arg UpdatePatientDependentParams) error {
	_, err := q.db.Exec(ctx, updatePatientDependent,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.DateOfBirth,
		arg.Gender,
		arg.BloodType,
		arg.HealthStatus,
		arg.PrimaryPediatrician,
		arg.ClinicID,
		arg.SchoolName,
		arg.Grade,
		arg.HasSpecialNeeds,
		arg.SpecialNeedsDescription,
	)
	return err
}
