// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patient_medical_info.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPatientMedicalInfo = `-- name: CreatePatientMedicalInfo :one

INSERT INTO patient_medical_info (
    patient_id, blood_type, height_cm, weight_kg, bmi, 
    overall_health_status, health_summary, primary_care_physician, 
    primary_clinic_id, organ_donor, dnr_status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, patient_id, blood_type, overall_health_status, created_at, updated_at
`

type CreatePatientMedicalInfoParams struct {
	PatientID            pgtype.UUID    `json:"patient_id"`
	BloodType            pgtype.Text    `json:"blood_type"`
	HeightCm             pgtype.Numeric `json:"height_cm"`
	WeightKg             pgtype.Numeric `json:"weight_kg"`
	Bmi                  pgtype.Numeric `json:"bmi"`
	OverallHealthStatus  pgtype.Text    `json:"overall_health_status"`
	HealthSummary        pgtype.Text    `json:"health_summary"`
	PrimaryCarePhysician pgtype.Text    `json:"primary_care_physician"`
	PrimaryClinicID      pgtype.UUID    `json:"primary_clinic_id"`
	OrganDonor           pgtype.Bool    `json:"organ_donor"`
	DnrStatus            pgtype.Bool    `json:"dnr_status"`
}

type CreatePatientMedicalInfoRow struct {
	ID                  pgtype.UUID      `json:"id"`
	PatientID           pgtype.UUID      `json:"patient_id"`
	BloodType           pgtype.Text      `json:"blood_type"`
	OverallHealthStatus pgtype.Text      `json:"overall_health_status"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

// ============================================
// Patient Medical Info Queries
// ============================================
func (q *Queries) CreatePatientMedicalInfo(ctx context.Context, arg CreatePatientMedicalInfoParams) (CreatePatientMedicalInfoRow, error) {
	row := q.db.QueryRow(ctx, createPatientMedicalInfo,
		arg.PatientID,
		arg.BloodType,
		arg.HeightCm,
		arg.WeightKg,
		arg.Bmi,
		arg.OverallHealthStatus,
		arg.HealthSummary,
		arg.PrimaryCarePhysician,
		arg.PrimaryClinicID,
		arg.OrganDonor,
		arg.DnrStatus,
	)
	var i CreatePatientMedicalInfoRow
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.BloodType,
		&i.OverallHealthStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatientMedicalInfo = `-- name: GetPatientMedicalInfo :one
SELECT id, patient_id, blood_type, blood_type_last_tested, height_cm, weight_kg, bmi, last_measured_date, overall_health_status, health_summary, primary_care_physician, primary_clinic_id, organ_donor, advance_directive_exists, advance_directive_url, dnr_status, created_at, updated_at FROM patient_medical_info WHERE patient_id = $1
`

func (q *Queries) GetPatientMedicalInfo(ctx context.Context, patientID pgtype.UUID) (PatientMedicalInfo, error) {
	row := q.db.QueryRow(ctx, getPatientMedicalInfo, patientID)
	var i PatientMedicalInfo
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.BloodType,
		&i.BloodTypeLastTested,
		&i.HeightCm,
		&i.WeightKg,
		&i.Bmi,
		&i.LastMeasuredDate,
		&i.OverallHealthStatus,
		&i.HealthSummary,
		&i.PrimaryCarePhysician,
		&i.PrimaryClinicID,
		&i.OrganDonor,
		&i.AdvanceDirectiveExists,
		&i.AdvanceDirectiveUrl,
		&i.DnrStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePatientMedicalInfo = `-- name: UpdatePatientMedicalInfo :exec
UPDATE patient_medical_info
SET blood_type = $2, height_cm = $3, weight_kg = $4, bmi = $5,
    overall_health_status = $6, health_summary = $7, 
    primary_care_physician = $8, primary_clinic_id = $9,
    last_measured_date = $10
WHERE patient_id = $1
`

type UpdatePatientMedicalInfoParams struct {
	PatientID            pgtype.UUID    `json:"patient_id"`
	BloodType            pgtype.Text    `json:"blood_type"`
	HeightCm             pgtype.Numeric `json:"height_cm"`
	WeightKg             pgtype.Numeric `json:"weight_kg"`
	Bmi                  pgtype.Numeric `json:"bmi"`
	OverallHealthStatus  pgtype.Text    `json:"overall_health_status"`
	HealthSummary        pgtype.Text    `json:"health_summary"`
	PrimaryCarePhysician pgtype.Text    `json:"primary_care_physician"`
	PrimaryClinicID      pgtype.UUID    `json:"primary_clinic_id"`
	LastMeasuredDate     pgtype.Date    `json:"last_measured_date"`
}

func (q *Queries) UpdatePatientMedicalInfo(ctx context.Context, arg UpdatePatientMedicalInfoParams) error {
	_, err := q.db.Exec(ctx, updatePatientMedicalInfo,
		arg.PatientID,
		arg.BloodType,
		arg.HeightCm,
		arg.WeightKg,
		arg.Bmi,
		arg.OverallHealthStatus,
		arg.HealthSummary,
		arg.PrimaryCarePhysician,
		arg.PrimaryClinicID,
		arg.LastMeasuredDate,
	)
	return err
}
