// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patient_profiles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkNationalIDExists = `-- name: CheckNationalIDExists :one
SELECT EXISTS(
    SELECT 1 FROM patient_profiles 
    WHERE 
        national_id_number = $1
        AND ($2::uuid IS NULL OR user_id != $2)
) as exists
`

type CheckNationalIDExistsParams struct {
	NationalIDNumber pgtype.Text `json:"national_id_number"`
	Column2          pgtype.UUID `json:"column_2"`
}

func (q *Queries) CheckNationalIDExists(ctx context.Context, arg CheckNationalIDExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkNationalIDExists, arg.NationalIDNumber, arg.Column2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createPatientProfile = `-- name: CreatePatientProfile :one


INSERT INTO patient_profiles (
    user_id, first_name, last_name, preferred_name, date_of_birth,
    gender, preferred_gender_pronouns, primary_address, city, province,
    postal_code, country, language_preferences, home_language,
    requires_interpreter, preferred_communication_method,
    medical_aid_number, medical_aid_provider, has_medical_aid,
    national_id_number, employment_status, education_level,
    household_income_range, timezone, referred_by, referral_code,
    accepts_marketing_emails
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27
)
RETURNING id, user_id, first_name, last_name, preferred_name, date_of_birth, gender, preferred_gender_pronouns, primary_address, city, province, postal_code, country, language_preferences, home_language, requires_interpreter, preferred_communication_method, medical_aid_number, medical_aid_provider, has_medical_aid, national_id_number, employment_status, education_level, household_income_range, profile_picture_url, timezone, last_profile_update, referred_by, referral_code, accepts_marketing_emails, created_at, updated_at
`

type CreatePatientProfileParams struct {
	UserID                       pgtype.UUID `json:"user_id"`
	FirstName                    string      `json:"first_name"`
	LastName                     string      `json:"last_name"`
	PreferredName                pgtype.Text `json:"preferred_name"`
	DateOfBirth                  pgtype.Date `json:"date_of_birth"`
	Gender                       pgtype.Text `json:"gender"`
	PreferredGenderPronouns      pgtype.Text `json:"preferred_gender_pronouns"`
	PrimaryAddress               pgtype.Text `json:"primary_address"`
	City                         pgtype.Text `json:"city"`
	Province                     pgtype.Text `json:"province"`
	PostalCode                   pgtype.Text `json:"postal_code"`
	Country                      pgtype.Text `json:"country"`
	LanguagePreferences          []string    `json:"language_preferences"`
	HomeLanguage                 pgtype.Text `json:"home_language"`
	RequiresInterpreter          pgtype.Bool `json:"requires_interpreter"`
	PreferredCommunicationMethod pgtype.Text `json:"preferred_communication_method"`
	MedicalAidNumber             pgtype.Text `json:"medical_aid_number"`
	MedicalAidProvider           pgtype.Text `json:"medical_aid_provider"`
	HasMedicalAid                pgtype.Bool `json:"has_medical_aid"`
	NationalIDNumber             pgtype.Text `json:"national_id_number"`
	EmploymentStatus             pgtype.Text `json:"employment_status"`
	EducationLevel               pgtype.Text `json:"education_level"`
	HouseholdIncomeRange         pgtype.Text `json:"household_income_range"`
	Timezone                     pgtype.Text `json:"timezone"`
	ReferredBy                   pgtype.UUID `json:"referred_by"`
	ReferralCode                 pgtype.Text `json:"referral_code"`
	AcceptsMarketingEmails       pgtype.Bool `json:"accepts_marketing_emails"`
}

// ============================================
// PATIENT PROFILE REPOSITORY QUERIES
// Maps to: PatientProfileRepository interface
// Domain: Patient Profile & Demographics Management
// ============================================
// ============================================
// CORE CRUD OPERATIONS
// ============================================
func (q *Queries) CreatePatientProfile(ctx context.Context, arg CreatePatientProfileParams) (PatientProfile, error) {
	row := q.db.QueryRow(ctx, createPatientProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.PreferredName,
		arg.DateOfBirth,
		arg.Gender,
		arg.PreferredGenderPronouns,
		arg.PrimaryAddress,
		arg.City,
		arg.Province,
		arg.PostalCode,
		arg.Country,
		arg.LanguagePreferences,
		arg.HomeLanguage,
		arg.RequiresInterpreter,
		arg.PreferredCommunicationMethod,
		arg.MedicalAidNumber,
		arg.MedicalAidProvider,
		arg.HasMedicalAid,
		arg.NationalIDNumber,
		arg.EmploymentStatus,
		arg.EducationLevel,
		arg.HouseholdIncomeRange,
		arg.Timezone,
		arg.ReferredBy,
		arg.ReferralCode,
		arg.AcceptsMarketingEmails,
	)
	var i PatientProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.PreferredName,
		&i.DateOfBirth,
		&i.Gender,
		&i.PreferredGenderPronouns,
		&i.PrimaryAddress,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.Country,
		&i.LanguagePreferences,
		&i.HomeLanguage,
		&i.RequiresInterpreter,
		&i.PreferredCommunicationMethod,
		&i.MedicalAidNumber,
		&i.MedicalAidProvider,
		&i.HasMedicalAid,
		&i.NationalIDNumber,
		&i.EmploymentStatus,
		&i.EducationLevel,
		&i.HouseholdIncomeRange,
		&i.ProfilePictureUrl,
		&i.Timezone,
		&i.LastProfileUpdate,
		&i.ReferredBy,
		&i.ReferralCode,
		&i.AcceptsMarketingEmails,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePatientProfile = `-- name: DeletePatientProfile :exec
DELETE FROM patient_profiles WHERE id = $1
`

func (q *Queries) DeletePatientProfile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePatientProfile, id)
	return err
}

const deletePatientProfileByUserID = `-- name: DeletePatientProfileByUserID :exec
DELETE FROM patient_profiles WHERE user_id = $1
`

func (q *Queries) DeletePatientProfileByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePatientProfileByUserID, userID)
	return err
}

const dependentBelongsToPatient = `-- name: DependentBelongsToPatient :one

SELECT EXISTS(
    SELECT 1
    FROM patient_dependents
    WHERE id         = $2
      AND patient_id = $1
) AS exists
`

type DependentBelongsToPatientParams struct {
	PatientID pgtype.UUID `json:"patient_id"`
	ID        pgtype.UUID `json:"id"`
}

// ============================================
// DEPENDENT OWNERSHIP
// ============================================
// Verifies that a dependent record belongs to a given patient.
// Called by the symptom checker service before accepting a session submission
// on behalf of a dependent, preventing cross-patient data access.
// $1 = patient_id (UUID of the patient_profile)
// $2 = dependent_id (UUID of the patient_dependents row)
func (q *Queries) DependentBelongsToPatient(ctx context.Context, arg DependentBelongsToPatientParams) (bool, error) {
	row := q.db.QueryRow(ctx, dependentBelongsToPatient, arg.PatientID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getPatientProfileByID = `-- name: GetPatientProfileByID :one
SELECT id, user_id, first_name, last_name, preferred_name, date_of_birth, gender, preferred_gender_pronouns, primary_address, city, province, postal_code, country, language_preferences, home_language, requires_interpreter, preferred_communication_method, medical_aid_number, medical_aid_provider, has_medical_aid, national_id_number, employment_status, education_level, household_income_range, profile_picture_url, timezone, last_profile_update, referred_by, referral_code, accepts_marketing_emails, created_at, updated_at FROM patient_profiles
WHERE id = $1
`

func (q *Queries) GetPatientProfileByID(ctx context.Context, id pgtype.UUID) (PatientProfile, error) {
	row := q.db.QueryRow(ctx, getPatientProfileByID, id)
	var i PatientProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.PreferredName,
		&i.DateOfBirth,
		&i.Gender,
		&i.PreferredGenderPronouns,
		&i.PrimaryAddress,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.Country,
		&i.LanguagePreferences,
		&i.HomeLanguage,
		&i.RequiresInterpreter,
		&i.PreferredCommunicationMethod,
		&i.MedicalAidNumber,
		&i.MedicalAidProvider,
		&i.HasMedicalAid,
		&i.NationalIDNumber,
		&i.EmploymentStatus,
		&i.EducationLevel,
		&i.HouseholdIncomeRange,
		&i.ProfilePictureUrl,
		&i.Timezone,
		&i.LastProfileUpdate,
		&i.ReferredBy,
		&i.ReferralCode,
		&i.AcceptsMarketingEmails,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatientProfileByNationalID = `-- name: GetPatientProfileByNationalID :one
SELECT id, user_id, first_name, last_name, preferred_name, date_of_birth, gender, preferred_gender_pronouns, primary_address, city, province, postal_code, country, language_preferences, home_language, requires_interpreter, preferred_communication_method, medical_aid_number, medical_aid_provider, has_medical_aid, national_id_number, employment_status, education_level, household_income_range, profile_picture_url, timezone, last_profile_update, referred_by, referral_code, accepts_marketing_emails, created_at, updated_at FROM patient_profiles
WHERE national_id_number = $1
LIMIT 1
`

func (q *Queries) GetPatientProfileByNationalID(ctx context.Context, nationalIDNumber pgtype.Text) (PatientProfile, error) {
	row := q.db.QueryRow(ctx, getPatientProfileByNationalID, nationalIDNumber)
	var i PatientProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.PreferredName,
		&i.DateOfBirth,
		&i.Gender,
		&i.PreferredGenderPronouns,
		&i.PrimaryAddress,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.Country,
		&i.LanguagePreferences,
		&i.HomeLanguage,
		&i.RequiresInterpreter,
		&i.PreferredCommunicationMethod,
		&i.MedicalAidNumber,
		&i.MedicalAidProvider,
		&i.HasMedicalAid,
		&i.NationalIDNumber,
		&i.EmploymentStatus,
		&i.EducationLevel,
		&i.HouseholdIncomeRange,
		&i.ProfilePictureUrl,
		&i.Timezone,
		&i.LastProfileUpdate,
		&i.ReferredBy,
		&i.ReferralCode,
		&i.AcceptsMarketingEmails,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatientProfileByUserID = `-- name: GetPatientProfileByUserID :one
SELECT id, user_id, first_name, last_name, preferred_name, date_of_birth, gender, preferred_gender_pronouns, primary_address, city, province, postal_code, country, language_preferences, home_language, requires_interpreter, preferred_communication_method, medical_aid_number, medical_aid_provider, has_medical_aid, national_id_number, employment_status, education_level, household_income_range, profile_picture_url, timezone, last_profile_update, referred_by, referral_code, accepts_marketing_emails, created_at, updated_at FROM patient_profiles
WHERE user_id = $1
`

func (q *Queries) GetPatientProfileByUserID(ctx context.Context, userID pgtype.UUID) (PatientProfile, error) {
	row := q.db.QueryRow(ctx, getPatientProfileByUserID, userID)
	var i PatientProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.PreferredName,
		&i.DateOfBirth,
		&i.Gender,
		&i.PreferredGenderPronouns,
		&i.PrimaryAddress,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.Country,
		&i.LanguagePreferences,
		&i.HomeLanguage,
		&i.RequiresInterpreter,
		&i.PreferredCommunicationMethod,
		&i.MedicalAidNumber,
		&i.MedicalAidProvider,
		&i.HasMedicalAid,
		&i.NationalIDNumber,
		&i.EmploymentStatus,
		&i.EducationLevel,
		&i.HouseholdIncomeRange,
		&i.ProfilePictureUrl,
		&i.Timezone,
		&i.LastProfileUpdate,
		&i.ReferredBy,
		&i.ReferralCode,
		&i.AcceptsMarketingEmails,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchPatients = `-- name: SearchPatients :many

SELECT 
    id, user_id, first_name, last_name, preferred_name,
    date_of_birth, gender, city, province,
    preferred_communication_method, has_medical_aid,
    created_at, updated_at
FROM patient_profiles
WHERE 
    ($1::TEXT IS NULL OR $1 = '' OR 
     first_name ILIKE '%' || $1 || '%' OR 
     last_name ILIKE '%' || $1 || '%' OR
     preferred_name ILIKE '%' || $1 || '%')
    AND ($2::VARCHAR IS NULL OR province = $2)
    AND ($3::VARCHAR IS NULL OR city = $3)
    AND ($4::BOOLEAN IS NULL OR has_medical_aid = $4)
    AND ($5::VARCHAR IS NULL OR gender = $5)
ORDER BY last_name, first_name
LIMIT $6 OFFSET $7
`

type SearchPatientsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 bool   `json:"column_4"`
	Column5 string `json:"column_5"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type SearchPatientsRow struct {
	ID                           pgtype.UUID      `json:"id"`
	UserID                       pgtype.UUID      `json:"user_id"`
	FirstName                    string           `json:"first_name"`
	LastName                     string           `json:"last_name"`
	PreferredName                pgtype.Text      `json:"preferred_name"`
	DateOfBirth                  pgtype.Date      `json:"date_of_birth"`
	Gender                       pgtype.Text      `json:"gender"`
	City                         pgtype.Text      `json:"city"`
	Province                     pgtype.Text      `json:"province"`
	PreferredCommunicationMethod pgtype.Text      `json:"preferred_communication_method"`
	HasMedicalAid                pgtype.Bool      `json:"has_medical_aid"`
	CreatedAt                    pgtype.Timestamp `json:"created_at"`
	UpdatedAt                    pgtype.Timestamp `json:"updated_at"`
}

// ============================================
// SEARCH & DISCOVERY
// ============================================
func (q *Queries) SearchPatients(ctx context.Context, arg SearchPatientsParams) ([]SearchPatientsRow, error) {
	rows, err := q.db.Query(ctx, searchPatients,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPatientsRow{}
	for rows.Next() {
		var i SearchPatientsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.PreferredName,
			&i.DateOfBirth,
			&i.Gender,
			&i.City,
			&i.Province,
			&i.PreferredCommunicationMethod,
			&i.HasMedicalAid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPatientsByName = `-- name: SearchPatientsByName :many
SELECT 
    id, user_id, first_name, last_name, preferred_name,
    city, province, date_of_birth, created_at
FROM patient_profiles
WHERE 
    first_name ILIKE '%' || $1 || '%' 
    OR last_name ILIKE '%' || $1 || '%'
    OR preferred_name ILIKE '%' || $1 || '%'
ORDER BY last_name, first_name
LIMIT $2 OFFSET $3
`

type SearchPatientsByNameParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type SearchPatientsByNameRow struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	FirstName     string           `json:"first_name"`
	LastName      string           `json:"last_name"`
	PreferredName pgtype.Text      `json:"preferred_name"`
	City          pgtype.Text      `json:"city"`
	Province      pgtype.Text      `json:"province"`
	DateOfBirth   pgtype.Date      `json:"date_of_birth"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) SearchPatientsByName(ctx context.Context, arg SearchPatientsByNameParams) ([]SearchPatientsByNameRow, error) {
	rows, err := q.db.Query(ctx, searchPatientsByName, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPatientsByNameRow{}
	for rows.Next() {
		var i SearchPatientsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.PreferredName,
			&i.City,
			&i.Province,
			&i.DateOfBirth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatientProfile = `-- name: UpdatePatientProfile :exec
UPDATE patient_profiles
SET 
    first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    preferred_name = COALESCE($4, preferred_name),
    date_of_birth = COALESCE($5, date_of_birth),
    gender = COALESCE($6, gender),
    preferred_gender_pronouns = COALESCE($7, preferred_gender_pronouns),
    primary_address = COALESCE($8, primary_address),
    city = COALESCE($9, city),
    province = COALESCE($10, province),
    postal_code = COALESCE($11, postal_code),
    country = COALESCE($12, country),
    preferred_communication_method = COALESCE($13, preferred_communication_method),
    employment_status = COALESCE($14, employment_status),
    education_level = COALESCE($15, education_level),
    household_income_range = COALESCE($16, household_income_range),
    last_profile_update = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type UpdatePatientProfileParams struct {
	ID                           pgtype.UUID `json:"id"`
	FirstName                    string      `json:"first_name"`
	LastName                     string      `json:"last_name"`
	PreferredName                pgtype.Text `json:"preferred_name"`
	DateOfBirth                  pgtype.Date `json:"date_of_birth"`
	Gender                       pgtype.Text `json:"gender"`
	PreferredGenderPronouns      pgtype.Text `json:"preferred_gender_pronouns"`
	PrimaryAddress               pgtype.Text `json:"primary_address"`
	City                         pgtype.Text `json:"city"`
	Province                     pgtype.Text `json:"province"`
	PostalCode                   pgtype.Text `json:"postal_code"`
	Country                      pgtype.Text `json:"country"`
	PreferredCommunicationMethod pgtype.Text `json:"preferred_communication_method"`
	EmploymentStatus             pgtype.Text `json:"employment_status"`
	EducationLevel               pgtype.Text `json:"education_level"`
	HouseholdIncomeRange         pgtype.Text `json:"household_income_range"`
}

func (q *Queries) UpdatePatientProfile(ctx context.Context, arg UpdatePatientProfileParams) error {
	_, err := q.db.Exec(ctx, updatePatientProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.PreferredName,
		arg.DateOfBirth,
		arg.Gender,
		arg.PreferredGenderPronouns,
		arg.PrimaryAddress,
		arg.City,
		arg.Province,
		arg.PostalCode,
		arg.Country,
		arg.PreferredCommunicationMethod,
		arg.EmploymentStatus,
		arg.EducationLevel,
		arg.HouseholdIncomeRange,
	)
	return err
}

const validatePatientExists = `-- name: ValidatePatientExists :one
SELECT EXISTS(
    SELECT 1 FROM patient_profiles WHERE user_id = $1
) as exists
`

func (q *Queries) ValidatePatientExists(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, validatePatientExists, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
