// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: professional_credentials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :one


INSERT INTO professional_credentials (
    staff_id, credential_type, credential_number, issuing_authority,
    issue_date, expiry_date, status, verified_by, verification_date,
    document_url, notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, staff_id, credential_type, credential_number, issuing_authority, issue_date, expiry_date, status, verified_by, verification_date, document_url, notes, created_at, updated_at
`

type CreateCredentialParams struct {
	StaffID          pgtype.UUID      `json:"staff_id"`
	CredentialType   string           `json:"credential_type"`
	CredentialNumber pgtype.Text      `json:"credential_number"`
	IssuingAuthority string           `json:"issuing_authority"`
	IssueDate        pgtype.Date      `json:"issue_date"`
	ExpiryDate       pgtype.Date      `json:"expiry_date"`
	Status           pgtype.Text      `json:"status"`
	VerifiedBy       pgtype.UUID      `json:"verified_by"`
	VerificationDate pgtype.Timestamp `json:"verification_date"`
	DocumentUrl      pgtype.Text      `json:"document_url"`
	Notes            pgtype.Text      `json:"notes"`
}

// ============================================
// PROFESSIONAL CREDENTIALS REPOSITORY QUERIES
// Maps to: Part of StaffRepository interface (credential methods)
// Domain: Professional Licensing & Certification Management
// ============================================
// ============================================
// CORE CRUD OPERATIONS
// ============================================
func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (ProfessionalCredential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.StaffID,
		arg.CredentialType,
		arg.CredentialNumber,
		arg.IssuingAuthority,
		arg.IssueDate,
		arg.ExpiryDate,
		arg.Status,
		arg.VerifiedBy,
		arg.VerificationDate,
		arg.DocumentUrl,
		arg.Notes,
	)
	var i ProfessionalCredential
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.CredentialType,
		&i.CredentialNumber,
		&i.IssuingAuthority,
		&i.IssueDate,
		&i.ExpiryDate,
		&i.Status,
		&i.VerifiedBy,
		&i.VerificationDate,
		&i.DocumentUrl,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM professional_credentials 
WHERE id = $1
`

func (q *Queries) DeleteCredential(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCredential, id)
	return err
}

const getCredentialByID = `-- name: GetCredentialByID :one
SELECT id, staff_id, credential_type, credential_number, issuing_authority, issue_date, expiry_date, status, verified_by, verification_date, document_url, notes, created_at, updated_at FROM professional_credentials
WHERE id = $1
`

func (q *Queries) GetCredentialByID(ctx context.Context, id pgtype.UUID) (ProfessionalCredential, error) {
	row := q.db.QueryRow(ctx, getCredentialByID, id)
	var i ProfessionalCredential
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.CredentialType,
		&i.CredentialNumber,
		&i.IssuingAuthority,
		&i.IssueDate,
		&i.ExpiryDate,
		&i.Status,
		&i.VerifiedBy,
		&i.VerificationDate,
		&i.DocumentUrl,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffCredentials = `-- name: GetStaffCredentials :many
SELECT 
    id, staff_id, credential_type, credential_number,
    issuing_authority, issue_date, expiry_date, status,
    verified_by, verification_date, document_url, notes,
    created_at, updated_at
FROM professional_credentials
WHERE staff_id = $1
ORDER BY 
    CASE status
        WHEN 'verified' THEN 1
        WHEN 'pending' THEN 2
        WHEN 'expired' THEN 3
        WHEN 'revoked' THEN 4
        WHEN 'rejected' THEN 5
        ELSE 6
    END,
    expiry_date ASC NULLS LAST,
    issue_date DESC
`

func (q *Queries) GetStaffCredentials(ctx context.Context, staffID pgtype.UUID) ([]ProfessionalCredential, error) {
	rows, err := q.db.Query(ctx, getStaffCredentials, staffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfessionalCredential{}
	for rows.Next() {
		var i ProfessionalCredential
		if err := rows.Scan(
			&i.ID,
			&i.StaffID,
			&i.CredentialType,
			&i.CredentialNumber,
			&i.IssuingAuthority,
			&i.IssueDate,
			&i.ExpiryDate,
			&i.Status,
			&i.VerifiedBy,
			&i.VerificationDate,
			&i.DocumentUrl,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredential = `-- name: UpdateCredential :exec
UPDATE professional_credentials
SET 
    credential_type = COALESCE($2, credential_type),
    credential_number = COALESCE($3, credential_number),
    issuing_authority = COALESCE($4, issuing_authority),
    issue_date = COALESCE($5, issue_date),
    expiry_date = COALESCE($6, expiry_date),
    status = COALESCE($7, status),
    document_url = COALESCE($8, document_url),
    notes = COALESCE($9, notes),
    updated_at = NOW()
WHERE id = $1
`

type UpdateCredentialParams struct {
	ID               pgtype.UUID `json:"id"`
	CredentialType   string      `json:"credential_type"`
	CredentialNumber pgtype.Text `json:"credential_number"`
	IssuingAuthority string      `json:"issuing_authority"`
	IssueDate        pgtype.Date `json:"issue_date"`
	ExpiryDate       pgtype.Date `json:"expiry_date"`
	Status           pgtype.Text `json:"status"`
	DocumentUrl      pgtype.Text `json:"document_url"`
	Notes            pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error {
	_, err := q.db.Exec(ctx, updateCredential,
		arg.ID,
		arg.CredentialType,
		arg.CredentialNumber,
		arg.IssuingAuthority,
		arg.IssueDate,
		arg.ExpiryDate,
		arg.Status,
		arg.DocumentUrl,
		arg.Notes,
	)
	return err
}
