// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_availability.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const decrementActiveConsultations = `-- name: DecrementActiveConsultations :exec
UPDATE provider_availability
SET
    active_consultation_count = GREATEST(active_consultation_count - 1, 0),
    status = CASE
        WHEN is_accepting AND GREATEST(active_consultation_count - 1, 0) < max_concurrent_consultations
            THEN 'available'
        WHEN NOT is_accepting
            THEN 'away'
        ELSE status
    END,
    updated_at = NOW()
WHERE staff_id = $1
`

// Called when a consultation closes (completed / cancelled / no_show).
func (q *Queries) DecrementActiveConsultations(ctx context.Context, staffID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, decrementActiveConsultations, staffID)
	return err
}

const getAvailabilityByStaffID = `-- name: GetAvailabilityByStaffID :one

SELECT id, staff_id, is_online, is_accepting, status, active_consultation_count, max_concurrent_consultations, estimated_wait_minutes, status_message, consultation_fee_override, last_seen_at, shift_start, updated_at FROM provider_availability
WHERE staff_id = $1
`

// ============================================
// PROVIDER-FACING SELF-READS
// ============================================
func (q *Queries) GetAvailabilityByStaffID(ctx context.Context, staffID pgtype.UUID) (ProviderAvailability, error) {
	row := q.db.QueryRow(ctx, getAvailabilityByStaffID, staffID)
	var i ProviderAvailability
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.IsOnline,
		&i.IsAccepting,
		&i.Status,
		&i.ActiveConsultationCount,
		&i.MaxConcurrentConsultations,
		&i.EstimatedWaitMinutes,
		&i.StatusMessage,
		&i.ConsultationFeeOverride,
		&i.LastSeenAt,
		&i.ShiftStart,
		&i.UpdatedAt,
	)
	return i, err
}

const getAvailableProviders = `-- name: GetAvailableProviders :many

SELECT
    pa.staff_id,
    pa.status,
    pa.estimated_wait_minutes,
    pa.active_consultation_count,
    pa.max_concurrent_consultations,
    pa.consultation_fee_override,
    pa.status_message,

    cs.title,
    cs.first_name,
    cs.last_name,
    cs.professional_title,
    cs.specialization,
    cs.bio,
    cs.profile_picture_url,
    cs.years_experience,
    cs.languages_spoken
FROM provider_availability pa
JOIN clinic_staff cs ON cs.id = pa.staff_id
WHERE
    pa.is_accepting = true
    AND pa.is_online = true
    AND pa.active_consultation_count < pa.max_concurrent_consultations
    AND cs.employment_status = 'active'
    AND ($1::uuid IS NULL OR cs.clinic_id = $1)   -- optional clinic filter
ORDER BY
    pa.estimated_wait_minutes ASC NULLS LAST,
    pa.active_consultation_count ASC
`

type GetAvailableProvidersRow struct {
	StaffID                    pgtype.UUID    `json:"staff_id"`
	Status                     string         `json:"status"`
	EstimatedWaitMinutes       pgtype.Int4    `json:"estimated_wait_minutes"`
	ActiveConsultationCount    int32          `json:"active_consultation_count"`
	MaxConcurrentConsultations int32          `json:"max_concurrent_consultations"`
	ConsultationFeeOverride    pgtype.Numeric `json:"consultation_fee_override"`
	StatusMessage              pgtype.Text    `json:"status_message"`
	Title                      pgtype.Text    `json:"title"`
	FirstName                  string         `json:"first_name"`
	LastName                   string         `json:"last_name"`
	ProfessionalTitle          pgtype.Text    `json:"professional_title"`
	Specialization             pgtype.Text    `json:"specialization"`
	Bio                        pgtype.Text    `json:"bio"`
	ProfilePictureUrl          pgtype.Text    `json:"profile_picture_url"`
	YearsExperience            pgtype.Int4    `json:"years_experience"`
	LanguagesSpoken            []string       `json:"languages_spoken"`
}

// ============================================
// PROVIDER LIST (Patient-facing)
// ============================================
// Powers ProvidersList.jsx — only providers who are accepting AND have capacity.
func (q *Queries) GetAvailableProviders(ctx context.Context, dollar_1 pgtype.UUID) ([]GetAvailableProvidersRow, error) {
	rows, err := q.db.Query(ctx, getAvailableProviders, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAvailableProvidersRow{}
	for rows.Next() {
		var i GetAvailableProvidersRow
		if err := rows.Scan(
			&i.StaffID,
			&i.Status,
			&i.EstimatedWaitMinutes,
			&i.ActiveConsultationCount,
			&i.MaxConcurrentConsultations,
			&i.ConsultationFeeOverride,
			&i.StatusMessage,
			&i.Title,
			&i.FirstName,
			&i.LastName,
			&i.ProfessionalTitle,
			&i.Specialization,
			&i.Bio,
			&i.ProfilePictureUrl,
			&i.YearsExperience,
			&i.LanguagesSpoken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableProvidersBySpecialization = `-- name: GetAvailableProvidersBySpecialization :many
SELECT
    pa.staff_id,
    pa.status,
    pa.estimated_wait_minutes,
    pa.consultation_fee_override,
    cs.first_name,
    cs.last_name,
    cs.professional_title,
    cs.specialization,
    cs.profile_picture_url,
    cs.years_experience
FROM provider_availability pa
JOIN clinic_staff cs ON cs.id = pa.staff_id
WHERE
    pa.is_accepting = true
    AND pa.is_online = true
    AND pa.active_consultation_count < pa.max_concurrent_consultations
    AND cs.employment_status = 'active'
    AND cs.specialization ILIKE '%' || $1 || '%'
ORDER BY pa.estimated_wait_minutes ASC NULLS LAST
`

type GetAvailableProvidersBySpecializationRow struct {
	StaffID                 pgtype.UUID    `json:"staff_id"`
	Status                  string         `json:"status"`
	EstimatedWaitMinutes    pgtype.Int4    `json:"estimated_wait_minutes"`
	ConsultationFeeOverride pgtype.Numeric `json:"consultation_fee_override"`
	FirstName               string         `json:"first_name"`
	LastName                string         `json:"last_name"`
	ProfessionalTitle       pgtype.Text    `json:"professional_title"`
	Specialization          pgtype.Text    `json:"specialization"`
	ProfilePictureUrl       pgtype.Text    `json:"profile_picture_url"`
	YearsExperience         pgtype.Int4    `json:"years_experience"`
}

// Filtered version: patient requests a specific specialty.
func (q *Queries) GetAvailableProvidersBySpecialization(ctx context.Context, dollar_1 pgtype.Text) ([]GetAvailableProvidersBySpecializationRow, error) {
	rows, err := q.db.Query(ctx, getAvailableProvidersBySpecialization, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAvailableProvidersBySpecializationRow{}
	for rows.Next() {
		var i GetAvailableProvidersBySpecializationRow
		if err := rows.Scan(
			&i.StaffID,
			&i.Status,
			&i.EstimatedWaitMinutes,
			&i.ConsultationFeeOverride,
			&i.FirstName,
			&i.LastName,
			&i.ProfessionalTitle,
			&i.Specialization,
			&i.ProfilePictureUrl,
			&i.YearsExperience,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaleProviders = `-- name: GetStaleProviders :many

SELECT staff_id
FROM provider_availability
WHERE
    is_online    = true
    AND last_seen_at < NOW() - INTERVAL '2 minutes'
`

// ============================================
// BACKGROUND JOB QUERIES
// ============================================
// Background job: find providers whose heartbeat hasn't been seen in 2 minutes.
// Used to auto-set them offline so patients don't wait for a ghost provider.
func (q *Queries) GetStaleProviders(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getStaleProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var staff_id pgtype.UUID
		if err := rows.Scan(&staff_id); err != nil {
			return nil, err
		}
		items = append(items, staff_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const goOffline = `-- name: GoOffline :exec
UPDATE provider_availability
SET
    is_online    = false,
    is_accepting = false,
    status       = 'offline',
    shift_start  = NULL,
    updated_at   = NOW()
WHERE staff_id = $1
`

// Provider closes dashboard or session expires.
func (q *Queries) GoOffline(ctx context.Context, staffID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, goOffline, staffID)
	return err
}

const goOnline = `-- name: GoOnline :one

UPDATE provider_availability
SET
    is_online   = true,
    shift_start = COALESCE(shift_start, NOW()),
    last_seen_at = NOW(),
    updated_at  = NOW()
WHERE staff_id = $1
RETURNING id, staff_id, is_online, is_accepting, status, active_consultation_count, max_concurrent_consultations, estimated_wait_minutes, status_message, consultation_fee_override, last_seen_at, shift_start, updated_at
`

// ============================================
// STATUS TRANSITIONS
// ============================================
// Provider opens their dashboard.
func (q *Queries) GoOnline(ctx context.Context, staffID pgtype.UUID) (ProviderAvailability, error) {
	row := q.db.QueryRow(ctx, goOnline, staffID)
	var i ProviderAvailability
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.IsOnline,
		&i.IsAccepting,
		&i.Status,
		&i.ActiveConsultationCount,
		&i.MaxConcurrentConsultations,
		&i.EstimatedWaitMinutes,
		&i.StatusMessage,
		&i.ConsultationFeeOverride,
		&i.LastSeenAt,
		&i.ShiftStart,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementActiveConsultations = `-- name: IncrementActiveConsultations :one

UPDATE provider_availability
SET
    active_consultation_count = active_consultation_count + 1,
    status = CASE
        WHEN active_consultation_count + 1 >= max_concurrent_consultations THEN 'busy'
        ELSE 'available'
    END,
    updated_at = NOW()
WHERE
    staff_id = $1
    AND active_consultation_count < max_concurrent_consultations
RETURNING id, staff_id, is_online, is_accepting, status, active_consultation_count, max_concurrent_consultations, estimated_wait_minutes, status_message, consultation_fee_override, last_seen_at, shift_start, updated_at
`

// ============================================
// CONCURRENCY COUNTERS
// ============================================
// Called atomically when a provider accepts a consultation.
// Returns the updated row so the service layer can enforce the cap.
func (q *Queries) IncrementActiveConsultations(ctx context.Context, staffID pgtype.UUID) (ProviderAvailability, error) {
	row := q.db.QueryRow(ctx, incrementActiveConsultations, staffID)
	var i ProviderAvailability
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.IsOnline,
		&i.IsAccepting,
		&i.Status,
		&i.ActiveConsultationCount,
		&i.MaxConcurrentConsultations,
		&i.EstimatedWaitMinutes,
		&i.StatusMessage,
		&i.ConsultationFeeOverride,
		&i.LastSeenAt,
		&i.ShiftStart,
		&i.UpdatedAt,
	)
	return i, err
}

const setAccepting = `-- name: SetAccepting :one
UPDATE provider_availability
SET
    is_accepting          = $2,
    status                = CASE WHEN $2 THEN 'available' ELSE 'away' END,
    consultation_fee_override = COALESCE($3, consultation_fee_override),
    estimated_wait_minutes    = COALESCE($4, estimated_wait_minutes),
    updated_at            = NOW()
WHERE staff_id = $1
RETURNING id, staff_id, is_online, is_accepting, status, active_consultation_count, max_concurrent_consultations, estimated_wait_minutes, status_message, consultation_fee_override, last_seen_at, shift_start, updated_at
`

type SetAcceptingParams struct {
	StaffID                 pgtype.UUID    `json:"staff_id"`
	IsAccepting             bool           `json:"is_accepting"`
	ConsultationFeeOverride pgtype.Numeric `json:"consultation_fee_override"`
	EstimatedWaitMinutes    pgtype.Int4    `json:"estimated_wait_minutes"`
}

// Provider toggles "Start Accepting" in their UI.
func (q *Queries) SetAccepting(ctx context.Context, arg SetAcceptingParams) (ProviderAvailability, error) {
	row := q.db.QueryRow(ctx, setAccepting,
		arg.StaffID,
		arg.IsAccepting,
		arg.ConsultationFeeOverride,
		arg.EstimatedWaitMinutes,
	)
	var i ProviderAvailability
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.IsOnline,
		&i.IsAccepting,
		&i.Status,
		&i.ActiveConsultationCount,
		&i.MaxConcurrentConsultations,
		&i.EstimatedWaitMinutes,
		&i.StatusMessage,
		&i.ConsultationFeeOverride,
		&i.LastSeenAt,
		&i.ShiftStart,
		&i.UpdatedAt,
	)
	return i, err
}

const setMaxConcurrent = `-- name: SetMaxConcurrent :exec
UPDATE provider_availability
SET
    max_concurrent_consultations = $2,
    updated_at = NOW()
WHERE staff_id = $1
`

type SetMaxConcurrentParams struct {
	StaffID                    pgtype.UUID `json:"staff_id"`
	MaxConcurrentConsultations int32       `json:"max_concurrent_consultations"`
}

func (q *Queries) SetMaxConcurrent(ctx context.Context, arg SetMaxConcurrentParams) error {
	_, err := q.db.Exec(ctx, setMaxConcurrent, arg.StaffID, arg.MaxConcurrentConsultations)
	return err
}

const setStaleProvidersOffline = `-- name: SetStaleProvidersOffline :exec
UPDATE provider_availability
SET
    is_online    = false,
    is_accepting = false,
    status       = 'offline',
    shift_start  = NULL,
    updated_at   = NOW()
WHERE
    is_online    = true
    AND last_seen_at < NOW() - INTERVAL '2 minutes'
`

// Companion to GetStaleProviders — runs in same background job.
func (q *Queries) SetStaleProvidersOffline(ctx context.Context) error {
	_, err := q.db.Exec(ctx, setStaleProvidersOffline)
	return err
}

const updateHeartbeat = `-- name: UpdateHeartbeat :exec
UPDATE provider_availability
SET last_seen_at = NOW()
WHERE staff_id = $1
`

// Provider dashboard pings every 30 s. If last_seen_at is stale (> 2 min),
// a background job sets the provider offline.
func (q *Queries) UpdateHeartbeat(ctx context.Context, staffID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateHeartbeat, staffID)
	return err
}

const updateStatus = `-- name: UpdateStatus :exec
UPDATE provider_availability
SET
    status         = $2,
    status_message = $3,
    updated_at     = NOW()
WHERE staff_id = $1
`

type UpdateStatusParams struct {
	StaffID       pgtype.UUID `json:"staff_id"`
	Status        string      `json:"status"`
	StatusMessage pgtype.Text `json:"status_message"`
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) error {
	_, err := q.db.Exec(ctx, updateStatus, arg.StaffID, arg.Status, arg.StatusMessage)
	return err
}

const updateWaitTime = `-- name: UpdateWaitTime :exec
UPDATE provider_availability
SET
    estimated_wait_minutes = $2,
    updated_at             = NOW()
WHERE staff_id = $1
`

type UpdateWaitTimeParams struct {
	StaffID              pgtype.UUID `json:"staff_id"`
	EstimatedWaitMinutes pgtype.Int4 `json:"estimated_wait_minutes"`
}

// Provider manually adjusts their estimated wait time shown to patients.
func (q *Queries) UpdateWaitTime(ctx context.Context, arg UpdateWaitTimeParams) error {
	_, err := q.db.Exec(ctx, updateWaitTime, arg.StaffID, arg.EstimatedWaitMinutes)
	return err
}

const upsertProviderAvailability = `-- name: UpsertProviderAvailability :one

INSERT INTO provider_availability (staff_id)
VALUES ($1)
ON CONFLICT (staff_id) DO UPDATE
    SET updated_at = NOW()
RETURNING id, staff_id, is_online, is_accepting, status, active_consultation_count, max_concurrent_consultations, estimated_wait_minutes, status_message, consultation_fee_override, last_seen_at, shift_start, updated_at
`

// ============================================
// UPSERT / INITIALISE
// ============================================
// Creates a row on first login, updates on subsequent calls.
func (q *Queries) UpsertProviderAvailability(ctx context.Context, staffID pgtype.UUID) (ProviderAvailability, error) {
	row := q.db.QueryRow(ctx, upsertProviderAvailability, staffID)
	var i ProviderAvailability
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.IsOnline,
		&i.IsAccepting,
		&i.Status,
		&i.ActiveConsultationCount,
		&i.MaxConcurrentConsultations,
		&i.EstimatedWaitMinutes,
		&i.StatusMessage,
		&i.ConsultationFeeOverride,
		&i.LastSeenAt,
		&i.ShiftStart,
		&i.UpdatedAt,
	)
	return i, err
}
