// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ============================================
	// SERVICE STATUS MANAGEMENT
	// ============================================
	ActivateService(ctx context.Context, id pgtype.UUID) error
	ActivateStaff(ctx context.Context, id pgtype.UUID) error
	// ============================================
	// PATIENT ALLERGIES REPOSITORY QUERIES
	// Maps to: Part of PatientRepository interface
	// Domain: Patient Allergy Management
	// ============================================
	// ============================================
	// CORE CRUD OPERATIONS
	// ============================================
	AddPatientAllergy(ctx context.Context, arg AddPatientAllergyParams) (PatientAllergy, error)
	// ============================================
	// PATIENT CONDITIONS REPOSITORY QUERIES
	// Maps to: Part of PatientRepository interface
	// Domain: Patient Medical Conditions Management
	// ============================================
	// ============================================
	// CORE CRUD OPERATIONS
	// ============================================
	AddPatientCondition(ctx context.Context, arg AddPatientConditionParams) (PatientCondition, error)
	// ============================================
	// PATIENT IMMUNIZATIONS REPOSITORY QUERIES
	// Maps to: Part of PatientRepository interface
	// Domain: Patient Immunization & Vaccination Management
	// ============================================
	// ============================================
	// CORE CRUD OPERATIONS
	// ============================================
	AddPatientImmunization(ctx context.Context, arg AddPatientImmunizationParams) (PatientImmunization, error)
	// ============================================
	// PATIENT MEDICATIONS REPOSITORY QUERIES
	// Maps to: Part of PatientRepository interface
	// Domain: Patient Medication Management
	// ============================================
	// ============================================
	// CORE CRUD OPERATIONS
	// ============================================
	AddPatientMedication(ctx context.Context, arg AddPatientMedicationParams) (PatientMedication, error)
	AddStaffQualification(ctx context.Context, arg AddStaffQualificationParams) error
	AddStaffToService(ctx context.Context, arg AddStaffToServiceParams) error
	AdvancedPatientSearch(ctx context.Context, arg AdvancedPatientSearchParams) ([]AdvancedPatientSearchRow, error)
	AutoExpireCredentials(ctx context.Context) error
	BulkActivateServices(ctx context.Context, dollar_1 []pgtype.UUID) error
	BulkDeactivateServices(ctx context.Context, dollar_1 []pgtype.UUID) error
	BulkRejectCredentials(ctx context.Context, arg BulkRejectCredentialsParams) error
	BulkSetAcceptingPatients(ctx context.Context, arg BulkSetAcceptingPatientsParams) error
	BulkUpdateAllergyStatus(ctx context.Context, arg BulkUpdateAllergyStatusParams) error
	BulkUpdateCommunicationMethod(ctx context.Context, arg BulkUpdateCommunicationMethodParams) error
	BulkUpdateConditionStatus(ctx context.Context, arg BulkUpdateConditionStatusParams) error
	BulkUpdateCredentialStatus(ctx context.Context, arg BulkUpdateCredentialStatusParams) error
	BulkUpdateHealthStatus(ctx context.Context, arg BulkUpdateHealthStatusParams) error
	BulkUpdateMarketingConsent(ctx context.Context, arg BulkUpdateMarketingConsentParams) error
	BulkUpdateMedicalAidStatus(ctx context.Context, arg BulkUpdateMedicalAidStatusParams) error
	BulkUpdateMedicationStatus(ctx context.Context, arg BulkUpdateMedicationStatusParams) error
	BulkUpdatePatientProvince(ctx context.Context, arg BulkUpdatePatientProvinceParams) error
	BulkUpdateServiceCategory(ctx context.Context, arg BulkUpdateServiceCategoryParams) error
	BulkUpdateStaffStatus(ctx context.Context, arg BulkUpdateStaffStatusParams) error
	BulkUpdateUserStatus(ctx context.Context, arg BulkUpdateUserStatusParams) error
	BulkUpdateVerificationStatus(ctx context.Context, arg BulkUpdateVerificationStatusParams) error
	BulkVerifyClinics(ctx context.Context, arg BulkVerifyClinicsParams) error
	BulkVerifyCredentials(ctx context.Context, arg BulkVerifyCredentialsParams) error
	// ============================================
	// VALIDATION & UTILITIES
	// ============================================
	CheckAllergyExists(ctx context.Context, arg CheckAllergyExistsParams) (bool, error)
	CheckConditionExists(ctx context.Context, arg CheckConditionExistsParams) (bool, error)
	CheckCredentialNumberExists(ctx context.Context, arg CheckCredentialNumberExistsParams) (bool, error)
	CheckEmailExists(ctx context.Context, arg CheckEmailExistsParams) (bool, error)
	CheckHPCSNumberExists(ctx context.Context, arg CheckHPCSNumberExistsParams) (bool, error)
	CheckMedicalAidNumberExists(ctx context.Context, arg CheckMedicalAidNumberExistsParams) (bool, error)
	// ============================================
	// VALIDATION & UTILITIES
	// ============================================
	CheckMedicationConflict(ctx context.Context, arg CheckMedicationConflictParams) (bool, error)
	CheckNationalIDExists(ctx context.Context, arg CheckNationalIDExistsParams) (bool, error)
	CheckPhoneExists(ctx context.Context, arg CheckPhoneExistsParams) (bool, error)
	CheckRegistrationNumberExists(ctx context.Context, arg CheckRegistrationNumberExistsParams) (bool, error)
	CheckServiceNameExists(ctx context.Context, arg CheckServiceNameExistsParams) (bool, error)
	CheckStaffEmailExists(ctx context.Context, arg CheckStaffEmailExistsParams) (bool, error)
	CheckUserStaffExists(ctx context.Context, userID pgtype.UUID) (bool, error)
	// ============================================
	// VALIDATION & UTILITIES
	// ============================================
	CheckVaccineReceived(ctx context.Context, arg CheckVaccineReceivedParams) (bool, error)
	ClinicExists(ctx context.Context, id pgtype.UUID) (bool, error)
	// ============================================
	// COMPARISON & CROSS-CLINIC QUERIES
	// ============================================
	CompareServiceAcrossClinics(ctx context.Context, serviceName string) ([]CompareServiceAcrossClinicsRow, error)
	CompleteMedication(ctx context.Context, id pgtype.UUID) error
	CountActiveConsents(ctx context.Context) (int64, error)
	// ============================================
	// COUNTING & EXISTENCE CHECKS
	// ============================================
	CountClinicServices(ctx context.Context, arg CountClinicServicesParams) (int64, error)
	// ============================================
	// COUNTING & EXISTENCE CHECKS
	// ============================================
	CountClinicStaff(ctx context.Context, arg CountClinicStaffParams) (int64, error)
	// ============================================
	// COUNTING & EXISTENCE CHECKS
	// ============================================
	CountClinics(ctx context.Context, arg CountClinicsParams) (int64, error)
	CountClinicsByProvince(ctx context.Context, province pgtype.Text) (int64, error)
	CountConsentsByType(ctx context.Context) (CountConsentsByTypeRow, error)
	CountCredentialsByType(ctx context.Context, arg CountCredentialsByTypeParams) (int64, error)
	// ============================================
	// STATISTICS & ANALYTICS
	// ============================================
	CountPatientAllergies(ctx context.Context, patientID pgtype.UUID) (CountPatientAllergiesRow, error)
	// ============================================
	// STATISTICS & ANALYTICS
	// ============================================
	CountPatientConditions(ctx context.Context, patientID pgtype.UUID) (CountPatientConditionsRow, error)
	// ============================================
	// STATISTICS & ANALYTICS
	// ============================================
	CountPatientImmunizations(ctx context.Context, patientID pgtype.UUID) (CountPatientImmunizationsRow, error)
	// ============================================
	// STATISTICS & ANALYTICS
	// ============================================
	CountPatientMedications(ctx context.Context, patientID pgtype.UUID) (CountPatientMedicationsRow, error)
	CountPatientsByCity(ctx context.Context, arg CountPatientsByCityParams) ([]CountPatientsByCityRow, error)
	CountPatientsByCommunicationMethod(ctx context.Context) (CountPatientsByCommunicationMethodRow, error)
	CountPatientsByGender(ctx context.Context) (CountPatientsByGenderRow, error)
	CountPatientsByMedicalAidProvider(ctx context.Context) ([]CountPatientsByMedicalAidProviderRow, error)
	CountPatientsByMedicalAidStatus(ctx context.Context) (CountPatientsByMedicalAidStatusRow, error)
	// ============================================
	// STATISTICS & ANALYTICS
	// ============================================
	CountPatientsByProvince(ctx context.Context) ([]CountPatientsByProvinceRow, error)
	CountServicesByCategory(ctx context.Context, arg CountServicesByCategoryParams) (int64, error)
	CountStaffByRole(ctx context.Context, arg CountStaffByRoleParams) (int64, error)
	// ============================================
	// COUNTING & EXISTENCE CHECKS
	// ============================================
	CountStaffCredentials(ctx context.Context, arg CountStaffCredentialsParams) (int64, error)
	CountUsersByRole(ctx context.Context, role string) (int64, error)
	CountVerifiedClinics(ctx context.Context) (int64, error)
	// ============================================
	// CLINIC REPOSITORY QUERIES
	// Maps to: ClinicRepository interface
	// Domain: Healthcare Provider Management
	// ============================================
	// ============================================
	// CORE CRUD OPERATIONS
	// ============================================
	CreateClinic(ctx context.Context, arg CreateClinicParams) (Clinic, error)
	// ============================================
	// CLINIC SERVICES REPOSITORY QUERIES
	// Maps to: Part of ClinicRepository interface (service-related methods)
	// Domain: Healthcare Service Management
	// ============================================
	// ============================================
	// CORE CRUD OPERATIONS
	// ============================================
	CreateClinicService(ctx context.Context, arg CreateClinicServiceParams) (ClinicService, error)
	// ============================================
	// PROFESSIONAL CREDENTIALS REPOSITORY QUERIES
	// Maps to: Part of StaffRepository interface (credential methods)
	// Domain: Professional Licensing & Certification Management
	// ============================================
	// ============================================
	// CORE CRUD OPERATIONS
	// ============================================
	CreateCredential(ctx context.Context, arg CreateCredentialParams) (ProfessionalCredential, error)
	// ============================================
	// Notification Preferences Queries
	// ============================================
	CreateNotificationPreferences(ctx context.Context, arg CreateNotificationPreferencesParams) (CreateNotificationPreferencesRow, error)
	// ============================================
	// PATIENT MEDICAL INFO REPOSITORY QUERIES
	// Maps to: Part of PatientRepository interface
	// Domain: Patient Medical & Health Information Management
	// ============================================
	// ============================================
	// CORE CRUD OPERATIONS
	// ============================================
	CreatePatientMedicalInfo(ctx context.Context, arg CreatePatientMedicalInfoParams) (PatientMedicalInfo, error)
	// ============================================
	// PATIENT PROFILE REPOSITORY QUERIES
	// Maps to: PatientProfileRepository interface
	// Domain: Patient Profile & Demographics Management
	// ============================================
	// ============================================
	// CORE CRUD OPERATIONS
	// ============================================
	CreatePatientProfile(ctx context.Context, arg CreatePatientProfileParams) (PatientProfile, error)
	// ============================================
	// Privacy Consent Queries (POPIA Compliance)
	// ============================================
	CreatePrivacyConsent(ctx context.Context, arg CreatePrivacyConsentParams) (CreatePrivacyConsentRow, error)
	// ============================================
	// SMS Conversation Queries
	// ============================================
	CreateSMSConversation(ctx context.Context, arg CreateSMSConversationParams) (CreateSMSConversationRow, error)
	// Session Management Queries
	CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error)
	// ============================================
	// CLINIC STAFF REPOSITORY QUERIES
	// Maps to: StaffRepository interface
	// Domain: Healthcare Staff Management
	// ============================================
	// ============================================
	// CORE CRUD OPERATIONS
	// ============================================
	CreateStaffMember(ctx context.Context, arg CreateStaffMemberParams) (ClinicStaff, error)
	// User Management Queries
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CredentialExists(ctx context.Context, id pgtype.UUID) (bool, error)
	DeactivateClinic(ctx context.Context, id pgtype.UUID) error
	DeactivateClinicServices(ctx context.Context, clinicID pgtype.UUID) error
	DeactivateClinicStaff(ctx context.Context, clinicID pgtype.UUID) error
	DeactivateService(ctx context.Context, id pgtype.UUID) error
	DeactivateStaff(ctx context.Context, id pgtype.UUID) error
	DeleteAllSessionsExcept(ctx context.Context, arg DeleteAllSessionsExceptParams) error
	DeleteClinic(ctx context.Context, id pgtype.UUID) error
	DeleteClinicService(ctx context.Context, id pgtype.UUID) error
	DeleteCredential(ctx context.Context, id pgtype.UUID) error
	DeleteExpiredOTPs(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteNotificationPreferences(ctx context.Context, userID pgtype.UUID) error
	DeleteOldDataAccessLogs(ctx context.Context, accessedAt pgtype.Timestamp) error
	DeleteOldUserActivities(ctx context.Context, performedAt pgtype.Timestamp) error
	DeletePatientAllergies(ctx context.Context, patientID pgtype.UUID) error
	DeletePatientAllergy(ctx context.Context, id pgtype.UUID) error
	DeletePatientCondition(ctx context.Context, id pgtype.UUID) error
	DeletePatientConditions(ctx context.Context, patientID pgtype.UUID) error
	DeletePatientImmunization(ctx context.Context, id pgtype.UUID) error
	DeletePatientImmunizations(ctx context.Context, patientID pgtype.UUID) error
	DeletePatientMedicalInfo(ctx context.Context, patientID pgtype.UUID) error
	DeletePatientMedication(ctx context.Context, id pgtype.UUID) error
	DeletePatientMedications(ctx context.Context, patientID pgtype.UUID) error
	DeletePatientProfile(ctx context.Context, id pgtype.UUID) error
	DeletePatientProfileByUserID(ctx context.Context, userID pgtype.UUID) error
	DeletePrivacyConsent(ctx context.Context, userID pgtype.UUID) error
	DeleteSession(ctx context.Context, sessionToken string) error
	DeleteSessionByDevice(ctx context.Context, arg DeleteSessionByDeviceParams) error
	DeleteStaffCredentials(ctx context.Context, staffID pgtype.UUID) error
	DeleteStaffMember(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	DeleteUserOTPs(ctx context.Context, arg DeleteUserOTPsParams) error
	DeleteUserSessions(ctx context.Context, userID pgtype.UUID) error
	DiscontinueMedication(ctx context.Context, arg DiscontinueMedicationParams) error
	ExportDataAccessLogs(ctx context.Context, arg ExportDataAccessLogsParams) ([]DataAccessLog, error)
	ExportPatientBasicInfo(ctx context.Context, userID pgtype.UUID) (ExportPatientBasicInfoRow, error)
	// ============================================
	// DATA EXPORT & COMPLIANCE
	// ============================================
	ExportPatientData(ctx context.Context, userID pgtype.UUID) ([]byte, error)
	ExportUserActivities(ctx context.Context, arg ExportUserActivitiesParams) ([]UserActivity, error)
	GetAcceptingNewPatientsStaff(ctx context.Context, clinicID pgtype.UUID) ([]GetAcceptingNewPatientsStaffRow, error)
	GetAccessLogsByAccessedByUser(ctx context.Context, arg GetAccessLogsByAccessedByUserParams) ([]DataAccessLog, error)
	GetActiveClinicServices(ctx context.Context, clinicID pgtype.UUID) ([]GetActiveClinicServicesRow, error)
	GetActiveClinicStaff(ctx context.Context, clinicID pgtype.UUID) ([]GetActiveClinicStaffRow, error)
	GetActiveConditions(ctx context.Context, patientID pgtype.UUID) ([]GetActiveConditionsRow, error)
	GetActiveEmergencyAccessConsents(ctx context.Context) ([]PrivacyConsent, error)
	GetActiveHealthDataConsents(ctx context.Context) ([]PrivacyConsent, error)
	GetActiveMedicationCount(ctx context.Context, patientID pgtype.UUID) (int64, error)
	GetActiveMedications(ctx context.Context, patientID pgtype.UUID) ([]GetActiveMedicationsRow, error)
	GetActivePatientAllergies(ctx context.Context, patientID pgtype.UUID) ([]GetActivePatientAllergiesRow, error)
	GetActiveResearchConsents(ctx context.Context) ([]PrivacyConsent, error)
	GetActiveStaffCredentials(ctx context.Context, staffID pgtype.UUID) ([]GetActiveStaffCredentialsRow, error)
	GetActivitiesByResource(ctx context.Context, arg GetActivitiesByResourceParams) ([]UserActivity, error)
	GetActivitiesByType(ctx context.Context, arg GetActivitiesByTypeParams) ([]UserActivity, error)
	GetAcuteConditions(ctx context.Context, patientID pgtype.UUID) ([]GetAcuteConditionsRow, error)
	GetAgeDistribution(ctx context.Context) ([]GetAgeDistributionRow, error)
	GetAllClinicStaff(ctx context.Context, clinicID pgtype.UUID) ([]GetAllClinicStaffRow, error)
	GetAllergiesByDateRange(ctx context.Context, arg GetAllergiesByDateRangeParams) ([]GetAllergiesByDateRangeRow, error)
	// ============================================
	// BULK OPERATIONS
	// ============================================
	GetAllergiesByPatientIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetAllergiesByPatientIDsRow, error)
	GetAllergySeverityDistribution(ctx context.Context) ([]GetAllergySeverityDistributionRow, error)
	GetAllergyStatistics(ctx context.Context) (GetAllergyStatisticsRow, error)
	GetAppointmentOnlyServices(ctx context.Context, clinicID pgtype.UUID) ([]GetAppointmentOnlyServicesRow, error)
	// ============================================
	// HEALTH METRICS & ANALYTICS
	// ============================================
	GetBMIDistribution(ctx context.Context) ([]GetBMIDistributionRow, error)
	GetBloodTypeDistribution(ctx context.Context) ([]GetBloodTypeDistributionRow, error)
	GetCertificationCredentials(ctx context.Context) ([]GetCertificationCredentialsRow, error)
	GetCheapestServiceProviders(ctx context.Context, arg GetCheapestServiceProvidersParams) ([]GetCheapestServiceProvidersRow, error)
	GetChildrenNeedingVaccines(ctx context.Context, arg GetChildrenNeedingVaccinesParams) ([]GetChildrenNeedingVaccinesRow, error)
	GetChronicConditions(ctx context.Context, patientID pgtype.UUID) ([]GetChronicConditionsRow, error)
	GetClinicByEmail(ctx context.Context, email pgtype.Text) (Clinic, error)
	GetClinicByID(ctx context.Context, id pgtype.UUID) (Clinic, error)
	GetClinicByPhone(ctx context.Context, primaryPhone pgtype.Text) (Clinic, error)
	// ============================================
	// REFERENCE DATA LOOKUPS
	// ============================================
	GetClinicByRegistrationNumber(ctx context.Context, registrationNumber pgtype.Text) (Clinic, error)
	GetClinicCredentialMetrics(ctx context.Context, clinicID pgtype.UUID) (GetClinicCredentialMetricsRow, error)
	GetClinicDoctors(ctx context.Context, clinicID pgtype.UUID) ([]GetClinicDoctorsRow, error)
	GetClinicMetrics(ctx context.Context) (GetClinicMetricsRow, error)
	GetClinicNurses(ctx context.Context, clinicID pgtype.UUID) ([]GetClinicNursesRow, error)
	GetClinicOwnershipDistribution(ctx context.Context) ([]GetClinicOwnershipDistributionRow, error)
	GetClinicPrimaryContact(ctx context.Context, clinicID pgtype.UUID) (GetClinicPrimaryContactRow, error)
	GetClinicProvinceDistribution(ctx context.Context) ([]GetClinicProvinceDistributionRow, error)
	GetClinicServiceMetrics(ctx context.Context, clinicID pgtype.UUID) (GetClinicServiceMetricsRow, error)
	// ============================================
	// QUERYING BY CLINIC
	// ============================================
	GetClinicServices(ctx context.Context, clinicID pgtype.UUID) ([]GetClinicServicesRow, error)
	GetClinicServicesByCategory(ctx context.Context, arg GetClinicServicesByCategoryParams) ([]GetClinicServicesByCategoryRow, error)
	GetClinicServicesByStaff(ctx context.Context, arg GetClinicServicesByStaffParams) ([]GetClinicServicesByStaffRow, error)
	// ============================================
	// CLINIC STAFF MANAGEMENT
	// ============================================
	GetClinicStaff(ctx context.Context, arg GetClinicStaffParams) ([]GetClinicStaffRow, error)
	GetClinicStaffByRole(ctx context.Context, arg GetClinicStaffByRoleParams) ([]GetClinicStaffByRoleRow, error)
	GetClinicStaffMetrics(ctx context.Context, clinicID pgtype.UUID) (GetClinicStaffMetricsRow, error)
	// ============================================
	// STATISTICS & ANALYTICS
	// ============================================
	GetClinicStatistics(ctx context.Context, id pgtype.UUID) (GetClinicStatisticsRow, error)
	GetClinicTypeDistribution(ctx context.Context) ([]GetClinicTypeDistributionRow, error)
	// ============================================
	// MEDICAL AID & PAYMENT
	// ============================================
	GetClinicsAcceptingMedicalAid(ctx context.Context, arg GetClinicsAcceptingMedicalAidParams) ([]GetClinicsAcceptingMedicalAidRow, error)
	GetClinicsByFeeStructure(ctx context.Context, arg GetClinicsByFeeStructureParams) ([]GetClinicsByFeeStructureRow, error)
	// ============================================
	// BULK OPERATIONS
	// ============================================
	GetClinicsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Clinic, error)
	GetClinicsByOwnership(ctx context.Context, arg GetClinicsByOwnershipParams) ([]GetClinicsByOwnershipRow, error)
	GetClinicsByPaymentMethod(ctx context.Context, arg GetClinicsByPaymentMethodParams) ([]GetClinicsByPaymentMethodRow, error)
	GetClinicsByProvince(ctx context.Context, arg GetClinicsByProvinceParams) ([]GetClinicsByProvinceRow, error)
	// ============================================
	// SERVICE-BASED QUERIES
	// ============================================
	GetClinicsByService(ctx context.Context, arg GetClinicsByServiceParams) ([]GetClinicsByServiceRow, error)
	GetClinicsBySpecialty(ctx context.Context, arg GetClinicsBySpecialtyParams) ([]GetClinicsBySpecialtyRow, error)
	GetClinicsByType(ctx context.Context, arg GetClinicsByTypeParams) ([]GetClinicsByTypeRow, error)
	GetClinicsNeedingReaccreditation(ctx context.Context) ([]GetClinicsNeedingReaccreditationRow, error)
	GetClinicsWithExpiredAccreditation(ctx context.Context) ([]GetClinicsWithExpiredAccreditationRow, error)
	GetClinicsWithFacility(ctx context.Context, arg GetClinicsWithFacilityParams) ([]GetClinicsWithFacilityRow, error)
	GetCompleteVaccineSeries(ctx context.Context, patientID pgtype.UUID) ([]GetCompleteVaccineSeriesRow, error)
	GetConditionStatistics(ctx context.Context) (GetConditionStatisticsRow, error)
	GetConditionTypeDistribution(ctx context.Context) ([]GetConditionTypeDistributionRow, error)
	GetConditionsByICD10(ctx context.Context, icd10Code pgtype.Text) ([]GetConditionsByICD10Row, error)
	// ============================================
	// BULK OPERATIONS
	// ============================================
	GetConditionsByPatientIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetConditionsByPatientIDsRow, error)
	GetConditionsByType(ctx context.Context, arg GetConditionsByTypeParams) ([]GetConditionsByTypeRow, error)
	GetConsentByID(ctx context.Context, id pgtype.UUID) (PrivacyConsent, error)
	GetConsentHistory(ctx context.Context, userID pgtype.UUID) ([]PrivacyConsent, error)
	GetConsentsExpiringBefore(ctx context.Context, healthDataConsentDate pgtype.Timestamp) ([]pgtype.UUID, error)
	GetConversationMessages(ctx context.Context, arg GetConversationMessagesParams) ([]GetConversationMessagesRow, error)
	GetCredentialByID(ctx context.Context, id pgtype.UUID) (ProfessionalCredential, error)
	GetCredentialRenewalHistory(ctx context.Context, arg GetCredentialRenewalHistoryParams) ([]GetCredentialRenewalHistoryRow, error)
	// ============================================
	// STATISTICS & ANALYTICS
	// ============================================
	GetCredentialStatistics(ctx context.Context, staffID pgtype.UUID) (GetCredentialStatisticsRow, error)
	GetCredentialStatusDistribution(ctx context.Context, staffID pgtype.UUID) ([]GetCredentialStatusDistributionRow, error)
	GetCredentialTypeDistribution(ctx context.Context, staffID pgtype.UUID) ([]GetCredentialTypeDistributionRow, error)
	// ============================================
	// ISSUING AUTHORITY QUERIES
	// ============================================
	GetCredentialsByAuthority(ctx context.Context, issuingAuthority string) ([]GetCredentialsByAuthorityRow, error)
	GetCredentialsByAuthorityAndType(ctx context.Context, arg GetCredentialsByAuthorityAndTypeParams) ([]GetCredentialsByAuthorityAndTypeRow, error)
	GetCredentialsByDateRange(ctx context.Context, arg GetCredentialsByDateRangeParams) ([]GetCredentialsByDateRangeRow, error)
	// ============================================
	// BULK OPERATIONS
	// ============================================
	GetCredentialsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ProfessionalCredential, error)
	// ============================================
	// CREDENTIAL TYPE QUERIES
	// ============================================
	GetCredentialsByType(ctx context.Context, credentialType string) ([]GetCredentialsByTypeRow, error)
	GetCredentialsExpiringWithinDays(ctx context.Context, dollar_1 pgtype.Text) ([]GetCredentialsExpiringWithinDaysRow, error)
	GetCredentialsNeedingRenewal(ctx context.Context) ([]GetCredentialsNeedingRenewalRow, error)
	GetCriticalAllergyWarnings(ctx context.Context, patientID pgtype.UUID) (GetCriticalAllergyWarningsRow, error)
	GetCriticalPatientInfo(ctx context.Context, patientID pgtype.UUID) (GetCriticalPatientInfoRow, error)
	GetCurrentMedications(ctx context.Context, patientID pgtype.UUID) ([]GetCurrentMedicationsRow, error)
	GetDataAccessLogs(ctx context.Context, arg GetDataAccessLogsParams) ([]DataAccessLog, error)
	GetDegreeCredentials(ctx context.Context) ([]GetDegreeCredentialsRow, error)
	GetEmergencyAccessLogs(ctx context.Context, arg GetEmergencyAccessLogsParams) ([]DataAccessLog, error)
	// ============================================
	// EMERGENCY ACCESS QUERIES
	// ============================================
	GetEmergencyAllergyInfo(ctx context.Context, patientID pgtype.UUID) ([]GetEmergencyAllergyInfoRow, error)
	GetEmergencyConditionInfo(ctx context.Context, patientID pgtype.UUID) ([]GetEmergencyConditionInfoRow, error)
	// ============================================
	// EMERGENCY ACCESS
	// ============================================
	GetEmergencyImmunizationInfo(ctx context.Context, patientID pgtype.UUID) ([]GetEmergencyImmunizationInfoRow, error)
	// ============================================
	// EMERGENCY INFORMATION
	// ============================================
	GetEmergencyMedicalInfo(ctx context.Context, patientID pgtype.UUID) (GetEmergencyMedicalInfoRow, error)
	GetEmergencyMedicationInfo(ctx context.Context, patientID pgtype.UUID) ([]GetEmergencyMedicationInfoRow, error)
	GetExpiredConsents(ctx context.Context) ([]PrivacyConsent, error)
	// ============================================
	// EXPIRATION & RENEWAL MANAGEMENT
	// ============================================
	GetExpiredCredentials(ctx context.Context) ([]GetExpiredCredentialsRow, error)
	GetExpiredCredentialsByClinic(ctx context.Context, clinicID pgtype.UUID) ([]GetExpiredCredentialsByClinicRow, error)
	GetExpiredMedications(ctx context.Context) ([]GetExpiredMedicationsRow, error)
	// ============================================
	// EXPIRATION & REFILL MANAGEMENT
	// ============================================
	GetExpiringMedications(ctx context.Context, endDate pgtype.Date) ([]GetExpiringMedicationsRow, error)
	GetFreeServices(ctx context.Context, clinicID pgtype.UUID) ([]GetFreeServicesRow, error)
	GetHealthStatusDistribution(ctx context.Context) ([]GetHealthStatusDistributionRow, error)
	GetHighRiskPatients(ctx context.Context) ([]GetHighRiskPatientsRow, error)
	// ============================================
	// SEGMENTATION QUERIES
	// ============================================
	GetHighValuePatients(ctx context.Context, arg GetHighValuePatientsParams) ([]GetHighValuePatientsRow, error)
	GetImmunizationCoverage(ctx context.Context) ([]GetImmunizationCoverageRow, error)
	GetImmunizationHistory(ctx context.Context, patientID pgtype.UUID) ([]GetImmunizationHistoryRow, error)
	GetImmunizationRecordsByDateRange(ctx context.Context, arg GetImmunizationRecordsByDateRangeParams) ([]GetImmunizationRecordsByDateRangeRow, error)
	GetImmunizationStatistics(ctx context.Context) (GetImmunizationStatisticsRow, error)
	GetImmunizationsByAdministrator(ctx context.Context, administeredBy pgtype.Text) ([]GetImmunizationsByAdministratorRow, error)
	GetImmunizationsByClinic(ctx context.Context, clinicName pgtype.Text) ([]GetImmunizationsByClinicRow, error)
	GetImmunizationsByLotNumber(ctx context.Context, lotNumber pgtype.Text) ([]GetImmunizationsByLotNumberRow, error)
	// ============================================
	// BULK OPERATIONS
	// ============================================
	GetImmunizationsByPatientIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetImmunizationsByPatientIDsRow, error)
	GetImmunizationsByType(ctx context.Context, arg GetImmunizationsByTypeParams) ([]GetImmunizationsByTypeRow, error)
	// ============================================
	// VACCINE & PROVIDER QUERIES
	// ============================================
	GetImmunizationsByVaccine(ctx context.Context, vaccineName string) ([]GetImmunizationsByVaccineRow, error)
	GetImmunizationsDueInPeriod(ctx context.Context, nextDueDate pgtype.Date) ([]GetImmunizationsDueInPeriodRow, error)
	GetInactivePatients(ctx context.Context, arg GetInactivePatientsParams) ([]GetInactivePatientsRow, error)
	// ============================================
	// COMPLETENESS & DATA QUALITY
	// ============================================
	GetIncompleteMedicalInfo(ctx context.Context, arg GetIncompleteMedicalInfoParams) ([]GetIncompleteMedicalInfoRow, error)
	// ============================================
	// PROFILE COMPLETENESS & QUALITY
	// ============================================
	GetIncompleteProfiles(ctx context.Context, arg GetIncompleteProfilesParams) ([]GetIncompleteProfilesRow, error)
	// ============================================
	// VACCINE SERIES TRACKING
	// ============================================
	GetIncompleteVaccineSeries(ctx context.Context, patientID pgtype.UUID) ([]GetIncompleteVaccineSeriesRow, error)
	GetLanguageDistribution(ctx context.Context) ([]GetLanguageDistributionRow, error)
	GetLastVaccineDate(ctx context.Context, arg GetLastVaccineDateParams) (interface{}, error)
	GetLatestActiveOTP(ctx context.Context, arg GetLatestActiveOTPParams) (OtpVerification, error)
	GetLicenseCredentials(ctx context.Context, dollar_1 pgtype.UUID) ([]GetLicenseCredentialsRow, error)
	GetLifeThreateningAllergies(ctx context.Context, patientID pgtype.UUID) ([]GetLifeThreateningAllergiesRow, error)
	GetLongTermMedications(ctx context.Context) ([]GetLongTermMedicationsRow, error)
	// ============================================
	// MEDICAL AID COVERAGE
	// ============================================
	GetMedicalAidCoveredServices(ctx context.Context, clinicID pgtype.UUID) ([]GetMedicalAidCoveredServicesRow, error)
	// ============================================
	// BULK OPERATIONS
	// ============================================
	GetMedicalInfoByPatientIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]PatientMedicalInfo, error)
	GetMedicalInfoStatistics(ctx context.Context) (GetMedicalInfoStatisticsRow, error)
	GetMedicationHistory(ctx context.Context, patientID pgtype.UUID) ([]GetMedicationHistoryRow, error)
	GetMedicationStatistics(ctx context.Context) (GetMedicationStatisticsRow, error)
	// ============================================
	// BULK OPERATIONS
	// ============================================
	GetMedicationsByPatientIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetMedicationsByPatientIDsRow, error)
	GetMedicationsByPharmacy(ctx context.Context, pharmacyName pgtype.Text) ([]GetMedicationsByPharmacyRow, error)
	// ============================================
	// PRESCRIBER & PHARMACY QUERIES
	// ============================================
	GetMedicationsByPrescriber(ctx context.Context, prescribingDoctor pgtype.Text) ([]GetMedicationsByPrescriberRow, error)
	GetMedicationsByRoute(ctx context.Context, arg GetMedicationsByRouteParams) ([]GetMedicationsByRouteRow, error)
	GetMedicationsWithSideEffects(ctx context.Context) ([]GetMedicationsWithSideEffectsRow, error)
	GetMostCommonAllergies(ctx context.Context, limit int32) ([]GetMostCommonAllergiesRow, error)
	GetMostCommonConditions(ctx context.Context, limit int32) ([]GetMostCommonConditionsRow, error)
	GetMostPopularServices(ctx context.Context, arg GetMostPopularServicesParams) ([]GetMostPopularServicesRow, error)
	GetMostPrescribedMedications(ctx context.Context, limit int32) ([]GetMostPrescribedMedicationsRow, error)
	GetMostReviewedClinics(ctx context.Context, arg GetMostReviewedClinicsParams) ([]GetMostReviewedClinicsRow, error)
	GetMultilingualStaff(ctx context.Context, arg GetMultilingualStaffParams) ([]GetMultilingualStaffRow, error)
	GetNearbyClinicsByService(ctx context.Context, arg GetNearbyClinicsByServiceParams) ([]GetNearbyClinicsByServiceRow, error)
	// ============================================
	// REPORTING QUERIES
	// ============================================
	GetNewPatientsInPeriod(ctx context.Context, arg GetNewPatientsInPeriodParams) ([]GetNewPatientsInPeriodRow, error)
	GetNotificationPreferences(ctx context.Context, userID pgtype.UUID) (NotificationPreference, error)
	GetOTP(ctx context.Context, arg GetOTPParams) (OtpVerification, error)
	GetOTPAttemptCount(ctx context.Context, arg GetOTPAttemptCountParams) (int64, error)
	GetObesePatients(ctx context.Context, arg GetObesePatientsParams) ([]GetObesePatientsRow, error)
	GetOrganDonors(ctx context.Context, arg GetOrganDonorsParams) ([]GetOrganDonorsRow, error)
	GetOverdueCheckups(ctx context.Context) ([]GetOverdueCheckupsRow, error)
	GetOverdueImmunizations(ctx context.Context) ([]GetOverdueImmunizationsRow, error)
	// ============================================
	// BMI & WEIGHT MANAGEMENT QUERIES
	// ============================================
	GetOverweightPatients(ctx context.Context, arg GetOverweightPatientsParams) ([]GetOverweightPatientsRow, error)
	GetPatientAge(ctx context.Context, userID pgtype.UUID) (int32, error)
	// ============================================
	// QUERYING BY PATIENT
	// ============================================
	GetPatientAllergies(ctx context.Context, patientID pgtype.UUID) ([]PatientAllergy, error)
	GetPatientAllergiesByStatus(ctx context.Context, arg GetPatientAllergiesByStatusParams) ([]GetPatientAllergiesByStatusRow, error)
	GetPatientAllergy(ctx context.Context, id pgtype.UUID) (PatientAllergy, error)
	GetPatientAllergyCount(ctx context.Context, patientID pgtype.UUID) (int64, error)
	GetPatientCondition(ctx context.Context, id pgtype.UUID) (PatientCondition, error)
	// ============================================
	// QUERYING BY PATIENT
	// ============================================
	GetPatientConditions(ctx context.Context, arg GetPatientConditionsParams) ([]PatientCondition, error)
	GetPatientDemographicsSummary(ctx context.Context) (GetPatientDemographicsSummaryRow, error)
	GetPatientFullName(ctx context.Context, userID pgtype.UUID) (interface{}, error)
	GetPatientImmunization(ctx context.Context, id pgtype.UUID) (PatientImmunization, error)
	// ============================================
	// QUERYING BY PATIENT
	// ============================================
	GetPatientImmunizations(ctx context.Context, patientID pgtype.UUID) ([]GetPatientImmunizationsRow, error)
	GetPatientMedicalInfo(ctx context.Context, patientID pgtype.UUID) (PatientMedicalInfo, error)
	GetPatientMedicalInfoByID(ctx context.Context, id pgtype.UUID) (PatientMedicalInfo, error)
	GetPatientMedication(ctx context.Context, id pgtype.UUID) (PatientMedication, error)
	// ============================================
	// QUERYING BY PATIENT
	// ============================================
	GetPatientMedications(ctx context.Context, arg GetPatientMedicationsParams) ([]GetPatientMedicationsRow, error)
	GetPatientProfileByID(ctx context.Context, id pgtype.UUID) (PatientProfile, error)
	GetPatientProfileByNationalID(ctx context.Context, nationalIDNumber pgtype.Text) (PatientProfile, error)
	GetPatientProfileByUserID(ctx context.Context, userID pgtype.UUID) (PatientProfile, error)
	GetPatientProfilesByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]PatientProfile, error)
	// ============================================
	// BULK OPERATIONS
	// ============================================
	GetPatientProfilesByUserIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetPatientProfilesByUserIDsRow, error)
	GetPatientRegistrationTrends(ctx context.Context, createdAt pgtype.Timestamp) ([]GetPatientRegistrationTrendsRow, error)
	GetPatientsAcceptingMarketing(ctx context.Context, arg GetPatientsAcceptingMarketingParams) ([]GetPatientsAcceptingMarketingRow, error)
	// ============================================
	// DEMOGRAPHICS & SEGMENTATION
	// ============================================
	GetPatientsByAgeRange(ctx context.Context, arg GetPatientsByAgeRangeParams) ([]GetPatientsByAgeRangeRow, error)
	// ============================================
	// ALLERGY TYPE QUERIES
	// ============================================
	GetPatientsByAllergyName(ctx context.Context, dollar_1 pgtype.Text) ([]GetPatientsByAllergyNameRow, error)
	GetPatientsByBMIRange(ctx context.Context, arg GetPatientsByBMIRangeParams) ([]GetPatientsByBMIRangeRow, error)
	GetPatientsByBloodType(ctx context.Context, bloodType pgtype.Text) ([]GetPatientsByBloodTypeRow, error)
	GetPatientsByCity(ctx context.Context, arg GetPatientsByCityParams) ([]GetPatientsByCityRow, error)
	GetPatientsByCommunicationMethod(ctx context.Context, arg GetPatientsByCommunicationMethodParams) ([]GetPatientsByCommunicationMethodRow, error)
	GetPatientsByCondition(ctx context.Context, dollar_1 pgtype.Text) ([]GetPatientsByConditionRow, error)
	GetPatientsByEducationLevel(ctx context.Context, arg GetPatientsByEducationLevelParams) ([]GetPatientsByEducationLevelRow, error)
	GetPatientsByEmploymentStatus(ctx context.Context, arg GetPatientsByEmploymentStatusParams) ([]GetPatientsByEmploymentStatusRow, error)
	GetPatientsByGender(ctx context.Context, arg GetPatientsByGenderParams) ([]GetPatientsByGenderRow, error)
	GetPatientsByHealthStatus(ctx context.Context, arg GetPatientsByHealthStatusParams) ([]GetPatientsByHealthStatusRow, error)
	GetPatientsByIncomeRange(ctx context.Context, arg GetPatientsByIncomeRangeParams) ([]GetPatientsByIncomeRangeRow, error)
	// ============================================
	// LANGUAGE & COMMUNICATION
	// ============================================
	GetPatientsByLanguage(ctx context.Context, arg GetPatientsByLanguageParams) ([]GetPatientsByLanguageRow, error)
	GetPatientsByMedicalAidProvider(ctx context.Context, arg GetPatientsByMedicalAidProviderParams) ([]GetPatientsByMedicalAidProviderRow, error)
	GetPatientsByMedication(ctx context.Context, dollar_1 pgtype.Text) ([]GetPatientsByMedicationRow, error)
	GetPatientsByPrimaryCarePhysician(ctx context.Context, primaryCarePhysician pgtype.Text) ([]GetPatientsByPrimaryCarePhysicianRow, error)
	GetPatientsByPrimaryClinic(ctx context.Context, primaryClinicID pgtype.UUID) ([]GetPatientsByPrimaryClinicRow, error)
	// ============================================
	// GEOGRAPHIC FILTERING
	// ============================================
	GetPatientsByProvince(ctx context.Context, arg GetPatientsByProvinceParams) ([]GetPatientsByProvinceRow, error)
	GetPatientsByProvinceAndCity(ctx context.Context, arg GetPatientsByProvinceAndCityParams) ([]GetPatientsByProvinceAndCityRow, error)
	GetPatientsByReferralCode(ctx context.Context, referralCode pgtype.Text) ([]GetPatientsByReferralCodeRow, error)
	// ============================================
	// REFERRAL & MARKETING
	// ============================================
	GetPatientsByReferrer(ctx context.Context, arg GetPatientsByReferrerParams) ([]GetPatientsByReferrerRow, error)
	GetPatientsBySeverity(ctx context.Context, severity string) ([]GetPatientsBySeverityRow, error)
	GetPatientsForDataExport(ctx context.Context, arg GetPatientsForDataExportParams) ([]GetPatientsForDataExportRow, error)
	GetPatientsNeedingBloodTypeTest(ctx context.Context, arg GetPatientsNeedingBloodTypeTestParams) ([]GetPatientsNeedingBloodTypeTestRow, error)
	GetPatientsNeedingHealthAssessment(ctx context.Context, arg GetPatientsNeedingHealthAssessmentParams) ([]GetPatientsNeedingHealthAssessmentRow, error)
	// ============================================
	// COMPLIANCE & REPORTING
	// ============================================
	GetPatientsNeedingImmunizations(ctx context.Context) ([]GetPatientsNeedingImmunizationsRow, error)
	GetPatientsNeedingOutreach(ctx context.Context, arg GetPatientsNeedingOutreachParams) ([]GetPatientsNeedingOutreachRow, error)
	// ============================================
	// REPORTING QUERIES
	// ============================================
	GetPatientsOnMultipleMedications(ctx context.Context, dollar_1 interface{}) ([]GetPatientsOnMultipleMedicationsRow, error)
	GetPatientsOptedInMarketing(ctx context.Context, arg GetPatientsOptedInMarketingParams) ([]GetPatientsOptedInMarketingRow, error)
	GetPatientsRequiringInterpreter(ctx context.Context, arg GetPatientsRequiringInterpreterParams) ([]GetPatientsRequiringInterpreterRow, error)
	GetPatientsWithAdvanceDirectives(ctx context.Context) ([]GetPatientsWithAdvanceDirectivesRow, error)
	GetPatientsWithDNR(ctx context.Context) ([]GetPatientsWithDNRRow, error)
	GetPatientsWithLanguagePreference(ctx context.Context, arg GetPatientsWithLanguagePreferenceParams) ([]GetPatientsWithLanguagePreferenceRow, error)
	// ============================================
	// MEDICAL AID FILTERING
	// ============================================
	GetPatientsWithMedicalAid(ctx context.Context, arg GetPatientsWithMedicalAidParams) ([]GetPatientsWithMedicalAidRow, error)
	// ============================================
	// REPORTING QUERIES
	// ============================================
	GetPatientsWithMultipleAllergies(ctx context.Context, dollar_1 interface{}) ([]GetPatientsWithMultipleAllergiesRow, error)
	// ============================================
	// REPORTING QUERIES
	// ============================================
	GetPatientsWithMultipleConditions(ctx context.Context, dollar_1 interface{}) ([]GetPatientsWithMultipleConditionsRow, error)
	GetPatientsWithNoAllergies(ctx context.Context, arg GetPatientsWithNoAllergiesParams) ([]GetPatientsWithNoAllergiesRow, error)
	GetPatientsWithOutdatedVitals(ctx context.Context, arg GetPatientsWithOutdatedVitalsParams) ([]GetPatientsWithOutdatedVitalsRow, error)
	GetPatientsWithoutMedicalAid(ctx context.Context, arg GetPatientsWithoutMedicalAidParams) ([]GetPatientsWithoutMedicalAidRow, error)
	GetPatientsWithoutPrimaryCare(ctx context.Context, arg GetPatientsWithoutPrimaryCareParams) ([]GetPatientsWithoutPrimaryCareRow, error)
	GetPediatricServices(ctx context.Context, clinicID pgtype.UUID) ([]GetPediatricServicesRow, error)
	// ============================================
	// VERIFICATION WORKFLOWS
	// ============================================
	GetPendingCredentialVerifications(ctx context.Context) ([]GetPendingCredentialVerificationsRow, error)
	GetPendingCredentialsByClinic(ctx context.Context, clinicID pgtype.UUID) ([]GetPendingCredentialsByClinicRow, error)
	GetPendingVerificationClinics(ctx context.Context, arg GetPendingVerificationClinicsParams) ([]GetPendingVerificationClinicsRow, error)
	GetPrescriptionTrends(ctx context.Context, prescriptionDate pgtype.Date) ([]GetPrescriptionTrendsRow, error)
	GetPreventiveServices(ctx context.Context, clinicID pgtype.UUID) ([]GetPreventiveServicesRow, error)
	GetPrivacyConsent(ctx context.Context, userID pgtype.UUID) (PrivacyConsent, error)
	GetProfilesMissingCriticalInfo(ctx context.Context, arg GetProfilesMissingCriticalInfoParams) ([]GetProfilesMissingCriticalInfoRow, error)
	GetProfilesNeedingUpdate(ctx context.Context, arg GetProfilesNeedingUpdateParams) ([]GetProfilesNeedingUpdateRow, error)
	GetProvinceMetrics(ctx context.Context) ([]GetProvinceMetricsRow, error)
	GetQuickServices(ctx context.Context, arg GetQuickServicesParams) ([]GetQuickServicesRow, error)
	GetRecentActivities(ctx context.Context, arg GetRecentActivitiesParams) ([]UserActivity, error)
	GetRecentAllergyOccurrences(ctx context.Context, lastOccurrenceDate pgtype.Date) ([]GetRecentAllergyOccurrencesRow, error)
	GetRecentFlareUps(ctx context.Context, lastFlareUp pgtype.Date) ([]GetRecentFlareUpsRow, error)
	GetRecentOTPs(ctx context.Context, arg GetRecentOTPsParams) ([]OtpVerification, error)
	GetRecentlyAddedClinics(ctx context.Context, arg GetRecentlyAddedClinicsParams) ([]GetRecentlyAddedClinicsRow, error)
	GetRecentlyAddedServices(ctx context.Context, arg GetRecentlyAddedServicesParams) ([]GetRecentlyAddedServicesRow, error)
	GetRecentlyUpdatedProfiles(ctx context.Context, arg GetRecentlyUpdatedProfilesParams) ([]GetRecentlyUpdatedProfilesRow, error)
	GetRecentlyVerifiedClinics(ctx context.Context, limit int32) ([]GetRecentlyVerifiedClinicsRow, error)
	GetRecentlyVerifiedCredentials(ctx context.Context) ([]GetRecentlyVerifiedCredentialsRow, error)
	GetRejectedCredentials(ctx context.Context) ([]GetRejectedCredentialsRow, error)
	GetRevokedCredentials(ctx context.Context) ([]GetRevokedCredentialsRow, error)
	GetRoutineImmunizations(ctx context.Context, patientID pgtype.UUID) ([]GetRoutineImmunizationsRow, error)
	GetSMSConversationByPhone(ctx context.Context, phoneNumber string) (SmsConversation, error)
	GetServiceByID(ctx context.Context, id pgtype.UUID) (ClinicService, error)
	GetServiceCategoryDistribution(ctx context.Context, clinicID pgtype.UUID) ([]GetServiceCategoryDistributionRow, error)
	GetServicePriceDistribution(ctx context.Context, clinicID pgtype.UUID) ([]GetServicePriceDistributionRow, error)
	// ============================================
	// STATISTICS & ANALYTICS
	// ============================================
	GetServiceStatistics(ctx context.Context, id pgtype.UUID) (GetServiceStatisticsRow, error)
	// ============================================
	// AVAILABILITY & SCHEDULING
	// ============================================
	GetServicesAvailableOnDay(ctx context.Context, arg GetServicesAvailableOnDayParams) ([]GetServicesAvailableOnDayRow, error)
	// ============================================
	// BULK OPERATIONS
	// ============================================
	GetServicesByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ClinicService, error)
	GetServicesByMedicalAidCode(ctx context.Context, dollar_1 []byte) ([]GetServicesByMedicalAidCodeRow, error)
	GetServicesByPriceRange(ctx context.Context, arg GetServicesByPriceRangeParams) ([]GetServicesByPriceRangeRow, error)
	// ============================================
	// AGE & ELIGIBILITY FILTERING
	// ============================================
	GetServicesForAge(ctx context.Context, arg GetServicesForAgeParams) ([]GetServicesForAgeRow, error)
	GetServicesForGender(ctx context.Context, arg GetServicesForGenderParams) ([]GetServicesForGenderRow, error)
	GetServicesRequiringFollowUp(ctx context.Context, clinicID pgtype.UUID) ([]GetServicesRequiringFollowUpRow, error)
	GetSession(ctx context.Context, sessionToken string) (GetSessionRow, error)
	// ============================================
	// SEVERITY-BASED QUERIES
	// ============================================
	GetSevereAllergies(ctx context.Context, patientID pgtype.UUID) ([]GetSevereAllergiesRow, error)
	GetSpecializationCredentials(ctx context.Context) ([]GetSpecializationCredentialsRow, error)
	// ============================================
	// STAFF AVAILABILITY QUERIES
	// ============================================
	GetStaffAvailableOnDay(ctx context.Context, arg GetStaffAvailableOnDayParams) ([]GetStaffAvailableOnDayRow, error)
	GetStaffByDepartment(ctx context.Context, arg GetStaffByDepartmentParams) ([]GetStaffByDepartmentRow, error)
	GetStaffByExperience(ctx context.Context, arg GetStaffByExperienceParams) ([]GetStaffByExperienceRow, error)
	// ============================================
	// LICENSING & CREDENTIALS
	// ============================================
	GetStaffByHPCSNumber(ctx context.Context, hpcsNumber pgtype.Text) (ClinicStaff, error)
	GetStaffByID(ctx context.Context, id pgtype.UUID) (ClinicStaff, error)
	// ============================================
	// BULK OPERATIONS
	// ============================================
	GetStaffByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ClinicStaff, error)
	// ============================================
	// LANGUAGE & COMMUNICATION
	// ============================================
	GetStaffByLanguage(ctx context.Context, arg GetStaffByLanguageParams) ([]GetStaffByLanguageRow, error)
	GetStaffBySpecialization(ctx context.Context, arg GetStaffBySpecializationParams) ([]GetStaffBySpecializationRow, error)
	GetStaffByUserID(ctx context.Context, userID pgtype.UUID) (ClinicStaff, error)
	// ============================================
	// QUERYING BY STAFF MEMBER
	// ============================================
	GetStaffCredentials(ctx context.Context, staffID pgtype.UUID) ([]ProfessionalCredential, error)
	GetStaffCredentialsByType(ctx context.Context, arg GetStaffCredentialsByTypeParams) ([]GetStaffCredentialsByTypeRow, error)
	GetStaffDemographics(ctx context.Context, clinicID pgtype.UUID) (GetStaffDemographicsRow, error)
	GetStaffHiredBetweenDates(ctx context.Context, arg GetStaffHiredBetweenDatesParams) ([]GetStaffHiredBetweenDatesRow, error)
	GetStaffNeedingCredentialRenewal(ctx context.Context) ([]GetStaffNeedingCredentialRenewalRow, error)
	GetStaffRoleDistribution(ctx context.Context, clinicID pgtype.UUID) ([]GetStaffRoleDistributionRow, error)
	// ============================================
	// STATISTICS & ANALYTICS
	// ============================================
	GetStaffStatistics(ctx context.Context, id pgtype.UUID) (GetStaffStatisticsRow, error)
	GetStaffTerminatedBetweenDates(ctx context.Context, arg GetStaffTerminatedBetweenDatesParams) ([]GetStaffTerminatedBetweenDatesRow, error)
	GetStaffTransferHistory(ctx context.Context, userID pgtype.UUID) ([]GetStaffTransferHistoryRow, error)
	GetStaffWithExpiredLicenses(ctx context.Context) ([]GetStaffWithExpiredLicensesRow, error)
	GetStaffWithIncompleteProfiles(ctx context.Context) ([]GetStaffWithIncompleteProfilesRow, error)
	// ============================================
	// REPORTING & COMPLIANCE
	// ============================================
	GetStaffWithoutHPCSNumber(ctx context.Context) ([]GetStaffWithoutHPCSNumberRow, error)
	// ============================================
	// COMPLIANCE & REPORTING
	// ============================================
	GetStaffWithoutRequiredCredentials(ctx context.Context) ([]GetStaffWithoutRequiredCredentialsRow, error)
	GetStaffWorkingHours(ctx context.Context, id pgtype.UUID) (GetStaffWorkingHoursRow, error)
	GetStaleProfiles(ctx context.Context, arg GetStaleProfilesParams) ([]GetStaleProfilesRow, error)
	GetSystemCredentialMetrics(ctx context.Context) (GetSystemCredentialMetricsRow, error)
	// ============================================
	// RANKING & DISCOVERY
	// ============================================
	GetTopRatedClinics(ctx context.Context, arg GetTopRatedClinicsParams) ([]GetTopRatedClinicsRow, error)
	// ============================================
	// POPULAR & RECOMMENDED SERVICES
	// ============================================
	GetTopRatedServices(ctx context.Context, arg GetTopRatedServicesParams) ([]GetTopRatedServicesRow, error)
	GetUnderservedPatients(ctx context.Context, arg GetUnderservedPatientsParams) ([]GetUnderservedPatientsRow, error)
	GetUnderweightPatients(ctx context.Context, arg GetUnderweightPatientsParams) ([]GetUnderweightPatientsRow, error)
	GetUnresolvedAllergies(ctx context.Context) ([]GetUnresolvedAllergiesRow, error)
	GetUpcomingCheckups(ctx context.Context, nextCheckupDate pgtype.Date) ([]GetUpcomingCheckupsRow, error)
	// ============================================
	// DUE DATE & SCHEDULING
	// ============================================
	GetUpcomingImmunizations(ctx context.Context, patientID pgtype.UUID) ([]GetUpcomingImmunizationsRow, error)
	GetUpdatedPatientsInPeriod(ctx context.Context, arg GetUpdatedPatientsInPeriodParams) ([]GetUpdatedPatientsInPeriodRow, error)
	GetUserActivities(ctx context.Context, arg GetUserActivitiesParams) ([]UserActivity, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	GetUserByPasswordResetToken(ctx context.Context, resetPasswordToken pgtype.Text) (GetUserByPasswordResetTokenRow, error)
	GetUserByPhone(ctx context.Context, phone pgtype.Text) (GetUserByPhoneRow, error)
	GetUserByPhoneWithHash(ctx context.Context, phone pgtype.Text) (GetUserByPhoneWithHashRow, error)
	GetUserByVerificationToken(ctx context.Context, verificationToken pgtype.Text) (GetUserByVerificationTokenRow, error)
	GetUserSessions(ctx context.Context, userID pgtype.UUID) ([]UserSession, error)
	GetUsersByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetUsersByIDsRow, error)
	GetUsersForHealthTips(ctx context.Context, healthTipsFrequency pgtype.Text) ([]pgtype.UUID, error)
	GetUsersWithDisabledType(ctx context.Context, dollar_1 interface{}) ([]pgtype.UUID, error)
	GetVaccineDistribution(ctx context.Context) ([]GetVaccineDistributionRow, error)
	GetVaccineSeriesProgress(ctx context.Context, patientID pgtype.UUID) ([]GetVaccineSeriesProgressRow, error)
	GetVerificationBacklog(ctx context.Context) ([]GetVerificationBacklogRow, error)
	GetVerifiedClinics(ctx context.Context, arg GetVerifiedClinicsParams) ([]GetVerifiedClinicsRow, error)
	GetVerifiedStaffCredentials(ctx context.Context, staffID pgtype.UUID) ([]GetVerifiedStaffCredentialsRow, error)
	GetVerifierWorkload(ctx context.Context, arg GetVerifierWorkloadParams) ([]GetVerifierWorkloadRow, error)
	GetVitalStatisticsSummary(ctx context.Context) (GetVitalStatisticsSummaryRow, error)
	GetWalkInServices(ctx context.Context, clinicID pgtype.UUID) ([]GetWalkInServicesRow, error)
	GetWithdrawnConsents(ctx context.Context, arg GetWithdrawnConsentsParams) ([]PrivacyConsent, error)
	// ============================================
	// VALIDATION & UTILITIES
	// ============================================
	HasChronicConditions(ctx context.Context, patientID pgtype.UUID) (bool, error)
	HasCompleteVitals(ctx context.Context, patientID pgtype.UUID) (pgtype.Bool, error)
	HasLifeThreateningAllergies(ctx context.Context, patientID pgtype.UUID) (bool, error)
	HasVerifiedCredentialOfType(ctx context.Context, arg HasVerifiedCredentialOfTypeParams) (bool, error)
	IncrementPopularityScore(ctx context.Context, id pgtype.UUID) error
	IncrementReviewCount(ctx context.Context, id pgtype.UUID) error
	IncrementServiceReviewCount(ctx context.Context, id pgtype.UUID) error
	InvalidateUserOTPs(ctx context.Context, arg InvalidateUserOTPsParams) error
	IsVaccineSeriesComplete(ctx context.Context, arg IsVaccineSeriesCompleteParams) (bool, error)
	// ============================================
	// FILTERING & LISTING
	// ============================================
	ListClinics(ctx context.Context, arg ListClinicsParams) ([]ListClinicsRow, error)
	ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]ListUsersByRoleRow, error)
	// ============================================
	// Data Access Log Queries
	// ============================================
	LogDataAccess(ctx context.Context, arg LogDataAccessParams) error
	LogSMSMessage(ctx context.Context, arg LogSMSMessageParams) (LogSMSMessageRow, error)
	// ============================================
	// User Activity Queries
	// ============================================
	LogUserActivity(ctx context.Context, arg LogUserActivityParams) error
	MarkAllergyInactive(ctx context.Context, arg MarkAllergyInactiveParams) error
	MarkAllergyResolved(ctx context.Context, arg MarkAllergyResolvedParams) error
	MarkConditionInRemission(ctx context.Context, arg MarkConditionInRemissionParams) error
	MarkConditionResolved(ctx context.Context, arg MarkConditionResolvedParams) error
	MarkCredentialExpired(ctx context.Context, id pgtype.UUID) error
	MarkOTPUsed(ctx context.Context, arg MarkOTPUsedParams) error
	// ============================================
	// VALIDATION & UTILITIES
	// ============================================
	MedicalInfoExists(ctx context.Context, patientID pgtype.UUID) (bool, error)
	NeedsBMICalculation(ctx context.Context) ([]NeedsBMICalculationRow, error)
	ReactivateAllergy(ctx context.Context, id pgtype.UUID) error
	ReactivateClinic(ctx context.Context, id pgtype.UUID) error
	ReactivateMedication(ctx context.Context, id pgtype.UUID) error
	// ============================================
	// OCCURRENCE TRACKING
	// ============================================
	RecordAllergyOccurrence(ctx context.Context, arg RecordAllergyOccurrenceParams) error
	// ============================================
	// FLARE-UP & CHECKUP TRACKING
	// ============================================
	RecordFlareUp(ctx context.Context, arg RecordFlareUpParams) error
	// ============================================
	// SIDE EFFECTS & MONITORING
	// ============================================
	RecordSideEffects(ctx context.Context, arg RecordSideEffectsParams) error
	RecordVitalMeasurement(ctx context.Context, arg RecordVitalMeasurementParams) error
	RejectClinicVerification(ctx context.Context, arg RejectClinicVerificationParams) error
	RejectCredential(ctx context.Context, arg RejectCredentialParams) error
	RemoveStaffFromService(ctx context.Context, arg RemoveStaffFromServiceParams) error
	RenewCredential(ctx context.Context, arg RenewCredentialParams) error
	RevokeCredential(ctx context.Context, arg RevokeCredentialParams) error
	// OTP Verification Queries
	SaveOTP(ctx context.Context, arg SaveOTPParams) (OtpVerification, error)
	SearchAllergiesByName(ctx context.Context, arg SearchAllergiesByNameParams) ([]SearchAllergiesByNameRow, error)
	// ============================================
	// SEARCH & DISCOVERY
	// ============================================
	SearchClinics(ctx context.Context, arg SearchClinicsParams) ([]SearchClinicsRow, error)
	// ============================================
	// ADVANCED SEARCH
	// ============================================
	SearchClinicsAdvanced(ctx context.Context, arg SearchClinicsAdvancedParams) ([]SearchClinicsAdvancedRow, error)
	SearchClinicsByLocation(ctx context.Context, arg SearchClinicsByLocationParams) ([]SearchClinicsByLocationRow, error)
	SearchClinicsByName(ctx context.Context, arg SearchClinicsByNameParams) ([]SearchClinicsByNameRow, error)
	// ============================================
	// SEARCH & FILTERING
	// ============================================
	SearchConditionsByName(ctx context.Context, arg SearchConditionsByNameParams) ([]SearchConditionsByNameRow, error)
	SearchDataAccessLogs(ctx context.Context, arg SearchDataAccessLogsParams) ([]DataAccessLog, error)
	// ============================================
	// SEARCH & FILTERING
	// ============================================
	SearchMedicationsByName(ctx context.Context, arg SearchMedicationsByNameParams) ([]SearchMedicationsByNameRow, error)
	// ============================================
	// SEARCH & DISCOVERY
	// ============================================
	SearchPatients(ctx context.Context, arg SearchPatientsParams) ([]SearchPatientsRow, error)
	SearchPatientsByName(ctx context.Context, arg SearchPatientsByNameParams) ([]SearchPatientsByNameRow, error)
	// ============================================
	// SEARCH & FILTERING
	// ============================================
	SearchServices(ctx context.Context, arg SearchServicesParams) ([]SearchServicesRow, error)
	SearchServicesByCategory(ctx context.Context, arg SearchServicesByCategoryParams) ([]SearchServicesByCategoryRow, error)
	// ============================================
	// STAFF SEARCH & FILTERING
	// ============================================
	SearchStaffByName(ctx context.Context, arg SearchStaffByNameParams) ([]SearchStaffByNameRow, error)
	SearchUserActivities(ctx context.Context, arg SearchUserActivitiesParams) ([]UserActivity, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error)
	ServiceExists(ctx context.Context, id pgtype.UUID) (bool, error)
	SetAcceptingPatients(ctx context.Context, id pgtype.UUID) error
	SetNotAcceptingPatients(ctx context.Context, id pgtype.UUID) error
	SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error
	SetPrimaryContact(ctx context.Context, arg SetPrimaryContactParams) error
	SetStaffOnLeave(ctx context.Context, id pgtype.UUID) error
	SetVerificationToken(ctx context.Context, arg SetVerificationTokenParams) error
	StaffExists(ctx context.Context, id pgtype.UUID) (bool, error)
	ToggleServiceStatus(ctx context.Context, id pgtype.UUID) error
	// ============================================
	// TRANSFER & REASSIGNMENT
	// ============================================
	TransferStaffToClinic(ctx context.Context, arg TransferStaffToClinicParams) error
	UpdateAdvanceDirective(ctx context.Context, arg UpdateAdvanceDirectiveParams) error
	// ============================================
	// STATUS MANAGEMENT
	// ============================================
	UpdateAllergyStatus(ctx context.Context, arg UpdateAllergyStatusParams) error
	UpdateAppointmentReminders(ctx context.Context, arg UpdateAppointmentRemindersParams) error
	UpdateAverageWaitTime(ctx context.Context, arg UpdateAverageWaitTimeParams) error
	UpdateBloodTypeTestDate(ctx context.Context, arg UpdateBloodTypeTestDateParams) error
	UpdateChannelSettings(ctx context.Context, arg UpdateChannelSettingsParams) error
	UpdateClinic(ctx context.Context, arg UpdateClinicParams) error
	// ============================================
	// ACCREDITATION & CERTIFICATION
	// ============================================
	UpdateClinicAccreditation(ctx context.Context, arg UpdateClinicAccreditationParams) error
	// ============================================
	// OPERATIONAL METRICS
	// ============================================
	UpdateClinicCapacity(ctx context.Context, arg UpdateClinicCapacityParams) error
	// ============================================
	// CONTACT INFORMATION
	// ============================================
	UpdateClinicContact(ctx context.Context, arg UpdateClinicContactParams) error
	UpdateClinicCoordinates(ctx context.Context, arg UpdateClinicCoordinatesParams) error
	// ============================================
	// LOCATION MANAGEMENT
	// ============================================
	UpdateClinicLocation(ctx context.Context, arg UpdateClinicLocationParams) error
	UpdateClinicOperatingHours(ctx context.Context, arg UpdateClinicOperatingHoursParams) error
	// ============================================
	// PAYMENT & INSURANCE
	// ============================================
	UpdateClinicPaymentInfo(ctx context.Context, arg UpdateClinicPaymentInfoParams) error
	// ============================================
	// RATINGS & REVIEWS
	// ============================================
	UpdateClinicRating(ctx context.Context, arg UpdateClinicRatingParams) error
	UpdateClinicService(ctx context.Context, arg UpdateClinicServiceParams) error
	// ============================================
	// SERVICES & CAPABILITIES
	// ============================================
	UpdateClinicServices(ctx context.Context, arg UpdateClinicServicesParams) error
	UpdateClinicVerificationStatus(ctx context.Context, arg UpdateClinicVerificationStatusParams) error
	UpdateCommunicationConsents(ctx context.Context, arg UpdateCommunicationConsentsParams) error
	UpdateConditionSeverity(ctx context.Context, arg UpdateConditionSeverityParams) error
	// ============================================
	// STATUS MANAGEMENT
	// ============================================
	UpdateConditionStatus(ctx context.Context, arg UpdateConditionStatusParams) error
	UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error
	UpdateCredentialDates(ctx context.Context, arg UpdateCredentialDatesParams) error
	UpdateCredentialDocument(ctx context.Context, arg UpdateCredentialDocumentParams) error
	UpdateCredentialExpiry(ctx context.Context, arg UpdateCredentialExpiryParams) error
	UpdateCredentialNotes(ctx context.Context, arg UpdateCredentialNotesParams) error
	// ============================================
	// CREDENTIAL DETAILS MANAGEMENT
	// ============================================
	UpdateCredentialNumber(ctx context.Context, arg UpdateCredentialNumberParams) error
	UpdateCredentialStatus(ctx context.Context, arg UpdateCredentialStatusParams) error
	UpdateDNRStatus(ctx context.Context, arg UpdateDNRStatusParams) error
	UpdateDataSharingConsent(ctx context.Context, arg UpdateDataSharingConsentParams) error
	UpdateEmergencyAccessConsent(ctx context.Context, arg UpdateEmergencyAccessConsentParams) error
	UpdateEmergencyAlerts(ctx context.Context, arg UpdateEmergencyAlertsParams) error
	UpdateEndOfLifePreferences(ctx context.Context, arg UpdateEndOfLifePreferencesParams) error
	UpdateHealthDataConsent(ctx context.Context, arg UpdateHealthDataConsentParams) error
	UpdateHealthSummary(ctx context.Context, arg UpdateHealthSummaryParams) error
	UpdateHealthTips(ctx context.Context, arg UpdateHealthTipsParams) error
	UpdateLastOccurrence(ctx context.Context, arg UpdateLastOccurrenceParams) error
	UpdateMedicationEndDate(ctx context.Context, arg UpdateMedicationEndDateParams) error
	UpdateMedicationReminders(ctx context.Context, arg UpdateMedicationRemindersParams) error
	// ============================================
	// STATUS MANAGEMENT
	// ============================================
	UpdateMedicationStatus(ctx context.Context, arg UpdateMedicationStatusParams) error
	UpdateNextCheckup(ctx context.Context, arg UpdateNextCheckupParams) error
	UpdateNextDueDate(ctx context.Context, arg UpdateNextDueDateParams) error
	UpdateNotificationLanguage(ctx context.Context, arg UpdateNotificationLanguageParams) error
	UpdateNotificationPreferences(ctx context.Context, arg UpdateNotificationPreferencesParams) error
	// ============================================
	// ADVANCE DIRECTIVES & END-OF-LIFE
	// ============================================
	UpdateOrganDonorStatus(ctx context.Context, arg UpdateOrganDonorStatusParams) error
	UpdatePatientAcceptanceStatus(ctx context.Context, arg UpdatePatientAcceptanceStatusParams) error
	UpdatePatientAllergy(ctx context.Context, arg UpdatePatientAllergyParams) error
	UpdatePatientBMI(ctx context.Context, arg UpdatePatientBMIParams) error
	// ============================================
	// BLOOD TYPE MANAGEMENT
	// ============================================
	UpdatePatientBloodType(ctx context.Context, arg UpdatePatientBloodTypeParams) error
	UpdatePatientCondition(ctx context.Context, arg UpdatePatientConditionParams) error
	UpdatePatientContactInfo(ctx context.Context, arg UpdatePatientContactInfoParams) error
	UpdatePatientDemographicInfo(ctx context.Context, arg UpdatePatientDemographicInfoParams) error
	// ============================================
	// HEALTH STATUS MANAGEMENT
	// ============================================
	UpdatePatientHealthStatus(ctx context.Context, arg UpdatePatientHealthStatusParams) error
	UpdatePatientHeight(ctx context.Context, arg UpdatePatientHeightParams) error
	UpdatePatientImmunization(ctx context.Context, arg UpdatePatientImmunizationParams) error
	UpdatePatientLanguagePreferences(ctx context.Context, arg UpdatePatientLanguagePreferencesParams) error
	UpdatePatientMarketingPreferences(ctx context.Context, arg UpdatePatientMarketingPreferencesParams) error
	UpdatePatientMedicalAidInfo(ctx context.Context, arg UpdatePatientMedicalAidInfoParams) error
	UpdatePatientMedicalInfo(ctx context.Context, arg UpdatePatientMedicalInfoParams) error
	UpdatePatientMedication(ctx context.Context, arg UpdatePatientMedicationParams) error
	UpdatePatientNationalID(ctx context.Context, arg UpdatePatientNationalIDParams) error
	// ============================================
	// PROFILE SECTION UPDATES
	// ============================================
	UpdatePatientPersonalInfo(ctx context.Context, arg UpdatePatientPersonalInfoParams) error
	UpdatePatientProfile(ctx context.Context, arg UpdatePatientProfileParams) error
	UpdatePatientProfilePicture(ctx context.Context, arg UpdatePatientProfilePictureParams) error
	UpdatePatientReferralInfo(ctx context.Context, arg UpdatePatientReferralInfoParams) error
	UpdatePatientTimezone(ctx context.Context, arg UpdatePatientTimezoneParams) error
	// ============================================
	// VITAL STATISTICS MANAGEMENT
	// ============================================
	UpdatePatientVitals(ctx context.Context, arg UpdatePatientVitalsParams) error
	UpdatePatientWeight(ctx context.Context, arg UpdatePatientWeightParams) error
	UpdatePharmacy(ctx context.Context, arg UpdatePharmacyParams) error
	// ============================================
	// CARE PROVIDER MANAGEMENT
	// ============================================
	UpdatePrimaryCareProvider(ctx context.Context, arg UpdatePrimaryCareProviderParams) error
	UpdatePrimaryClinic(ctx context.Context, arg UpdatePrimaryClinicParams) error
	UpdatePrimaryPhysician(ctx context.Context, arg UpdatePrimaryPhysicianParams) error
	UpdatePrivacyConsent(ctx context.Context, arg UpdatePrivacyConsentParams) error
	UpdateQuietHours(ctx context.Context, arg UpdateQuietHoursParams) error
	UpdateResearchConsent(ctx context.Context, arg UpdateResearchConsentParams) error
	UpdateSMSConversation(ctx context.Context, arg UpdateSMSConversationParams) error
	UpdateServiceAvailability(ctx context.Context, arg UpdateServiceAvailabilityParams) error
	UpdateServiceCost(ctx context.Context, arg UpdateServiceCostParams) error
	// ============================================
	// SERVICE DETAILS MANAGEMENT
	// ============================================
	UpdateServiceDetails(ctx context.Context, arg UpdateServiceDetailsParams) error
	UpdateServiceEligibility(ctx context.Context, arg UpdateServiceEligibilityParams) error
	UpdateServicePopularity(ctx context.Context, arg UpdateServicePopularityParams) error
	// ============================================
	// SERVICE METRICS & RATINGS
	// ============================================
	UpdateServiceRating(ctx context.Context, arg UpdateServiceRatingParams) error
	UpdateServiceStaff(ctx context.Context, arg UpdateServiceStaffParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) error
	UpdateSessionToken(ctx context.Context, arg UpdateSessionTokenParams) error
	// ============================================
	// AVAILABILITY & SCHEDULING
	// ============================================
	UpdateStaffAvailability(ctx context.Context, arg UpdateStaffAvailabilityParams) error
	// ============================================
	// CONTACT INFORMATION
	// ============================================
	UpdateStaffContact(ctx context.Context, arg UpdateStaffContactParams) error
	UpdateStaffEmploymentDates(ctx context.Context, arg UpdateStaffEmploymentDatesParams) error
	UpdateStaffLicenses(ctx context.Context, arg UpdateStaffLicensesParams) error
	UpdateStaffMember(ctx context.Context, arg UpdateStaffMemberParams) error
	// ============================================
	// PROFESSIONAL INFORMATION
	// ============================================
	UpdateStaffProfessionalInfo(ctx context.Context, arg UpdateStaffProfessionalInfoParams) error
	UpdateStaffProfile(ctx context.Context, arg UpdateStaffProfileParams) error
	UpdateStaffQualifications(ctx context.Context, arg UpdateStaffQualificationsParams) error
	// ============================================
	// ROLE & EMPLOYMENT
	// ============================================
	UpdateStaffRole(ctx context.Context, arg UpdateStaffRoleParams) error
	UpdateStaffStatus(ctx context.Context, arg UpdateStaffStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserConsents(ctx context.Context, arg UpdateUserConsentsParams) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserLastLogin(ctx context.Context, id pgtype.UUID) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) error
	UpdateUserProfileCompletion(ctx context.Context, arg UpdateUserProfileCompletionParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	// ============================================
	// VALIDATION & UTILITIES
	// ============================================
	ValidatePatientExists(ctx context.Context, userID pgtype.UUID) (bool, error)
	ValidateProfileComplete(ctx context.Context, userID pgtype.UUID) (pgtype.Bool, error)
	// ============================================
	// VERIFICATION & STATUS
	// ============================================
	VerifyClinic(ctx context.Context, arg VerifyClinicParams) error
	// ============================================
	// VERIFICATION & STATUS MANAGEMENT
	// ============================================
	VerifyCredential(ctx context.Context, arg VerifyCredentialParams) error
	VerifyUser(ctx context.Context, id pgtype.UUID) error
	WithdrawConsent(ctx context.Context, arg WithdrawConsentParams) error
}

var _ Querier = (*Queries)(nil)
