// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_admin.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRegionAssignment = `-- name: AddRegionAssignment :exec
UPDATE system_admins
SET 
    assigned_regions = array_append(assigned_regions, $2),
    updated_at = NOW()
WHERE id = $1 AND NOT ($2 = ANY(assigned_regions))
`

type AddRegionAssignmentParams struct {
	ID          pgtype.UUID `json:"id"`
	ArrayAppend interface{} `json:"array_append"`
}

func (q *Queries) AddRegionAssignment(ctx context.Context, arg AddRegionAssignmentParams) error {
	_, err := q.db.Exec(ctx, addRegionAssignment, arg.ID, arg.ArrayAppend)
	return err
}

const bulkAssignRegion = `-- name: BulkAssignRegion :exec
UPDATE system_admins
SET 
    assigned_regions = array_append(assigned_regions, $2),
    updated_at = NOW()
WHERE 
    id = ANY($1::uuid[])
    AND NOT ($2 = ANY(assigned_regions))
`

type BulkAssignRegionParams struct {
	Column1     []pgtype.UUID `json:"column_1"`
	ArrayAppend interface{}   `json:"array_append"`
}

func (q *Queries) BulkAssignRegion(ctx context.Context, arg BulkAssignRegionParams) error {
	_, err := q.db.Exec(ctx, bulkAssignRegion, arg.Column1, arg.ArrayAppend)
	return err
}

const bulkRemoveRegion = `-- name: BulkRemoveRegion :exec
UPDATE system_admins
SET 
    assigned_regions = array_remove(assigned_regions, $2),
    updated_at = NOW()
WHERE id = ANY($1::uuid[])
`

type BulkRemoveRegionParams struct {
	Column1     []pgtype.UUID `json:"column_1"`
	ArrayRemove interface{}   `json:"array_remove"`
}

func (q *Queries) BulkRemoveRegion(ctx context.Context, arg BulkRemoveRegionParams) error {
	_, err := q.db.Exec(ctx, bulkRemoveRegion, arg.Column1, arg.ArrayRemove)
	return err
}

const bulkUpdateDepartment = `-- name: BulkUpdateDepartment :exec
UPDATE system_admins
SET 
    department = $2,
    updated_at = NOW()
WHERE id = ANY($1::uuid[])
`

type BulkUpdateDepartmentParams struct {
	Column1    []pgtype.UUID `json:"column_1"`
	Department pgtype.Text   `json:"department"`
}

func (q *Queries) BulkUpdateDepartment(ctx context.Context, arg BulkUpdateDepartmentParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateDepartment, arg.Column1, arg.Department)
	return err
}

const bulkUpdatePermissions = `-- name: BulkUpdatePermissions :exec
UPDATE system_admins
SET 
    permissions = $2,
    updated_at = NOW()
WHERE id = ANY($1::uuid[])
`

type BulkUpdatePermissionsParams struct {
	Column1     []pgtype.UUID `json:"column_1"`
	Permissions []byte        `json:"permissions"`
}

func (q *Queries) BulkUpdatePermissions(ctx context.Context, arg BulkUpdatePermissionsParams) error {
	_, err := q.db.Exec(ctx, bulkUpdatePermissions, arg.Column1, arg.Permissions)
	return err
}

const checkAdminExists = `-- name: CheckAdminExists :one

SELECT EXISTS(
    SELECT 1 FROM system_admins
    WHERE user_id = $1
) as exists
`

// ============================================
// VALIDATION & UTILITIES
// ============================================
func (q *Queries) CheckAdminExists(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkAdminExists, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkAdminHasRegion = `-- name: CheckAdminHasRegion :one
SELECT EXISTS(
    SELECT 1 FROM system_admins
    WHERE id = $1 AND $2 = ANY(assigned_regions)
) as has_region
`

type CheckAdminHasRegionParams struct {
	ID              pgtype.UUID `json:"id"`
	AssignedRegions []string    `json:"assigned_regions"`
}

func (q *Queries) CheckAdminHasRegion(ctx context.Context, arg CheckAdminHasRegionParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkAdminHasRegion, arg.ID, arg.AssignedRegions)
	var has_region bool
	err := row.Scan(&has_region)
	return has_region, err
}

const checkHasPermission = `-- name: CheckHasPermission :one
SELECT 
    CASE 
        WHEN $2 = 'manage_users' THEN can_manage_users
        WHEN $2 = 'manage_clinics' THEN can_manage_clinics
        WHEN $2 = 'manage_content' THEN can_manage_content
        WHEN $2 = 'view_analytics' THEN can_view_analytics
        WHEN $2 = 'manage_system' THEN can_manage_system
        ELSE false
    END as has_permission
FROM system_admins
WHERE user_id = $1
`

type CheckHasPermissionParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) CheckHasPermission(ctx context.Context, arg CheckHasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkHasPermission, arg.UserID, arg.Column2)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const checkIsSuperAdmin = `-- name: CheckIsSuperAdmin :one
SELECT EXISTS(
    SELECT 1 FROM system_admins
    WHERE user_id = $1 AND admin_level = 'super_admin'
) as is_super_admin
`

func (q *Queries) CheckIsSuperAdmin(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkIsSuperAdmin, userID)
	var is_super_admin bool
	err := row.Scan(&is_super_admin)
	return is_super_admin, err
}

const countAdminsByDepartment = `-- name: CountAdminsByDepartment :many
SELECT 
    department,
    COUNT(*) as admin_count,
    COUNT(*) FILTER (WHERE admin_level = 'super_admin') as super_admin_count,
    COUNT(*) FILTER (WHERE admin_level = 'regional_admin') as regional_admin_count,
    COUNT(*) FILTER (WHERE admin_level = 'support_admin') as support_admin_count
FROM system_admins
WHERE department IS NOT NULL
GROUP BY department
ORDER BY admin_count DESC
`

type CountAdminsByDepartmentRow struct {
	Department         pgtype.Text `json:"department"`
	AdminCount         int64       `json:"admin_count"`
	SuperAdminCount    int64       `json:"super_admin_count"`
	RegionalAdminCount int64       `json:"regional_admin_count"`
	SupportAdminCount  int64       `json:"support_admin_count"`
}

func (q *Queries) CountAdminsByDepartment(ctx context.Context) ([]CountAdminsByDepartmentRow, error) {
	rows, err := q.db.Query(ctx, countAdminsByDepartment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAdminsByDepartmentRow{}
	for rows.Next() {
		var i CountAdminsByDepartmentRow
		if err := rows.Scan(
			&i.Department,
			&i.AdminCount,
			&i.SuperAdminCount,
			&i.RegionalAdminCount,
			&i.SupportAdminCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAdminsByLevel = `-- name: CountAdminsByLevel :one
SELECT COUNT(*) as admin_count
FROM system_admins
WHERE admin_level = $1
`

func (q *Queries) CountAdminsByLevel(ctx context.Context, adminLevel string) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminsByLevel, adminLevel)
	var admin_count int64
	err := row.Scan(&admin_count)
	return admin_count, err
}

const countSystemAdmins = `-- name: CountSystemAdmins :one

SELECT 
    COUNT(*) as total_admins,
    COUNT(*) FILTER (WHERE admin_level = 'super_admin') as super_admin_count,
    COUNT(*) FILTER (WHERE admin_level = 'regional_admin') as regional_admin_count,
    COUNT(*) FILTER (WHERE admin_level = 'support_admin') as support_admin_count,
    COUNT(*) FILTER (WHERE can_manage_users = true) as user_managers,
    COUNT(*) FILTER (WHERE can_manage_clinics = true) as clinic_managers,
    COUNT(*) FILTER (WHERE can_view_analytics = true) as analytics_viewers
FROM system_admins
`

type CountSystemAdminsRow struct {
	TotalAdmins        int64 `json:"total_admins"`
	SuperAdminCount    int64 `json:"super_admin_count"`
	RegionalAdminCount int64 `json:"regional_admin_count"`
	SupportAdminCount  int64 `json:"support_admin_count"`
	UserManagers       int64 `json:"user_managers"`
	ClinicManagers     int64 `json:"clinic_managers"`
	AnalyticsViewers   int64 `json:"analytics_viewers"`
}

// ============================================
// STATISTICS & ANALYTICS
// ============================================
func (q *Queries) CountSystemAdmins(ctx context.Context) (CountSystemAdminsRow, error) {
	row := q.db.QueryRow(ctx, countSystemAdmins)
	var i CountSystemAdminsRow
	err := row.Scan(
		&i.TotalAdmins,
		&i.SuperAdminCount,
		&i.RegionalAdminCount,
		&i.SupportAdminCount,
		&i.UserManagers,
		&i.ClinicManagers,
		&i.AnalyticsViewers,
	)
	return i, err
}

const createSystemAdmin = `-- name: CreateSystemAdmin :one


INSERT INTO system_admins (
    user_id, admin_level, assigned_regions, department,
    permissions, can_manage_users, can_manage_clinics,
    can_manage_content, can_view_analytics, can_manage_system,
    work_phone, extension
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, user_id, admin_level, assigned_regions, department, permissions, can_manage_users, can_manage_clinics, can_manage_content, can_view_analytics, can_manage_system, work_phone, extension, created_at, updated_at
`

type CreateSystemAdminParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	AdminLevel       string      `json:"admin_level"`
	AssignedRegions  []string    `json:"assigned_regions"`
	Department       pgtype.Text `json:"department"`
	Permissions      []byte      `json:"permissions"`
	CanManageUsers   pgtype.Bool `json:"can_manage_users"`
	CanManageClinics pgtype.Bool `json:"can_manage_clinics"`
	CanManageContent pgtype.Bool `json:"can_manage_content"`
	CanViewAnalytics pgtype.Bool `json:"can_view_analytics"`
	CanManageSystem  pgtype.Bool `json:"can_manage_system"`
	WorkPhone        pgtype.Text `json:"work_phone"`
	Extension        pgtype.Text `json:"extension"`
}

// ============================================
// SYSTEM ADMINS REPOSITORY QUERIES
// Maps to: AdminRepository interface
// Domain: System Administration & Access Management
// ============================================
// ============================================
// CORE CRUD OPERATIONS
// ============================================
func (q *Queries) CreateSystemAdmin(ctx context.Context, arg CreateSystemAdminParams) (SystemAdmin, error) {
	row := q.db.QueryRow(ctx, createSystemAdmin,
		arg.UserID,
		arg.AdminLevel,
		arg.AssignedRegions,
		arg.Department,
		arg.Permissions,
		arg.CanManageUsers,
		arg.CanManageClinics,
		arg.CanManageContent,
		arg.CanViewAnalytics,
		arg.CanManageSystem,
		arg.WorkPhone,
		arg.Extension,
	)
	var i SystemAdmin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AdminLevel,
		&i.AssignedRegions,
		&i.Department,
		&i.Permissions,
		&i.CanManageUsers,
		&i.CanManageClinics,
		&i.CanManageContent,
		&i.CanViewAnalytics,
		&i.CanManageSystem,
		&i.WorkPhone,
		&i.Extension,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSystemAdmin = `-- name: DeleteSystemAdmin :exec
DELETE FROM system_admins WHERE id = $1
`

func (q *Queries) DeleteSystemAdmin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSystemAdmin, id)
	return err
}

const findAdminByEmail = `-- name: FindAdminByEmail :one
SELECT 
    sa.id,
    sa.user_id,
    sa.admin_level,
    sa.department,
    sa.permissions
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
WHERE u.email = $1
`

type FindAdminByEmailRow struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	AdminLevel  string      `json:"admin_level"`
	Department  pgtype.Text `json:"department"`
	Permissions []byte      `json:"permissions"`
}

func (q *Queries) FindAdminByEmail(ctx context.Context, email string) (FindAdminByEmailRow, error) {
	row := q.db.QueryRow(ctx, findAdminByEmail, email)
	var i FindAdminByEmailRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AdminLevel,
		&i.Department,
		&i.Permissions,
	)
	return i, err
}

const findAdminByPhone = `-- name: FindAdminByPhone :one
SELECT 
    sa.id,
    sa.user_id,
    sa.admin_level,
    sa.department
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
WHERE sa.work_phone = $1 OR u.phone = $1
`

type FindAdminByPhoneRow struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	AdminLevel string      `json:"admin_level"`
	Department pgtype.Text `json:"department"`
}

func (q *Queries) FindAdminByPhone(ctx context.Context, workPhone pgtype.Text) (FindAdminByPhoneRow, error) {
	row := q.db.QueryRow(ctx, findAdminByPhone, workPhone)
	var i FindAdminByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AdminLevel,
		&i.Department,
	)
	return i, err
}

const getAdminActivitySummary = `-- name: GetAdminActivitySummary :one
SELECT 
    sa.id,
    sa.admin_level,
    sa.department,
    sa.assigned_regions,
    sa.permissions,
    COUNT(ua.id) as total_activities,
    MAX(ua.performed_at) as last_activity
FROM system_admins sa
LEFT JOIN user_activities ua ON sa.user_id = ua.user_id
WHERE sa.id = $1
GROUP BY sa.id, sa.admin_level, sa.department, sa.assigned_regions, sa.permissions
`

type GetAdminActivitySummaryRow struct {
	ID              pgtype.UUID `json:"id"`
	AdminLevel      string      `json:"admin_level"`
	Department      pgtype.Text `json:"department"`
	AssignedRegions []string    `json:"assigned_regions"`
	Permissions     []byte      `json:"permissions"`
	TotalActivities int64       `json:"total_activities"`
	LastActivity    interface{} `json:"last_activity"`
}

func (q *Queries) GetAdminActivitySummary(ctx context.Context, id pgtype.UUID) (GetAdminActivitySummaryRow, error) {
	row := q.db.QueryRow(ctx, getAdminActivitySummary, id)
	var i GetAdminActivitySummaryRow
	err := row.Scan(
		&i.ID,
		&i.AdminLevel,
		&i.Department,
		&i.AssignedRegions,
		&i.Permissions,
		&i.TotalActivities,
		&i.LastActivity,
	)
	return i, err
}

const getAdminContactInfo = `-- name: GetAdminContactInfo :one
SELECT 
    sa.id,
    u.email,
    u.phone as personal_phone,
    sa.work_phone,
    sa.extension,
    sa.department
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
WHERE sa.id = $1
`

type GetAdminContactInfoRow struct {
	ID            pgtype.UUID `json:"id"`
	Email         string      `json:"email"`
	PersonalPhone pgtype.Text `json:"personal_phone"`
	WorkPhone     pgtype.Text `json:"work_phone"`
	Extension     pgtype.Text `json:"extension"`
	Department    pgtype.Text `json:"department"`
}

func (q *Queries) GetAdminContactInfo(ctx context.Context, id pgtype.UUID) (GetAdminContactInfoRow, error) {
	row := q.db.QueryRow(ctx, getAdminContactInfo, id)
	var i GetAdminContactInfoRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PersonalPhone,
		&i.WorkPhone,
		&i.Extension,
		&i.Department,
	)
	return i, err
}

const getAdminLevelDistribution = `-- name: GetAdminLevelDistribution :many
SELECT 
    admin_level,
    COUNT(*) as admin_count,
    AVG(array_length(assigned_regions, 1)) FILTER (WHERE assigned_regions IS NOT NULL) as avg_regions_per_admin
FROM system_admins
GROUP BY admin_level
ORDER BY 
    CASE admin_level
        WHEN 'super_admin' THEN 1
        WHEN 'regional_admin' THEN 2
        WHEN 'support_admin' THEN 3
        ELSE 4
    END
`

type GetAdminLevelDistributionRow struct {
	AdminLevel         string  `json:"admin_level"`
	AdminCount         int64   `json:"admin_count"`
	AvgRegionsPerAdmin float64 `json:"avg_regions_per_admin"`
}

func (q *Queries) GetAdminLevelDistribution(ctx context.Context) ([]GetAdminLevelDistributionRow, error) {
	rows, err := q.db.Query(ctx, getAdminLevelDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminLevelDistributionRow{}
	for rows.Next() {
		var i GetAdminLevelDistributionRow
		if err := rows.Scan(&i.AdminLevel, &i.AdminCount, &i.AvgRegionsPerAdmin); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminPermissions = `-- name: GetAdminPermissions :one
SELECT 
    admin_level,
    permissions,
    can_manage_users,
    can_manage_clinics,
    can_manage_content,
    can_view_analytics,
    can_manage_system,
    assigned_regions
FROM system_admins
WHERE user_id = $1
`

type GetAdminPermissionsRow struct {
	AdminLevel       string      `json:"admin_level"`
	Permissions      []byte      `json:"permissions"`
	CanManageUsers   pgtype.Bool `json:"can_manage_users"`
	CanManageClinics pgtype.Bool `json:"can_manage_clinics"`
	CanManageContent pgtype.Bool `json:"can_manage_content"`
	CanViewAnalytics pgtype.Bool `json:"can_view_analytics"`
	CanManageSystem  pgtype.Bool `json:"can_manage_system"`
	AssignedRegions  []string    `json:"assigned_regions"`
}

func (q *Queries) GetAdminPermissions(ctx context.Context, userID pgtype.UUID) (GetAdminPermissionsRow, error) {
	row := q.db.QueryRow(ctx, getAdminPermissions, userID)
	var i GetAdminPermissionsRow
	err := row.Scan(
		&i.AdminLevel,
		&i.Permissions,
		&i.CanManageUsers,
		&i.CanManageClinics,
		&i.CanManageContent,
		&i.CanViewAnalytics,
		&i.CanManageSystem,
		&i.AssignedRegions,
	)
	return i, err
}

const getAdminsByDepartment = `-- name: GetAdminsByDepartment :many

SELECT 
    sa.id,
    sa.user_id,
    u.email,
    sa.admin_level,
    sa.work_phone,
    sa.extension
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
WHERE sa.department = $1
ORDER BY sa.admin_level, sa.created_at
`

type GetAdminsByDepartmentRow struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	Email      string      `json:"email"`
	AdminLevel string      `json:"admin_level"`
	WorkPhone  pgtype.Text `json:"work_phone"`
	Extension  pgtype.Text `json:"extension"`
}

// ============================================
// DEPARTMENT QUERIES
// ============================================
func (q *Queries) GetAdminsByDepartment(ctx context.Context, department pgtype.Text) ([]GetAdminsByDepartmentRow, error) {
	rows, err := q.db.Query(ctx, getAdminsByDepartment, department)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminsByDepartmentRow{}
	for rows.Next() {
		var i GetAdminsByDepartmentRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.AdminLevel,
			&i.WorkPhone,
			&i.Extension,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminsByLevel = `-- name: GetAdminsByLevel :many

SELECT 
    sa.id,
    sa.user_id,
    u.email,
    u.phone,
    sa.admin_level,
    sa.department,
    sa.assigned_regions,
    sa.work_phone,
    sa.created_at
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
WHERE sa.admin_level = $1
ORDER BY sa.created_at DESC
`

type GetAdminsByLevelRow struct {
	ID              pgtype.UUID      `json:"id"`
	UserID          pgtype.UUID      `json:"user_id"`
	Email           string           `json:"email"`
	Phone           pgtype.Text      `json:"phone"`
	AdminLevel      string           `json:"admin_level"`
	Department      pgtype.Text      `json:"department"`
	AssignedRegions []string         `json:"assigned_regions"`
	WorkPhone       pgtype.Text      `json:"work_phone"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

// ============================================
// ADMIN LEVEL QUERIES
// ============================================
func (q *Queries) GetAdminsByLevel(ctx context.Context, adminLevel string) ([]GetAdminsByLevelRow, error) {
	rows, err := q.db.Query(ctx, getAdminsByLevel, adminLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminsByLevelRow{}
	for rows.Next() {
		var i GetAdminsByLevelRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.Phone,
			&i.AdminLevel,
			&i.Department,
			&i.AssignedRegions,
			&i.WorkPhone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminsByRegion = `-- name: GetAdminsByRegion :many
SELECT 
    sa.id,
    sa.user_id,
    u.email,
    u.phone,
    sa.admin_level,
    sa.department,
    sa.work_phone
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
WHERE $1 = ANY(sa.assigned_regions)
ORDER BY sa.admin_level, sa.created_at
`

type GetAdminsByRegionRow struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	Email      string      `json:"email"`
	Phone      pgtype.Text `json:"phone"`
	AdminLevel string      `json:"admin_level"`
	Department pgtype.Text `json:"department"`
	WorkPhone  pgtype.Text `json:"work_phone"`
}

func (q *Queries) GetAdminsByRegion(ctx context.Context, assignedRegions []string) ([]GetAdminsByRegionRow, error) {
	rows, err := q.db.Query(ctx, getAdminsByRegion, assignedRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminsByRegionRow{}
	for rows.Next() {
		var i GetAdminsByRegionRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.Phone,
			&i.AdminLevel,
			&i.Department,
			&i.WorkPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminsByUserIDs = `-- name: GetAdminsByUserIDs :many

SELECT 
    sa.id,
    sa.user_id,
    sa.admin_level,
    sa.department,
    sa.permissions
FROM system_admins sa
WHERE sa.user_id = ANY($1::uuid[])
ORDER BY sa.admin_level
`

type GetAdminsByUserIDsRow struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	AdminLevel  string      `json:"admin_level"`
	Department  pgtype.Text `json:"department"`
	Permissions []byte      `json:"permissions"`
}

// ============================================
// BULK OPERATIONS
// ============================================
func (q *Queries) GetAdminsByUserIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetAdminsByUserIDsRow, error) {
	rows, err := q.db.Query(ctx, getAdminsByUserIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminsByUserIDsRow{}
	for rows.Next() {
		var i GetAdminsByUserIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AdminLevel,
			&i.Department,
			&i.Permissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminsWithAnalyticsAccess = `-- name: GetAdminsWithAnalyticsAccess :many
SELECT 
    sa.id,
    sa.user_id,
    u.email,
    sa.admin_level,
    sa.department
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
WHERE sa.can_view_analytics = true
ORDER BY sa.admin_level, sa.created_at
`

type GetAdminsWithAnalyticsAccessRow struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	Email      string      `json:"email"`
	AdminLevel string      `json:"admin_level"`
	Department pgtype.Text `json:"department"`
}

func (q *Queries) GetAdminsWithAnalyticsAccess(ctx context.Context) ([]GetAdminsWithAnalyticsAccessRow, error) {
	rows, err := q.db.Query(ctx, getAdminsWithAnalyticsAccess)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminsWithAnalyticsAccessRow{}
	for rows.Next() {
		var i GetAdminsWithAnalyticsAccessRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.AdminLevel,
			&i.Department,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminsWithClinicManagement = `-- name: GetAdminsWithClinicManagement :many
SELECT 
    sa.id,
    sa.user_id,
    u.email,
    sa.admin_level,
    sa.assigned_regions
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
WHERE sa.can_manage_clinics = true
ORDER BY sa.admin_level, sa.created_at
`

type GetAdminsWithClinicManagementRow struct {
	ID              pgtype.UUID `json:"id"`
	UserID          pgtype.UUID `json:"user_id"`
	Email           string      `json:"email"`
	AdminLevel      string      `json:"admin_level"`
	AssignedRegions []string    `json:"assigned_regions"`
}

func (q *Queries) GetAdminsWithClinicManagement(ctx context.Context) ([]GetAdminsWithClinicManagementRow, error) {
	rows, err := q.db.Query(ctx, getAdminsWithClinicManagement)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminsWithClinicManagementRow{}
	for rows.Next() {
		var i GetAdminsWithClinicManagementRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.AdminLevel,
			&i.AssignedRegions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminsWithContentManagement = `-- name: GetAdminsWithContentManagement :many
SELECT 
    sa.id,
    sa.user_id,
    u.email,
    sa.admin_level,
    sa.department
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
WHERE sa.can_manage_content = true
ORDER BY sa.admin_level, sa.created_at
`

type GetAdminsWithContentManagementRow struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	Email      string      `json:"email"`
	AdminLevel string      `json:"admin_level"`
	Department pgtype.Text `json:"department"`
}

func (q *Queries) GetAdminsWithContentManagement(ctx context.Context) ([]GetAdminsWithContentManagementRow, error) {
	rows, err := q.db.Query(ctx, getAdminsWithContentManagement)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminsWithContentManagementRow{}
	for rows.Next() {
		var i GetAdminsWithContentManagementRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.AdminLevel,
			&i.Department,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminsWithLimitedPermissions = `-- name: GetAdminsWithLimitedPermissions :many
SELECT 
    sa.id,
    sa.user_id,
    u.email,
    sa.admin_level,
    sa.permissions
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
WHERE 
    NOT (sa.can_manage_users AND sa.can_manage_clinics AND 
         sa.can_manage_content AND sa.can_view_analytics AND 
         sa.can_manage_system)
ORDER BY sa.admin_level, sa.created_at
`

type GetAdminsWithLimitedPermissionsRow struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	Email       string      `json:"email"`
	AdminLevel  string      `json:"admin_level"`
	Permissions []byte      `json:"permissions"`
}

func (q *Queries) GetAdminsWithLimitedPermissions(ctx context.Context) ([]GetAdminsWithLimitedPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getAdminsWithLimitedPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminsWithLimitedPermissionsRow{}
	for rows.Next() {
		var i GetAdminsWithLimitedPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.AdminLevel,
			&i.Permissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminsWithNoRecentActivity = `-- name: GetAdminsWithNoRecentActivity :many
SELECT 
    sa.id,
    sa.user_id,
    u.email,
    sa.admin_level,
    MAX(ua.performed_at) as last_activity
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
LEFT JOIN user_activities ua ON sa.user_id = ua.user_id
GROUP BY sa.id, sa.user_id, u.email, sa.admin_level
HAVING MAX(ua.performed_at) < $1 OR MAX(ua.performed_at) IS NULL
ORDER BY last_activity ASC NULLS FIRST
`

type GetAdminsWithNoRecentActivityRow struct {
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	Email        string      `json:"email"`
	AdminLevel   string      `json:"admin_level"`
	LastActivity interface{} `json:"last_activity"`
}

func (q *Queries) GetAdminsWithNoRecentActivity(ctx context.Context, performedAt pgtype.Timestamp) ([]GetAdminsWithNoRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, getAdminsWithNoRecentActivity, performedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminsWithNoRecentActivityRow{}
	for rows.Next() {
		var i GetAdminsWithNoRecentActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.AdminLevel,
			&i.LastActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminsWithPermission = `-- name: GetAdminsWithPermission :many
SELECT 
    sa.id,
    sa.user_id,
    u.email,
    sa.admin_level,
    sa.permissions
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
WHERE 
    (CASE 
        WHEN $1 = 'manage_users' THEN sa.can_manage_users
        WHEN $1 = 'manage_clinics' THEN sa.can_manage_clinics
        WHEN $1 = 'manage_content' THEN sa.can_manage_content
        WHEN $1 = 'view_analytics' THEN sa.can_view_analytics
        WHEN $1 = 'manage_system' THEN sa.can_manage_system
        ELSE false
    END) = true
ORDER BY sa.admin_level, sa.created_at
`

type GetAdminsWithPermissionRow struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	Email       string      `json:"email"`
	AdminLevel  string      `json:"admin_level"`
	Permissions []byte      `json:"permissions"`
}

func (q *Queries) GetAdminsWithPermission(ctx context.Context, dollar_1 interface{}) ([]GetAdminsWithPermissionRow, error) {
	rows, err := q.db.Query(ctx, getAdminsWithPermission, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminsWithPermissionRow{}
	for rows.Next() {
		var i GetAdminsWithPermissionRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.AdminLevel,
			&i.Permissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminsWithSystemManagement = `-- name: GetAdminsWithSystemManagement :many
SELECT 
    sa.id,
    sa.user_id,
    u.email,
    sa.admin_level,
    sa.department
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
WHERE sa.can_manage_system = true
ORDER BY sa.admin_level, sa.created_at
`

type GetAdminsWithSystemManagementRow struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	Email      string      `json:"email"`
	AdminLevel string      `json:"admin_level"`
	Department pgtype.Text `json:"department"`
}

func (q *Queries) GetAdminsWithSystemManagement(ctx context.Context) ([]GetAdminsWithSystemManagementRow, error) {
	rows, err := q.db.Query(ctx, getAdminsWithSystemManagement)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminsWithSystemManagementRow{}
	for rows.Next() {
		var i GetAdminsWithSystemManagementRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.AdminLevel,
			&i.Department,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminsWithUserManagement = `-- name: GetAdminsWithUserManagement :many

SELECT 
    sa.id,
    sa.user_id,
    u.email,
    sa.admin_level,
    sa.department
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
WHERE sa.can_manage_users = true
ORDER BY sa.admin_level, sa.created_at
`

type GetAdminsWithUserManagementRow struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	Email      string      `json:"email"`
	AdminLevel string      `json:"admin_level"`
	Department pgtype.Text `json:"department"`
}

// ============================================
// PERMISSION-BASED QUERIES
// ============================================
func (q *Queries) GetAdminsWithUserManagement(ctx context.Context) ([]GetAdminsWithUserManagementRow, error) {
	rows, err := q.db.Query(ctx, getAdminsWithUserManagement)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminsWithUserManagementRow{}
	for rows.Next() {
		var i GetAdminsWithUserManagementRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.AdminLevel,
			&i.Department,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminsWithoutRegions = `-- name: GetAdminsWithoutRegions :many
SELECT 
    sa.id,
    sa.user_id,
    u.email,
    sa.admin_level,
    sa.department
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
WHERE 
    sa.admin_level = 'regional_admin'
    AND (sa.assigned_regions IS NULL OR array_length(sa.assigned_regions, 1) = 0)
ORDER BY sa.created_at
`

type GetAdminsWithoutRegionsRow struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	Email      string      `json:"email"`
	AdminLevel string      `json:"admin_level"`
	Department pgtype.Text `json:"department"`
}

func (q *Queries) GetAdminsWithoutRegions(ctx context.Context) ([]GetAdminsWithoutRegionsRow, error) {
	rows, err := q.db.Query(ctx, getAdminsWithoutRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminsWithoutRegionsRow{}
	for rows.Next() {
		var i GetAdminsWithoutRegionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.AdminLevel,
			&i.Department,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSystemAdmins = `-- name: GetAllSystemAdmins :many
SELECT 
    sa.id,
    sa.user_id,
    u.email,
    sa.admin_level,
    sa.department,
    sa.work_phone
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
ORDER BY sa.admin_level, sa.created_at
`

type GetAllSystemAdminsRow struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	Email      string      `json:"email"`
	AdminLevel string      `json:"admin_level"`
	Department pgtype.Text `json:"department"`
	WorkPhone  pgtype.Text `json:"work_phone"`
}

func (q *Queries) GetAllSystemAdmins(ctx context.Context) ([]GetAllSystemAdminsRow, error) {
	rows, err := q.db.Query(ctx, getAllSystemAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllSystemAdminsRow{}
	for rows.Next() {
		var i GetAllSystemAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.AdminLevel,
			&i.Department,
			&i.WorkPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDepartmentList = `-- name: GetDepartmentList :many
SELECT DISTINCT department
FROM system_admins
WHERE department IS NOT NULL
ORDER BY department
`

func (q *Queries) GetDepartmentList(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, getDepartmentList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var department pgtype.Text
		if err := rows.Scan(&department); err != nil {
			return nil, err
		}
		items = append(items, department)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionStatistics = `-- name: GetPermissionStatistics :one
SELECT 
    COUNT(*) FILTER (WHERE can_manage_users = true) as with_user_mgmt,
    COUNT(*) FILTER (WHERE can_manage_clinics = true) as with_clinic_mgmt,
    COUNT(*) FILTER (WHERE can_manage_content = true) as with_content_mgmt,
    COUNT(*) FILTER (WHERE can_view_analytics = true) as with_analytics,
    COUNT(*) FILTER (WHERE can_manage_system = true) as with_system_mgmt,
    COUNT(*) FILTER (WHERE 
        can_manage_users = true AND 
        can_manage_clinics = true AND 
        can_manage_content = true AND 
        can_view_analytics = true AND 
        can_manage_system = true
    ) as with_all_permissions
FROM system_admins
`

type GetPermissionStatisticsRow struct {
	WithUserMgmt       int64 `json:"with_user_mgmt"`
	WithClinicMgmt     int64 `json:"with_clinic_mgmt"`
	WithContentMgmt    int64 `json:"with_content_mgmt"`
	WithAnalytics      int64 `json:"with_analytics"`
	WithSystemMgmt     int64 `json:"with_system_mgmt"`
	WithAllPermissions int64 `json:"with_all_permissions"`
}

func (q *Queries) GetPermissionStatistics(ctx context.Context) (GetPermissionStatisticsRow, error) {
	row := q.db.QueryRow(ctx, getPermissionStatistics)
	var i GetPermissionStatisticsRow
	err := row.Scan(
		&i.WithUserMgmt,
		&i.WithClinicMgmt,
		&i.WithContentMgmt,
		&i.WithAnalytics,
		&i.WithSystemMgmt,
		&i.WithAllPermissions,
	)
	return i, err
}

const getRecentlyCreatedAdmins = `-- name: GetRecentlyCreatedAdmins :many

SELECT 
    sa.id,
    sa.user_id,
    u.email,
    sa.admin_level,
    sa.department,
    sa.created_at
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
WHERE sa.created_at >= $1
ORDER BY sa.created_at DESC
`

type GetRecentlyCreatedAdminsRow struct {
	ID         pgtype.UUID      `json:"id"`
	UserID     pgtype.UUID      `json:"user_id"`
	Email      string           `json:"email"`
	AdminLevel string           `json:"admin_level"`
	Department pgtype.Text      `json:"department"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

// ============================================
// AUDIT & REPORTING
// ============================================
func (q *Queries) GetRecentlyCreatedAdmins(ctx context.Context, createdAt pgtype.Timestamp) ([]GetRecentlyCreatedAdminsRow, error) {
	rows, err := q.db.Query(ctx, getRecentlyCreatedAdmins, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentlyCreatedAdminsRow{}
	for rows.Next() {
		var i GetRecentlyCreatedAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.AdminLevel,
			&i.Department,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentlyUpdatedAdmins = `-- name: GetRecentlyUpdatedAdmins :many
SELECT 
    sa.id,
    sa.user_id,
    u.email,
    sa.admin_level,
    sa.updated_at
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
WHERE sa.updated_at >= $1
ORDER BY sa.updated_at DESC
`

type GetRecentlyUpdatedAdminsRow struct {
	ID         pgtype.UUID      `json:"id"`
	UserID     pgtype.UUID      `json:"user_id"`
	Email      string           `json:"email"`
	AdminLevel string           `json:"admin_level"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetRecentlyUpdatedAdmins(ctx context.Context, updatedAt pgtype.Timestamp) ([]GetRecentlyUpdatedAdminsRow, error) {
	rows, err := q.db.Query(ctx, getRecentlyUpdatedAdmins, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentlyUpdatedAdminsRow{}
	for rows.Next() {
		var i GetRecentlyUpdatedAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.AdminLevel,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRegionCoverage = `-- name: GetRegionCoverage :many
SELECT 
    unnest(assigned_regions) as region,
    COUNT(*) as admin_count
FROM system_admins
WHERE assigned_regions IS NOT NULL
GROUP BY region
ORDER BY admin_count DESC
`

type GetRegionCoverageRow struct {
	Region     interface{} `json:"region"`
	AdminCount int64       `json:"admin_count"`
}

func (q *Queries) GetRegionCoverage(ctx context.Context) ([]GetRegionCoverageRow, error) {
	rows, err := q.db.Query(ctx, getRegionCoverage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRegionCoverageRow{}
	for rows.Next() {
		var i GetRegionCoverageRow
		if err := rows.Scan(&i.Region, &i.AdminCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRegionalAdmins = `-- name: GetRegionalAdmins :many
SELECT 
    sa.id,
    sa.user_id,
    u.email,
    sa.assigned_regions,
    sa.department,
    sa.work_phone
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
WHERE sa.admin_level = 'regional_admin'
ORDER BY sa.created_at DESC
`

type GetRegionalAdminsRow struct {
	ID              pgtype.UUID `json:"id"`
	UserID          pgtype.UUID `json:"user_id"`
	Email           string      `json:"email"`
	AssignedRegions []string    `json:"assigned_regions"`
	Department      pgtype.Text `json:"department"`
	WorkPhone       pgtype.Text `json:"work_phone"`
}

func (q *Queries) GetRegionalAdmins(ctx context.Context) ([]GetRegionalAdminsRow, error) {
	rows, err := q.db.Query(ctx, getRegionalAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRegionalAdminsRow{}
	for rows.Next() {
		var i GetRegionalAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.AssignedRegions,
			&i.Department,
			&i.WorkPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRegionsForAdmin = `-- name: GetRegionsForAdmin :one
SELECT assigned_regions
FROM system_admins
WHERE id = $1
`

func (q *Queries) GetRegionsForAdmin(ctx context.Context, id pgtype.UUID) ([]string, error) {
	row := q.db.QueryRow(ctx, getRegionsForAdmin, id)
	var assigned_regions []string
	err := row.Scan(&assigned_regions)
	return assigned_regions, err
}

const getSuperAdmins = `-- name: GetSuperAdmins :many
SELECT 
    sa.id,
    sa.user_id,
    u.email,
    u.phone,
    sa.department,
    sa.work_phone,
    sa.created_at
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
WHERE sa.admin_level = 'super_admin'
ORDER BY sa.created_at DESC
`

type GetSuperAdminsRow struct {
	ID         pgtype.UUID      `json:"id"`
	UserID     pgtype.UUID      `json:"user_id"`
	Email      string           `json:"email"`
	Phone      pgtype.Text      `json:"phone"`
	Department pgtype.Text      `json:"department"`
	WorkPhone  pgtype.Text      `json:"work_phone"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetSuperAdmins(ctx context.Context) ([]GetSuperAdminsRow, error) {
	rows, err := q.db.Query(ctx, getSuperAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSuperAdminsRow{}
	for rows.Next() {
		var i GetSuperAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.Phone,
			&i.Department,
			&i.WorkPhone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSupportAdmins = `-- name: GetSupportAdmins :many
SELECT 
    sa.id,
    sa.user_id,
    u.email,
    sa.department,
    sa.work_phone,
    sa.extension
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
WHERE sa.admin_level = 'support_admin'
ORDER BY sa.created_at DESC
`

type GetSupportAdminsRow struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	Email      string      `json:"email"`
	Department pgtype.Text `json:"department"`
	WorkPhone  pgtype.Text `json:"work_phone"`
	Extension  pgtype.Text `json:"extension"`
}

func (q *Queries) GetSupportAdmins(ctx context.Context) ([]GetSupportAdminsRow, error) {
	rows, err := q.db.Query(ctx, getSupportAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSupportAdminsRow{}
	for rows.Next() {
		var i GetSupportAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.Department,
			&i.WorkPhone,
			&i.Extension,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSystemAdmin = `-- name: GetSystemAdmin :one
SELECT id, user_id, admin_level, assigned_regions, department, permissions, can_manage_users, can_manage_clinics, can_manage_content, can_view_analytics, can_manage_system, work_phone, extension, created_at, updated_at FROM system_admins
WHERE id = $1
`

func (q *Queries) GetSystemAdmin(ctx context.Context, id pgtype.UUID) (SystemAdmin, error) {
	row := q.db.QueryRow(ctx, getSystemAdmin, id)
	var i SystemAdmin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AdminLevel,
		&i.AssignedRegions,
		&i.Department,
		&i.Permissions,
		&i.CanManageUsers,
		&i.CanManageClinics,
		&i.CanManageContent,
		&i.CanViewAnalytics,
		&i.CanManageSystem,
		&i.WorkPhone,
		&i.Extension,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemAdminByUserID = `-- name: GetSystemAdminByUserID :one
SELECT id, user_id, admin_level, assigned_regions, department, permissions, can_manage_users, can_manage_clinics, can_manage_content, can_view_analytics, can_manage_system, work_phone, extension, created_at, updated_at FROM system_admins
WHERE user_id = $1
`

func (q *Queries) GetSystemAdminByUserID(ctx context.Context, userID pgtype.UUID) (SystemAdmin, error) {
	row := q.db.QueryRow(ctx, getSystemAdminByUserID, userID)
	var i SystemAdmin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AdminLevel,
		&i.AssignedRegions,
		&i.Department,
		&i.Permissions,
		&i.CanManageUsers,
		&i.CanManageClinics,
		&i.CanManageContent,
		&i.CanViewAnalytics,
		&i.CanManageSystem,
		&i.WorkPhone,
		&i.Extension,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const grantAnalyticsAccess = `-- name: GrantAnalyticsAccess :exec
UPDATE system_admins
SET 
    can_view_analytics = true,
    permissions = jsonb_set(permissions, '{view_analytics}', 'true', true),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) GrantAnalyticsAccess(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, grantAnalyticsAccess, id)
	return err
}

const grantClinicManagement = `-- name: GrantClinicManagement :exec
UPDATE system_admins
SET 
    can_manage_clinics = true,
    permissions = jsonb_set(permissions, '{manage_clinics}', 'true', true),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) GrantClinicManagement(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, grantClinicManagement, id)
	return err
}

const grantContentManagement = `-- name: GrantContentManagement :exec
UPDATE system_admins
SET 
    can_manage_content = true,
    permissions = jsonb_set(permissions, '{manage_content}', 'true', true),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) GrantContentManagement(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, grantContentManagement, id)
	return err
}

const grantSystemManagement = `-- name: GrantSystemManagement :exec
UPDATE system_admins
SET 
    can_manage_system = true,
    permissions = jsonb_set(permissions, '{manage_system}', 'true', true),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) GrantSystemManagement(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, grantSystemManagement, id)
	return err
}

const grantUserManagement = `-- name: GrantUserManagement :exec
UPDATE system_admins
SET 
    can_manage_users = true,
    permissions = jsonb_set(permissions, '{manage_users}', 'true', true),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) GrantUserManagement(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, grantUserManagement, id)
	return err
}

const listSystemAdmins = `-- name: ListSystemAdmins :many

SELECT 
    sa.id,
    sa.user_id,
    u.email,
    u.phone,
    sa.admin_level,
    sa.department,
    sa.assigned_regions,
    sa.can_manage_users,
    sa.can_manage_clinics,
    sa.can_view_analytics,
    sa.created_at
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
ORDER BY 
    CASE sa.admin_level
        WHEN 'super_admin' THEN 1
        WHEN 'regional_admin' THEN 2
        WHEN 'support_admin' THEN 3
        ELSE 4
    END,
    sa.created_at DESC
LIMIT $1 OFFSET $2
`

type ListSystemAdminsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListSystemAdminsRow struct {
	ID               pgtype.UUID      `json:"id"`
	UserID           pgtype.UUID      `json:"user_id"`
	Email            string           `json:"email"`
	Phone            pgtype.Text      `json:"phone"`
	AdminLevel       string           `json:"admin_level"`
	Department       pgtype.Text      `json:"department"`
	AssignedRegions  []string         `json:"assigned_regions"`
	CanManageUsers   pgtype.Bool      `json:"can_manage_users"`
	CanManageClinics pgtype.Bool      `json:"can_manage_clinics"`
	CanViewAnalytics pgtype.Bool      `json:"can_view_analytics"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

// ============================================
// LISTING & PAGINATION
// ============================================
func (q *Queries) ListSystemAdmins(ctx context.Context, arg ListSystemAdminsParams) ([]ListSystemAdminsRow, error) {
	rows, err := q.db.Query(ctx, listSystemAdmins, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSystemAdminsRow{}
	for rows.Next() {
		var i ListSystemAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.Phone,
			&i.AdminLevel,
			&i.Department,
			&i.AssignedRegions,
			&i.CanManageUsers,
			&i.CanManageClinics,
			&i.CanViewAnalytics,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteToSuperAdmin = `-- name: PromoteToSuperAdmin :exec
UPDATE system_admins
SET 
    admin_level = 'super_admin',
    can_manage_users = true,
    can_manage_clinics = true,
    can_manage_content = true,
    can_view_analytics = true,
    can_manage_system = true,
    permissions = jsonb_build_object(
        'manage_users', true,
        'manage_clinics', true,
        'manage_content', true,
        'view_analytics', true,
        'manage_system', true
    ),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) PromoteToSuperAdmin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, promoteToSuperAdmin, id)
	return err
}

const removeRegionAssignment = `-- name: RemoveRegionAssignment :exec
UPDATE system_admins
SET 
    assigned_regions = array_remove(assigned_regions, $2),
    updated_at = NOW()
WHERE id = $1
`

type RemoveRegionAssignmentParams struct {
	ID          pgtype.UUID `json:"id"`
	ArrayRemove interface{} `json:"array_remove"`
}

func (q *Queries) RemoveRegionAssignment(ctx context.Context, arg RemoveRegionAssignmentParams) error {
	_, err := q.db.Exec(ctx, removeRegionAssignment, arg.ID, arg.ArrayRemove)
	return err
}

const revokeAnalyticsAccess = `-- name: RevokeAnalyticsAccess :exec
UPDATE system_admins
SET 
    can_view_analytics = false,
    permissions = jsonb_set(permissions, '{view_analytics}', 'false', true),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeAnalyticsAccess(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAnalyticsAccess, id)
	return err
}

const revokeClinicManagement = `-- name: RevokeClinicManagement :exec
UPDATE system_admins
SET 
    can_manage_clinics = false,
    permissions = jsonb_set(permissions, '{manage_clinics}', 'false', true),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeClinicManagement(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeClinicManagement, id)
	return err
}

const revokeContentManagement = `-- name: RevokeContentManagement :exec
UPDATE system_admins
SET 
    can_manage_content = false,
    permissions = jsonb_set(permissions, '{manage_content}', 'false', true),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeContentManagement(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeContentManagement, id)
	return err
}

const revokeSystemManagement = `-- name: RevokeSystemManagement :exec
UPDATE system_admins
SET 
    can_manage_system = false,
    permissions = jsonb_set(permissions, '{manage_system}', 'false', true),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeSystemManagement(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSystemManagement, id)
	return err
}

const revokeUserManagement = `-- name: RevokeUserManagement :exec
UPDATE system_admins
SET 
    can_manage_users = false,
    permissions = jsonb_set(permissions, '{manage_users}', 'false', true),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeUserManagement(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserManagement, id)
	return err
}

const searchSystemAdmins = `-- name: SearchSystemAdmins :many

SELECT 
    sa.id,
    sa.user_id,
    u.email,
    u.phone,
    sa.admin_level,
    sa.department,
    sa.assigned_regions,
    sa.work_phone
FROM system_admins sa
JOIN users u ON sa.user_id = u.id
WHERE 
    ($1::VARCHAR IS NULL OR u.email ILIKE '%' || $1 || '%')
    AND ($2::VARCHAR IS NULL OR sa.admin_level = $2)
    AND ($3::VARCHAR IS NULL OR sa.department = $3)
    AND ($4::VARCHAR IS NULL OR $4 = ANY(sa.assigned_regions))
ORDER BY sa.admin_level, sa.created_at DESC
`

type SearchSystemAdminsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
}

type SearchSystemAdminsRow struct {
	ID              pgtype.UUID `json:"id"`
	UserID          pgtype.UUID `json:"user_id"`
	Email           string      `json:"email"`
	Phone           pgtype.Text `json:"phone"`
	AdminLevel      string      `json:"admin_level"`
	Department      pgtype.Text `json:"department"`
	AssignedRegions []string    `json:"assigned_regions"`
	WorkPhone       pgtype.Text `json:"work_phone"`
}

// ============================================
// SEARCH & FILTERING
// ============================================
func (q *Queries) SearchSystemAdmins(ctx context.Context, arg SearchSystemAdminsParams) ([]SearchSystemAdminsRow, error) {
	rows, err := q.db.Query(ctx, searchSystemAdmins,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSystemAdminsRow{}
	for rows.Next() {
		var i SearchSystemAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.Phone,
			&i.AdminLevel,
			&i.Department,
			&i.AssignedRegions,
			&i.WorkPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminLevel = `-- name: UpdateAdminLevel :exec
UPDATE system_admins
SET 
    admin_level = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateAdminLevelParams struct {
	ID         pgtype.UUID `json:"id"`
	AdminLevel string      `json:"admin_level"`
}

func (q *Queries) UpdateAdminLevel(ctx context.Context, arg UpdateAdminLevelParams) error {
	_, err := q.db.Exec(ctx, updateAdminLevel, arg.ID, arg.AdminLevel)
	return err
}

const updateAdminPermissions = `-- name: UpdateAdminPermissions :exec

UPDATE system_admins
SET 
    permissions = $2,
    can_manage_users = $3,
    can_manage_clinics = $4,
    can_manage_content = $5,
    can_view_analytics = $6,
    can_manage_system = $7,
    updated_at = NOW()
WHERE id = $1
`

type UpdateAdminPermissionsParams struct {
	ID               pgtype.UUID `json:"id"`
	Permissions      []byte      `json:"permissions"`
	CanManageUsers   pgtype.Bool `json:"can_manage_users"`
	CanManageClinics pgtype.Bool `json:"can_manage_clinics"`
	CanManageContent pgtype.Bool `json:"can_manage_content"`
	CanViewAnalytics pgtype.Bool `json:"can_view_analytics"`
	CanManageSystem  pgtype.Bool `json:"can_manage_system"`
}

// ============================================
// PERMISSIONS MANAGEMENT
// ============================================
func (q *Queries) UpdateAdminPermissions(ctx context.Context, arg UpdateAdminPermissionsParams) error {
	_, err := q.db.Exec(ctx, updateAdminPermissions,
		arg.ID,
		arg.Permissions,
		arg.CanManageUsers,
		arg.CanManageClinics,
		arg.CanManageContent,
		arg.CanViewAnalytics,
		arg.CanManageSystem,
	)
	return err
}

const updateAssignedRegions = `-- name: UpdateAssignedRegions :exec

UPDATE system_admins
SET 
    assigned_regions = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateAssignedRegionsParams struct {
	ID              pgtype.UUID `json:"id"`
	AssignedRegions []string    `json:"assigned_regions"`
}

// ============================================
// REGIONAL ASSIGNMENT QUERIES
// ============================================
func (q *Queries) UpdateAssignedRegions(ctx context.Context, arg UpdateAssignedRegionsParams) error {
	_, err := q.db.Exec(ctx, updateAssignedRegions, arg.ID, arg.AssignedRegions)
	return err
}

const updateContactInfo = `-- name: UpdateContactInfo :exec

UPDATE system_admins
SET 
    work_phone = COALESCE($2, work_phone),
    extension = COALESCE($3, extension),
    updated_at = NOW()
WHERE id = $1
`

type UpdateContactInfoParams struct {
	ID        pgtype.UUID `json:"id"`
	WorkPhone pgtype.Text `json:"work_phone"`
	Extension pgtype.Text `json:"extension"`
}

// ============================================
// CONTACT INFORMATION
// ============================================
func (q *Queries) UpdateContactInfo(ctx context.Context, arg UpdateContactInfoParams) error {
	_, err := q.db.Exec(ctx, updateContactInfo, arg.ID, arg.WorkPhone, arg.Extension)
	return err
}

const updateDepartment = `-- name: UpdateDepartment :exec
UPDATE system_admins
SET 
    department = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateDepartmentParams struct {
	ID         pgtype.UUID `json:"id"`
	Department pgtype.Text `json:"department"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) error {
	_, err := q.db.Exec(ctx, updateDepartment, arg.ID, arg.Department)
	return err
}

const updateExtension = `-- name: UpdateExtension :exec
UPDATE system_admins
SET 
    extension = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateExtensionParams struct {
	ID        pgtype.UUID `json:"id"`
	Extension pgtype.Text `json:"extension"`
}

func (q *Queries) UpdateExtension(ctx context.Context, arg UpdateExtensionParams) error {
	_, err := q.db.Exec(ctx, updateExtension, arg.ID, arg.Extension)
	return err
}

const updatePermissionsJSON = `-- name: UpdatePermissionsJSON :exec
UPDATE system_admins
SET 
    permissions = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdatePermissionsJSONParams struct {
	ID          pgtype.UUID `json:"id"`
	Permissions []byte      `json:"permissions"`
}

func (q *Queries) UpdatePermissionsJSON(ctx context.Context, arg UpdatePermissionsJSONParams) error {
	_, err := q.db.Exec(ctx, updatePermissionsJSON, arg.ID, arg.Permissions)
	return err
}

const updateSystemAdmin = `-- name: UpdateSystemAdmin :exec
UPDATE system_admins
SET 
    admin_level = COALESCE($2, admin_level),
    assigned_regions = COALESCE($3, assigned_regions),
    department = COALESCE($4, department),
    permissions = COALESCE($5, permissions),
    work_phone = COALESCE($6, work_phone),
    extension = COALESCE($7, extension),
    updated_at = NOW()
WHERE id = $1
`

type UpdateSystemAdminParams struct {
	ID              pgtype.UUID `json:"id"`
	AdminLevel      string      `json:"admin_level"`
	AssignedRegions []string    `json:"assigned_regions"`
	Department      pgtype.Text `json:"department"`
	Permissions     []byte      `json:"permissions"`
	WorkPhone       pgtype.Text `json:"work_phone"`
	Extension       pgtype.Text `json:"extension"`
}

func (q *Queries) UpdateSystemAdmin(ctx context.Context, arg UpdateSystemAdminParams) error {
	_, err := q.db.Exec(ctx, updateSystemAdmin,
		arg.ID,
		arg.AdminLevel,
		arg.AssignedRegions,
		arg.Department,
		arg.Permissions,
		arg.WorkPhone,
		arg.Extension,
	)
	return err
}

const updateWorkPhone = `-- name: UpdateWorkPhone :exec
UPDATE system_admins
SET 
    work_phone = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateWorkPhoneParams struct {
	ID        pgtype.UUID `json:"id"`
	WorkPhone pgtype.Text `json:"work_phone"`
}

func (q *Queries) UpdateWorkPhone(ctx context.Context, arg UpdateWorkPhoneParams) error {
	_, err := q.db.Exec(ctx, updateWorkPhone, arg.ID, arg.WorkPhone)
	return err
}
